### ISSUE TITLE
Disable SSL certificate validation

### ISSUE THREAD

**Issue by wget** [mageplaza/magento-2-smtp#1]
Dear Sir or Madam,

On a Magento 2.1 installation, for one of our client, we needed to connect to one of our mail server where we hosted a no-reply email address for our client.

However, since our mail server certificate is mail.mycompany.com and our client email will be site.myclientcom, the URl fields in the certificate does not correspond and PHP complains with this error

```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/website/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206
```

This line 206 is as follow:

```
if (!stream_socket_enable_crypto($this->_socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
```

I checked the PHP documentation, but wasn't able to find a way to disable PHP TLS certificate validation.

Do you have a proper way to achieve such a thing, without modifying your extension? Indeed, we still want to be able to apply updates to it, without repatching it manually. Thanks for your help.

**Comment by imsamthomas** [comment]
Hi,


Can you please provide us a temporary email account, password and Url to
support@mageplaza.com ?

Our team will look into this.

Regards,
Sam

**Comment by wget** [comment]
@imsamthomas I have sent an email to your wrt. this issue. Thanks.

**Comment by Slidey** [comment]
Hi! I'm in the same situation. Did you find a way to turn it off?

**Comment by wget** [comment]
@Slidey 

Here is what Mageplaza answered to me via an email:

> We have check the given information. But there is no idea about this. I think we need to modify the module to archive that.

No news since then from them.

On y side, I realized the only solution I had in mind was to setup a SMTP forwarded (MFA) with the same certificate as the address you want to send from and the latter connects to the official SMTP server.

Let me know if you have other ideas.

**Comment by wget** [comment]
I have another solution, in `Mageplaza/Smtp/Controller/Amdinhtml/Index/Index.php`, tehre is the following line:
```
$transport = new \Zend_Mail_Transport_Smtp($host, $config);
```

That class extends from `\Zend_Mail_Protocol_Abstract` which contains a method `_connect`.

That method is defined line 261 in `/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php`.

In that method, the socket is created with ` $this->_socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION);`.

According to the [PHP man pages](https://secure.php.net/manual/en/function.stream-socket-client.php), you can pass a socket context to that method.

This context can be created with [`resource stream_context_create ([ array $options [, array $params ]] )`](https://secure.php.net/manual/en/function.stream-context-create.php) as follow:

```
$stream_context = stream_context_create([ 'ssl' => [
'verify_peer'       => false,
'verify_peer_name'  => false,
'allow_self_signed' => true ]]);
```
[src.](https://php.net/manual/en/context.ssl.php#120278).

However, as soon I try to call my overriden class from `Index.php`, my class is not found:

```
$transport = new \Mageplaza\Smtp\Model\Config\Source\CustomMailProtocolSmtp($host, $config);
```

I checked with the following test which confirms my assumptions:
```
if (class_exists('\\Mageplaza\\Smtp\\Model\\Config\\Source\\CustomMailProtocolSmtp')) {
    $this->logger->addDebug('CLASS EXISTS');
} else {
    $this->logger->addDebug('CLASS NOT FOUND');
}
```

I know Magento uses the [dependency injection pattern](http://inchoo.net/magento-2/magento-2-logging/), but this shouldn't be the cause of the issue.

I even applied the recommandations [described here](https://magento.stackexchange.com/questions/112516/custom-module-does-not-get-its-classes-loaded) but the psr-4 location is defined correctly in the Module composer file and my class doesn't have `_` (underscores) anymore, so this should work out of the box.

I'm defining that new class in `/app/code/Mageplaza/Smtp/Model/Config/Source/CustomMailProtocolSmtp.php`.

Any idea why the class is not found?

**Comment by webtekindo** [comment]
We also have the same problem on localhost:

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\www\magento2rendy\vendor\magento\zendframework1\library\Zend\Mail\Protocol\Smtp.php on line 206

**Comment by webkulabhi** [comment]
I also got same issues
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /home/cellini/public_html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206

**Comment by KetulParikh** [comment]
Hello,
I am using magento2 platform. I got the error given below
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/magento/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206

**Comment by MackieeE** [comment]
Sadly I've had to hard-code a fix to allow this, especially as the first file uses `stream_socket_client` within a protected method. Two things here:

### vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php
```
/*
 * CORE CHANGE OF MAGENTO TO ALLOW LOCAL 
 * WITH SELF-CRET SMTPs
 */
$stream_context = stream_context_create(array(
	'ssl' => array(
		'verify_peer'       => false,
		'verify_peer_name'  => false,
		'allow_self_signed' => true
	)
));

// open connection
$this->_socket = stream_socket_client(
	$remote, 
	$errorNum, 
	$errorStr, 
	self::TIMEOUT_CONNECTION, 
	STREAM_CLIENT_CONNECT, 
	$stream_context 
);
```

The company I work at use a locally self signed SSL Cert for our `.local` domains.

The second issue I encountered was that the options page on the SMTP Configuration required a Username & Password.

### vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php

Some (Mine included) Local exchange servers don't require a full email username, unlike external SMTP Hosts. So my username would be:

`mackieee`

This returned `Invalid Address` as when it was attempting to formulate the Email headers - it would construct the header to have a `FROM` address set from the above:

```
From: Mackieee (mackieee)\r\n
Subject: article: SMTP Testl\r\n
To: test@example.com\r\n
...
```

Whereas the `FROM` Address was invalid. This is set at the line 208 from `SMTP.php`

**Comment by imsamthomas** [comment]
We fixed

**Comment by d0ky** [comment]
@imsamthomas how\where did you fixed? I've 1.1.2 release and still can experience the issue

**Comment by wget** [comment]
@d0ky Yes, from my understanding even by reading further commits, I can't see any fix for this issue. But maybe I'm wrong, but I doubt :)

**Comment by MackieeE** [comment]
Pretty sure he's mistaken this issue with recent pull request(s) #52 & #53.

**Comment by imsamthomas** [comment]
Sorry, I closed by mistake.
Thanks for your report, guys 👍

**Comment by AdamSEY** [comment]
I'm having same issue, but not using magento, just SMTP with php-mailer.

**Comment by MartinaEL** [comment]
I have this module installed and when I send the test email in the backend it works fine, yet when I try to share a Wishlist on the front end of my Magento2 site or a contact us form I get the following error;

`Warning: stream_socket_enable_crypto(): Peer certificate CN='xxx.com.au' did not match expected CN='localhost' in vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206`

After adding the fix suggested by @MackieeE I now get the following error on the frontend, yet test email still sends fine.

`Incorrect authentication data`

**Comment by AdamSEY** [comment]
I've fixed this problem: `Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/website/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206` by fixing my server time.

**Comment by wget** [comment]
@AdamSEY Sure, the error message you encountered can also be caused by a time issue. However, in this regard, the bug I opened is rather a feature missing: the ability to have a crypto channel enabled with a self signed certificate or a domain name mismatch between the real DNS and the one recorded in the certificate. The latter issue often occurs on shared email hosting for example :)

**Comment by gixid192** [comment]
Hey @wget,
Are you able to use Openssl to connect to the smtp in your server?

**Comment by wget** [comment]
@gixid192 Sure. This is a completely standard SMTP server using STARTTLS on 587, so yes.

**Comment by gixid192** [comment]
Are you still using Magento 2.1?
Here I found an answer from the author of Phpmailer. Could you follow and check again? https://github.com/PHPMailer/PHPMailer/issues/1276#issuecomment-350466528

Plus, Phpmailer also provides the Smtp connect function, you can try it, the reason is it logs more information than Magento itself.

Kindly let me know the result of your research here, thank you.

**Comment by wget** [comment]
@gixid192 Yes, my client is still on Magento 2.1. Yes, I know that using PHPMailer could fix the issue. This is what I do on WordPress websites for example
```
    $phpmailer->SMTPOptions = array(
        'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        )
    );
```

But for Magento, the point is I don't want to add another lib to the install process when simply overriding a class in the Zend Framework could do the job :)

**Comment by gixid192** [comment]
As you and others already provided the core-modified version, I think you can apply it to your store.
As the fix you posted is considered as a hack (Phpmailer author also said that) I think it won't be added into our extensions, this is not a good practice for security reason.

**Comment by gixid192** [comment]
I think we can close this issue from here, as you guys already provided the "hacked" solution.
If you agree, kindly help me close the issue @wget, thank you.

**Comment by wget** [comment]
@gixid192 What you could have done (and this is what I intended by reporting this bug) is that you simply add an option in the manager asking if the user wants or not to apply these verification.
Like for example, a drop down menu:
```
SSL options:
+-------------------------+
| Verify peer             |
+-------------------------+
| Don't verify peer       |
+-------------------------+

+-------------------------+
| Verify peer name        |
+-------------------------+
| Don't verify peer name  |
+-------------------------+

+-------------------------+
| Allow self signed       |
+-------------------------+
| Don't allow self signed |
+-------------------------+
```

**Comment by gixid192** [comment]
That's what we thought.
But unfortunately, not anyone is an expert, they just use the extension without knowing any else, some don't even know how to get the server and the port.
Imagine one only knows basic use that option and then their server mail got hacked. We can't take that risk.

This relates to Security and therefore, opt to not having those options is the best choice IMHO.

**Comment by wget** [comment]
@gixid192 Then just put these under an advanced area with a statement like `use these options at your own risk, only if you know what you are doing` and pre-select the most secure choices.

**Comment by gixid192** [comment]
We face that every day, the user guide, the faq, the instruction, no one read it, the issues on Github keep duplicating.
I'm sorry to let you down but we can't take that risk. It's just beyond our scope.

**Comment by gixid192** [comment]
I think we can close the issue here. If this is added in the feature versions, we will let you guys know the when it's released.

**Comment by EstebanAorta** [comment]
Found this solution. Maybe it helps someone. 


------------------------------------------------------------------------
vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php

(around line 200) change function _connect.



**replace**



`// open connection
        $this->socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION); `



**with**



`$contextOptions = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false
            )
        );`

        $context = stream_context_create($contextOptions);

        // open connection
        $this->socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION, STREAM_CLIENT_CONNECT, $context);

**Comment by tweetyx** [comment]
In vendor\magento\zendframework1\library\Zend\Mail\Protocol\Abstract.php
put
`        $stream_context = stream_context_create(array(
            'ssl' => array(
                'verify_peer'       => false,
                'verify_peer_name'  => false,
                'allow_self_signed' => true
            )
        ));

        // open connection
        $this->_socket = stream_socket_client(
            $remote,
            $errorNum,
            $errorStr,
            self::TIMEOUT_CONNECTION,
            STREAM_CLIENT_CONNECT,
            $stream_context 
);`

and in \vendor\magento\zendframework1\library\Zend\Mail\Protocol\Smtp\Auth\Login.php
copy your login and password in hardcoremode :

`        if (is_array($config)) {
            if (isset($config['username'])) {
                $this->_username = 'xxx@gmail.com';
            }
            if (isset($config['password'])) {
                $this->_password = 'yourpassword';
            }
        }`

**Comment by wget** [comment]
@tweetyx Modifying core libraries is breaking updates and is really the most disgusting way to proceed. Avoid this please. Especially as credentials are in plain text and not secured inside the database.

**Comment by tweetyx** [comment]
@wget yes,i know but if your are on a preprod and you not have ssl certificate this is a way for do test. But don t push that on production.

**Comment by aydinrzyv** [comment]
> Found this solution. Maybe it helps someone.
> 
> vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php
> 
> (around line 200) change function _connect.
> 
> **replace**
> 
> `// open connection $this->socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION); `
> 
> **with**
> 
> `$contextOptions = array( 'ssl' => array( 'verify_peer' => false, 'verify_peer_name' => false ) );`
> 
> ```
>     $context = stream_context_create($contextOptions);
> 
>     // open connection
>     $this->socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION, STREAM_CLIENT_CONNECT, $context);
> ```

Yes, this worked! 

I had a problem with emails not being sent, after replacing the code it worked like magic, thanks!

**Comment by vrajeshpatel4u** [comment]
Getting same error but file path changed : Warning: stream_socket_enable_crypto(): Peer certificate CN=`103-90-241-114.cprapid.com' did not match expected CN=`smtp.gmail.com' in public_html/vendor/laminas/laminas-mail/src/Protocol/Smtp.php on line 290

Magento ver. 2.4.2-p1
