### ISSUE TITLE
The attribute 'title' is required but missing

### ISSUE THREAD

**Issue by bangnguyen47** [mageplaza/magento-2-smtp#10]
Hello,

I am using magento version 2.2.
I am trying to install module (setup:upgrade) and throw exception.
> Element 'resource': The attribute 'title' is required but missing.

Note: the title-attribute is only required for new <resource>-nodes. So if your adding a new resource-node to an existing resource node (provided by another module) there is no need to add the title-attribute to those

Please update title source in https://github.com/mageplaza/magento-2-smtp/blob/master/etc/acl.xml#L34

**Comment by mariamghalleb** [comment]
how did you fix this?

**Comment by gixid192** [comment]
@mariamghalleb you should install Core module which can be found here https://github.com/mageplaza/module-core

**Comment by gixid192** [comment]
@mariamghalleb kindly enable it via command line. With normal installation, you can run: `bin/magento module:enable Mageplaza_Core`

**Comment by mariamghalleb** [comment]
@gixid192 Thanks!

now that the module is installed, enabled and functioning! 
My website became super slow! it went from 90/100 to 30/100 performance!  
I had to disable the module, any idea how to fix this performance issue caused by the module? 

Thank you

**Comment by gixid192** [comment]
We don't have any tickets nor issues report about the performance. Did your store back to normal speed when disabling our smtp extensions?

**Comment by lundco** [comment]
@gixid192 I too have performance issues with the module. After installing, i couldn't even load the webshop anymore. It just continued to load and load

**Comment by mariamghalleb** [comment]
@lundco check php bin/magento cache:status, and enable what's 0 !
