### ISSUE TITLE
Password emtpy on 2.2.5

### ISSUE THREAD

**Issue by mautz-et-tong** [mageplaza/magento-2-smtp#100]
Hi,

I get an empty password from namespace Mageplaza\Smtp\Helper\Data.

If I switch 
`function getPassword($storeId = null, $decrypt = true)`
to
`function getPassword($storeId = null, $decrypt = false)`
everything is fine.

Did I miss some undocumented requirements or is this a bug?

**Comment by datvm231** [comment]
Hi,

Please make sure you are using the latest version of Mageplaza Core and SMTP modules.
It has been tested on fresh installation of Magento 2.2.5  and password is encrypted/decrypted fine.
In case you already are, do you have any other sending mail module installed?

**Comment by mautz-et-tong** [comment]
We are on the latest versions.
Output of composer show:
mageplaza/module-core                         1.3.13
mageplaza/module-smtp                         1.2.2

There are no other mail sending modules installed.
But I can crosstest with other installed modules.

Will report later.

**Comment by mautz-et-tong** [comment]
OK:
The problem was that we - in some cases (e.g. test servers) - automatically distribute the SMTP configuration.
This password could not be decrypted in the Data Helper.
We just saved the password manually in the backend and now it works.
We have reproduced this behavior in several cases.
We are still investigating whether there is a problem with our sequence or the general deployment of variables that are encrypted.

I think you can close this issue, as it is not module related.
