### ISSUE TITLE
Test mail work but send to customer not working

### ISSUE THREAD

**Issue by nihachi** [mageplaza/magento-2-smtp#102]
I have this weird problem of all the smtps working with test emails but not the actual transactional emails. I have tried by executing cron from cli as well. Nothing seems to work.

**Comment by datvm231** [comment]
Hi,

What type of email can't be sent on your site? Is it order confirmation, contact, newsletter subscribe or all of them?

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know the detailed report.
