### ISSUE TITLE
Test mail says it is sent but it's never received

### ISSUE THREAD

**Issue by CarlPiper** [mageplaza/magento-2-smtp#104]
I have installed the module and copied the SMTP info from our working site. I press to send test mail and it takes about a minute (sounds like a timeout) then says the message has sent but i never get a message, I have tried sending to multiple addresses. I've played with as many settings as i can but still nothing. I cant seem to find any logs and Apache error logs are no help either.

**Comment by datvm231** [comment]
Hi,

Could you check if emails are delivered in spam box?
Also for further testing, please try using Telnet.
https://technet.microsoft.com/en-us/library/aa995718%28v=exchg.65%29.aspx
You may ask your host provider to help you with this.

**Comment by CarlPiper** [comment]
Hi,

It's definitely something wrong with our Magento server as we have tried multiple email providers. No emails in spam box either.

**Comment by CarlPiper** [comment]
No Help?

**Comment by datvm231** [comment]
For the record, your host provider will likely be able to help you troubleshoot the problem.
Please follow this instruction to check:
https://technet.microsoft.com/en-us/library/aa995718%28v=exchg.65%29.aspx

**Comment by CarlPiper** [comment]
Well what great support. The Magento server isn't talking to any SMTP servers, I've tried our own exchange and send grid now. The requests are not reaching them. So the error is the server your plugin is installed on. Also the error with your plugin is that there is no logs and it says sent successfully on a timeout. Sending me that link isn't helping anything is it.

**Comment by datvm231** [comment]
The problem is about your server, hence I advise you to check with your host provider.
Please check and you may get some result out of it.

**Comment by datvm231** [comment]
Do you mean that your site is hosted locally?

**Comment by CarlPiper** [comment]
Yes i am the admin

**Comment by datvm231** [comment]
Please use this tool to test:
https://github.com/PHPMailer/PHPMailer#a-simple-example
You only need to require PHPMailer and Exception classes, and can skip autoload.php if you don't install via composer.

**Comment by CarlPiper** [comment]
thank you i will try and get back to you

**Comment by CarlPiper** [comment]
Perfect thank you, after installing that plugin everything works
