### ISSUE TITLE
Base table or view not found: mageplaza_smtp_log

### ISSUE THREAD

**Issue by DePalmo** [mageplaza/magento-2-smtp#105]
Hello,

When I wanted to check out email log history to see if some of the emails were sent, I got back this error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'staging.mageplaza_smtp_log' doesn't exist, query was: SELECT COUNT(*) FROM `mageplaza_smtp_log` AS `main_table`

Magento v2.2.3
SMTP v1.2.5

I did check the database manually and the table truly does not exist. Do note that this issue was first noticed on v1.2.2, so then I updated it to latest version (through Composer) but issue is still present.

**Comment by datvm231** [comment]
Hello,

It looks like the install schema script wasn't executed, or it was skipped somehow when you run upgrade command.
You can try reinstalling the module again. Check table "setup_module" within your database and delete the record whose module is "Mageplaza_Smtp". Then run bin/magento setup:upgrade command, and the table should be created.

**Comment by DePalmo** [comment]
After I followed your instructions, table was created.

Thank you!
