### ISSUE TITLE
5.7.3 Authentication unsuccessful [DB6P18901CA0015.EURP189.PROD.OUTLOOK.COM]

### ISSUE THREAD

**Issue by FabiGjuzi** [mageplaza/magento-2-smtp#108]
When trying to send a test email, I always get this error message:
5.7.3 Authentication unsuccessful [DB6P18901CA0015.EURP189.PROD.OUTLOOK.COM]

**Comment by datvm231** [comment]
Hi,

The error means that you need to authenticate to use SMTP service from the SMTP server (Office 365).
Please contact them for further assistance.

Also you may refer to this guide:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_other-mso_o365b/smtpoffice365com-535-573-authentication/2e708a73-3340-4d24-b4e5-b97ff999dbae

**Comment by FabiGjuzi** [comment]
I am authenticating. In the username field, I have put outlook email and password field, the password that I use to sign in to Outlook.

**Comment by datvm231** [comment]
This is about using SMTP service of Office 365. It doesn't mean that you are able to login with your account only. Please check with their support to understand more of this matter. Also please check the above mentioned article.

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
