### ISSUE TITLE
test mail work fine . after saving config it gives error !!! 

### ISSUE THREAD

**Issue by mohanadly89** [mageplaza/magento-2-smtp#109]
![1](https://user-images.githubusercontent.com/37041833/46128587-9ea15680-c23c-11e8-9b4f-bacef86dd195.jpg)

![untitled](https://user-images.githubusercontent.com/37041833/46128593-a52fce00-c23c-11e8-9343-972946b5679c.jpg)

so i dont know whats causing the error .

test email works perfectly and email sent .but when i save config and try to send test email it give that error .

any solution regarding this issue

**Comment by datvm231** [comment]
Hi,

Your password might be saved incorrectly. Or password encryption might not be working well in old versions.
Make sure you are using the latest version of SMTP. If you already are, try turning off your browser auto filling functionality, or use incognito/private mode and login your Magento admin and save the SMTP configs again.

**Comment by mohanadly89** [comment]
i will check it ..
