### ISSUE TITLE
Adding a LICENSE file

### ISSUE THREAD

**Issue by quentinfarizon** [mageplaza/magento-2-smtp#11]
Could you add a license to this repository ? https://help.github.com/articles/licensing-a-repository/
In particular, Id like to know if I can fork it , modify it, and republish with attribution.

Thanks for this great extension!

**Comment by imsamthomas** [comment]
Hi @quentinfarizon ,

Thanks for your suggestion.
We have added the license at https://github.com/mageplaza/magento-2-smtp/blob/master/LICENSE.md

**Comment by quentinfarizon** [comment]
Thanks for your reactivity !
