### ISSUE TITLE
Magento 2.2.6 - Email not sending

### ISSUE THREAD

**Issue by anup4ranium** [mageplaza/magento-2-smtp#110]
Magento version: 2.2.6
Mageplaza magento2-smtp version: 1.2.6

Issue:

1. If email logging enabled, its throwing following error while sending email:
//////////////////////////
Fatal error: Uncaught Error: Call to a member function getRawContent() on string in /var/www/vhosts/shop/vendor/mageplaza/module-smtp/Model/Log.php:131 Stack trace: #0 /var/www/vhosts/shop/vendor/mageplaza/module-smtp/Mail/Transport.php(156): Mageplaza\Smtp\Model\Log->saveLog(Object(Ebizmarts\Mandrill\Model\Message), false) #1 /var/www/vhosts/shop/vendor/mageplaza/module-smtp/Mail/Transport.php(115): Mageplaza\Smtp\Mail\Transport->emailLog(Object(Ebizmarts\Mandrill\Model\Message), false) #2 /var/www/vhosts/shop/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\Smtp\Mail\Transport->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #3 /var/www/vhosts/shop/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}() #4 /var/www/vhosts/shop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object( in /var/www/vhosts/shop/vendor/mageplaza/module-smtp/Model/Log.php on line 131
/////////////////////////////////

2. If email logging disabled, its showing email sent successfully message for sending order email from admin, but not sending email.

Could you please review this issue on priority?

Thanks

**Comment by datvm231** [comment]
Hi,

This issue doesn't happen on fresh installation of Magento 2.2.6 with the latest version of SMTP.
I notice that you are using Ebizmarts_Mandrill extension. It seems to be overriding some email module class of Magento, Ebizmarts\Mandrill\Model\Message.
Please contact them to for further help on this matter.

**Comment by anup4ranium** [comment]
Hi @datvm231 ,

thanks for the reply.
I have Ebizmarts_Mandrill extension disabled in my app as it is not working for multistore setup and thats why in search other SMTP extensions :)

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.

**Comment by anup4ranium** [comment]
Hi @datvm231 , sorry for late reply here.
Removing ebizmarts extension resolved the issue. 
Thanks for your support 👍
