### ISSUE TITLE
There has been an error processing your request

### ISSUE THREAD

**Issue by dankeay91** [mageplaza/magento-2-smtp#112]
Hello after installing the SMPT extension it doent allow me in the configuration of the store getting the following error 

There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 818423160163

Uninstalled and reinstalled keep getting the same error am i doing anything wrong ?
Regards
Dan

**Comment by datvm231** [comment]
Hello Dan,

Make sure you have installed latest version of Mageplaza Core module. You can find it here:
https://github.com/mageplaza/module-core/

If you have already, could you show what the error log says? Go to your Magento root directory/var/report/818423160163 and let me know if the error includes any 3rd party extensions.

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
