### ISSUE TITLE
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by mls2700** [mageplaza/magento-2-smtp#113]
Hello,

This was just installed on Magento v.2.2.5. When trying to send a test message I am immediately receiving the following error:

"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

Tried reindexing, clearing cache, changing password with no luck. 

![image](https://user-images.githubusercontent.com/43759174/46305480-8d7b8100-c57f-11e8-8098-f4468ae7a1d0.png)

Thanks in advance,
JDG

**Comment by datvm231** [comment]
Hello,

Firstly, make sure you have installed the latest version of Mageplaza Core module.
https://github.com/mageplaza/module-core/

Then from your Magento root directory, check your /var/log/exception.log or /var/log/system.log if there are any new error log. Also check /var/report if there are new record (file).

**Comment by mls2700** [comment]
Latest Core Module worked, thank you!

JDG

**Comment by drinkingsouls** [comment]
I have the latest core version installed and I get this error.

**Comment by kamzata** [comment]
> I have the latest core version installed and I get this error.

Same error here. Magento 2.4.4 and the latest version of the Core and SMTP extension. No `var/log/exception.log` or errors in `var/log/system.log`.

**Comment by umarijaz04** [comment]
I have the same issue. I updated the core module and there no errors log in both file exception.log or system.log
