### ISSUE TITLE
technical problem with the server created

### ISSUE THREAD

**Issue by huzanf** [mageplaza/magento-2-smtp#116]
Hello,

I have setup everything. When I try to do a test email I get this error:

`A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.`

Kindly assist.

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.

**Comment by huzanf** [comment]
Hi @datvm231 
I am still facing an issue.

Please find below two links for the detailed report:
[system.log](https://www.dropbox.com/s/3jib4wrzhxt0pd1/system.log?dl=0)
[exception.log](https://www.dropbox.com/s/uw0vxvhnigvrkme/exception.log?dl=0)

Looking forward for your support.
