### ISSUE TITLE
Class 'Zend_Application_Resource_Mail' not found

### ISSUE THREAD

**Issue by thiagogalvao** [mageplaza/magento-2-smtp#118]
After install via composer on Magento 2.2.6 I got this erro when execute setup:di:compiler (after setup:upgrade):
Class 'Zend_Application_Resource_Mail' not found in /var/www/html/xxxxx/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31

Anyone has pass this ?

**Comment by datvm231** [comment]
Hi,

With a fresh instance of Magento 2.2.6 and SMTP latest version, 1.2.6, I was unable to reproduce this error. I got SMTP working well actually.
Could you check if class Zend_Application_Resource_Mail is declared? Its location should be here:
vendor/magento/zendframework1/library/Zend/Application/Resource/Mail.php

**Comment by thiagogalvao** [comment]
I don't have this directory! 
Don't ask me why this is not exists.

I installed the magento from github with composer.

Thanks to the answer.

**Comment by datvm231** [comment]
According to Magento official resources, they haven't supported installing Magento with their github. Please download packages from here:
https://magento.com/tech-resources/download

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.

**Comment by rdesimone** [comment]
Same problem here with a new Magento 2.3 installation:

`vendor/magento/zendframework1/library/Zend/Application` is missing after running `composer install`.

![screen shot 2018-11-29 at 08 10 45](https://user-images.githubusercontent.com/5596378/49202789-7e158a00-f3ae-11e8-87ff-111c9b758fee.png)

No problem for a new 2.2.6 installation:

![screen shot 2018-11-28 at 21 53 50](https://user-images.githubusercontent.com/5596378/49202818-9d141c00-f3ae-11e8-880f-63e5ae415920.png)

**Comment by robertkent** [comment]
@rdesimone +1 just found the same problem during code compilation on Magento 2.3 instance

**Comment by n2diving-dgx** [comment]
+1 Fresh install of 2.3... attempting to send an email does not succeed, error log contains...

 'Zend_Application_Resource_Mail' not found

**Comment by btekbtek** [comment]
Sam here after update to magento 2.3

**Comment by Arthas78** [comment]
Hi, We will continue this issue here 
https://github.com/mageplaza/magento-2-smtp/issues/127
