### ISSUE TITLE
Incorrect Menu location for SMTP

### ISSUE THREAD

**Issue by jeffb1a5** [mageplaza/magento-2-smtp#119]
Listing is not in the mageplazer admin section, is in the stores instead:
Changed in module-smtp>etc>adminhtml>menu.xml line 24
<add id="Mageplaza_Smtp::smtp" title="SMTP" module="Mageplaza_Smtp" sortOrder="45" resource="Mageplaza_Smtp::smtp" parent="Magento_Backend::stores"/>
to
<add id="Mageplaza_Smtp::smtp" title="SMTP" module="Mageplaza_Smtp" sortOrder="45" resource="Mageplaza_Smtp::smtp" parent="Mageplaza_Core::menu"/>

need to add the config as well, but I'm not sure of the action:
<add id="Mageplaza_Smtp::configuration" title="Configuration" module="Mageplaza_Smtp" sortOrder="10" parent="Mageplaza_Smtp::smtp" action="#########" resource="Mageplaza_Smtp::configuration"/>

**Comment by datvm231** [comment]
Hi,

We actually moved SMTP Log menu to stores section on purpose. The Mageplaza section shouldn't be added in the first place, and will be removed in the future. If all third party vendors were to do this, Magento admin panel would look aweful.

**Comment by jeffb1a5** [comment]
OK Thanks, you need to update the user guide then. 

Regards 

Jeff

On 2018-10-29 01:48, datvm231 wrote:

> Hi, 
> 
> We actually moved SMTP Log menu to stores section on purpose. The Mageplaza section shouldn't be added in the first place, and will be removed in the future. If all third party vendors were to do this, Magento admin panel would look aweful. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mageplaza/magento-2-smtp/issues/119#issuecomment-433764760
[2]

**Comment by datvm231** [comment]
Thank you. We will have it updated.
