### ISSUE TITLE
Doesn't work in Magento 2.2

### ISSUE THREAD

**Issue by jgamos** [mageplaza/magento-2-smtp#12]
i followed the installation guide, but when i try to send manually invoice the test costumer don't receive any emails.  I'm using both gmail as smtp account (server side) and test costumer

> Oct 20 15:07:22 ubuntu postfix/smtp[1725]: E082B10334F: to=<test@gmail.com>, relay=alt4.gmail-smtp-in.l.google.com[173.194.219.26]:25, delay=4155, delays=3726/0.61/428/0, dsn=4.4.2, status=deferred (lost connection with alt4.gmail-smtp-in.l.google.com[173.194.219.26] while receiving the initial server greeting)

**Comment by mustafatoraman** [comment]
Same issue here on Magento 2.2. Test email is successful , however not able to send email through magento. Tested on password reset and contact page.

**Comment by tsauerwein** [comment]
@haitv282 added support for Magento 2.2 in https://github.com/mageplaza/magento-2-smtp/commit/b821a33b21c999163bc50046a74ba45e21bb24a8

**Comment by mustafatoraman** [comment]
Thank you @haitv282  @tsauerwein  , tested and perfectly working in Magento 2.2.

**Comment by pinguleo** [comment]
Hi,
I have the same Issue  issue here on Magento 2.2 - Test email is successful -  But I don't receive any email :(

**Comment by imsamthomas** [comment]
@pinguleo 
We fixed it: https://github.com/mageplaza/magento-2-smtp/releases/tag/v1.0.5

**Comment by yasiraftab** [comment]
Extension 1.2.1 is not working with Magento 2.2. I can send test emails, password forget email, but new user creation email and order invoice sending is not working. I have downloaded the extension recently. SMTP logs showing email as "error" but cant find much details about it. Can anyone look into it?

**Comment by gixid192** [comment]
@yasiraftab you can send over the var/log folder, we will help you check it.

**Comment by yasiraftab** [comment]
@gixid192 any specific logs/files to upload?

**Comment by gixid192** [comment]
@yasiraftab You can zip the folder and send it all to me.

**Comment by site-me** [comment]
I am having a timeout when trying to use it with g-suit - 
`main.CRITICAL: Connection timed out {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Connection timed out`
should this plugin work with the Magento ver. 2.2.5?

**Comment by gixid192** [comment]
@site-me for 2.2.4 and above, you can check this issue: https://github.com/mageplaza/magento-2-smtp/issues/80
