### ISSUE TITLE
(Zend_Json_Exception): Decoding failed: Syntax error

### ISSUE THREAD

**Issue by IslamovRhino** [mageplaza/magento-2-smtp#122]
Extension's version is 1.2.6. Magento version is 2.1.10. (soon upgrading to 2.2.6)
This error happens if trying to access configuration page of Smtp extension. Checked - extension is enabled in admin - advanced and by "php bin/magento module:status" command.

1 exception(s):
Exception #0 (Zend_Json_Exception): Decoding failed: Syntax error

Exception #0 (Zend_Json_Exception): Decoding failed: Syntax error
#0 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Module/PackageInfo.php(85): Zend_Json::decode('\n\n    "name": "...')
#1 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Module/PackageInfo.php(262): Magento\Framework\Module\PackageInfo->load()
#2 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/mageplaza/module-core/Block/Adminhtml/System/Config/Form/Field/Version.php(67): Magento\Framework\Module\PackageInfo->getVersion('Mageplaza_Smtp')
#3 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-config/Block/System/Config/Form/Field.php(82): Mageplaza\Core\Block\Adminhtml\System\Config\Form\Field\Version->_getElementHtml(Object(Magento\Framework\Data\Form\Element\Label))
#4 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-config/Block/System/Config/Form/Field.php(56): Magento\Config\Block\System\Config\Form\Field->_renderValue(Object(Magento\Framework\Data\Form\Element\Label))
#5 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(453): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Label))
#6 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(467): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#7 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(81): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#8 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(62): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#9 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(453): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#10 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(467): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#11 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form.php(322): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#12 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/Data/Form.php(337): Magento\Framework\Data\Form->toHtml()
#13 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-backend/Block/Widget/Form.php(98): Magento\Framework\Data\Form->getHtml()
#14 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#15 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/ubuntu/de...')
#16 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/home/ubuntu/de...', Array)
#17 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/ubuntu/de...')
#18 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#19 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#20 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#21 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#22 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#23 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#24 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#25 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#26 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#27 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/ubuntu/de...')
#28 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/ubuntu/de...', Array)
#29 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/ubuntu/de...')
#30 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#31 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#32 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#33 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#34 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#35 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#36 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#37 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#38 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#39 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#40 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#41 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#42 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#43 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#44 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#45 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#46 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#47 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#48 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#49 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#50 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#51 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#52 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#53 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#54 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#55 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#56 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#57 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#58 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#59 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#60 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#61 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#62 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#63 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#64 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#65 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#66 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#67 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#68 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#69 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#70 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#71 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#72 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#73 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#74 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#75 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#76 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#77 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#78 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#79 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#80 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /home/ubuntu/deploy/bariatric-fusion/shared/src/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#82 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#83 /home/ubuntu/deploy/bariatric-fusion/releases/20181025140016/src/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#84 /home/ubuntu/deploy/bariatric-fusion/shared/src/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#85 {main}

**Comment by datvm231** [comment]
Hi,

It appears that the error is similiar to this one https://github.com/mageplaza/magento-2-smtp/issues/121
You can follow the instruction there and find which composer.json file contains incorrect syntax:
`{\n\n "name"...}`

You're welcome to reach our technical support team at https://mageplaza.freshdesk.com/ and provide your SSH and admin credentails so we can have a look at your site.

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
