### ISSUE TITLE
Notice: Undefined index: id in Iterator.php on line 63

### ISSUE THREAD

**Issue by bartoll** [mageplaza/magento-2-smtp#125]
Magento 2.2.6

When I go to Stores -> Configuration in admin panel, I get error as below:

`Notice: Undefined index: id in vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63`

After disabling this module, everything start working.

**Comment by bartoll** [comment]
This problem was because of Mageplaza_Core module was disabled.
Now everything works well.

**Comment by Eddcapone** [comment]
Look [here](https://magento.stackexchange.com/a/281929/66769), it might come from another module.
