### ISSUE TITLE
SMTP Email Logs view crashes when Sorting by "To"

### ISSUE THREAD

**Issue by allozaur** [mageplaza/magento-2-smtp#126]
![zrzut ekranu 2018-11-28 o 12 29 36](https://user-images.githubusercontent.com/37627284/49150148-4fdf6e00-f30c-11e8-99de-d07af542a4ee.jpg)

Sorting SMTP Email Logs by "to" column causes the SQL to be:

```SELECT `main_table`.* FROM `mageplaza_smtp_log` AS `main_table` ORDER BY to ASC
 LIMIT 200```

while it should be using ticks:

```SELECT `main_table`.* FROM `mageplaza_smtp_log` AS `main_table` ORDER BY `to` ASC
 LIMIT 200```

Because `to` is a special mysql keyword and it's treated as a badly created SQL query., please fix this within the module (by either adding ticks or renaming the column to `email_to`

**Comment by Arthas78** [comment]
It looks like you are using the old version. This issue has been fixed in version 1.2.6. 
Please upgrade that version

**Comment by allozaur** [comment]
You are right, this instance has the **1.4** version installed
