### ISSUE TITLE
Shipping mail confirmation works but not order confirmation

### ISSUE THREAD

**Issue by captainarmchair** [mageplaza/magento-2-smtp#128]
Hi 

Running 2.2.6 and test mails and shipping mails works fine and looks good in the logs but new orders and the confirmation mail are unsuccessful. I have tried to resend via the SMTP log section but that never works. Any log files that I can check why this happens. 

Thanks.

**Comment by Arthas78** [comment]
Actually, I've known this bug but it only appears in versions 2.2.3 and 2.2.4.
Please log in and check if there is no information in the "from" column, you can refer to the solution here
https://github.com/mageplaza/magento-2-smtp/issues/80

**Comment by captainarmchair** [comment]
Sorry I am running 2.2.5, where do I check in and confirm the from column ? 

Cheers

**Comment by Arthas78** [comment]
Hi,
This is a bug of Magento( http://prntscr.com/lqtrne )
you can refer here(#80 ) for the known solution

**Comment by captainarmchair** [comment]
Installed Sashas email bug, but it made no difference.

**Comment by Arthas78** [comment]
Your problem can be in the amazon payment module
You can see here(http://prntscr.com/lrbf2b )

**Comment by captainarmchair** [comment]
> Your problem can be in the amazon payment module
> You can see here(http://prntscr.com/lrbf2b )

Already disabled, makes no difference.

**Comment by Arthas78** [comment]
Try turning off the SMTP module and test again with dotmailer (http://prntscr.com/lrsbzq). If the new orders and the confirmation mail don't send then it may not be the fault of SMTP module

**Comment by captainarmchair** [comment]
Order confirmation mails was working before I installed the SMTP extension.

**Comment by captainarmchair** [comment]
OK, is there a different extension that actually works ? Please any recommendations would be great since this issue is driving me insane :-)

**Comment by Arthas78** [comment]
I'm not sure why this error appear. Kindly try an alternative approach:
Magento 2.2.5 shipped with Dotmailer Transaction Emails https://www.screencast.com/t/wSLA3bZsAZkZ
You can use it right away without registering an account.
Please check if it works for you.

**Comment by Arthas78** [comment]
I will close this issue because don't see the response from you
