### ISSUE TITLE
Installation Instructions Are Not Complete

### ISSUE THREAD

**Issue by uandiweb** [mageplaza/magento-2-smtp#130]
You must run first "composer require mageplaza/module-core" before you run "composer require mageplaza/module-smtp". Otherwise, you are going to have issues. I'm not sure why this important step is missing.

**Comment by Arthas78** [comment]
In my opinion, just run composer require that all dependencies will automatically install under. In this case, when run the "composer require mageplaza/module-smtp" command will automatically install the core module. This is how the composer manages the package. Can you tell me the problem you are having?

**Comment by Arthas78** [comment]
I will close this issue because don't see the response from you
