### ISSUE TITLE
SMTP module issue with Magento ver. 2.2.4

### ISSUE THREAD

**Issue by Vipin1988** [mageplaza/magento-2-smtp#131]
Hello Team,

I have install your module in my website but this is not working and not activate in my website if i goes configuration then showing error page so please fix it asap.

Error : 

There has been an error processing your request
Notice: Undefined index: id in /var/www/html/skipper/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
Error log record number: 907142481388

**Comment by Arthas78** [comment]
I will close this issue because don't see the response from you

**Comment by Vipin1988** [comment]
i have not got any solution for it yet.

**Comment by Arthas78** [comment]
First, have you installed our Core module yet? if not install, you can down and install it here
https://github.com/mageplaza/module-core
If the problem still occurs, try disabling SMTP modules and check for the error. If the system doesn't throw any errors, then that means a system.xml file in SMTP modules is causing the issue. If not, maybe that's not the problem from SMTP module.

**Comment by Arthas78** [comment]
Since I don't see any feedback, I will close this issue

**Comment by dngsa** [comment]
If the core is needed for the other modules to be running why don't you list it as a dependency ????????
