### ISSUE TITLE
invalid mail address on activate extension with magento 2.2.7

### ISSUE THREAD

**Issue by severus-sn4pe** [mageplaza/magento-2-smtp#132]
Fresh installation of magento 2.2.7 with composer.
Installed mageplaza/magento-2-smtp with composer.

After install, I go to `Stores > Settings > Configuration > Mageplaza Extensions > SMTP`.
I enter an email address and name in `Module Information` and press `Activate now`.

This leads to:
> Email address is invalid.

I have Version 1.2.6 of magento-2-smtp.
I have sucessfully used the extension on magento 2.2.6 without problems. With **2.2.7** I can't activate and use it.

Any ideas on what to do?

**Comment by Arthas78** [comment]
As you describe, in magento 2.2.6 you used that email to activate, so you will not be able to use it, please try another authentication email

**Comment by severus-sn4pe** [comment]
Thanks for clarification. 
The error message is a bit misleading, so I thought the error was somewhere else.
/close
