### ISSUE TITLE
Fatal error:  Class 'Zend\Mail\Header\AbstractAddressList' not found

### ISSUE THREAD

**Issue by AnthonyBonnier** [mageplaza/magento-2-smtp#134]
Dear magento-2-smtp team,

Since today, the version 2.1.8 triggers this error in our project :
`09:35:23 Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 56.0 MiBPHP Fatal error:  Class 'Zend\Mail\Header\AbstractAddressList' not found in .../vendor/mageplaza/module-smtp/Mail/Rse/Header/ReturnPath.php on line 28`

Do you have any idea why this is happening, even though yestereday everything was ok ?

Thank you in advance for your help.

Best regards

**Comment by Arthas78** [comment]
Thank you for your information. Are you using Magento version under 2.3?
If it's right, you should SMTP version 1.2.6 (http://prntscr.com/m7uhzq). The version 1.2.8 used for Magento version 2.3 but it seems to have errors when running the command s: d: c for the following versions. We will quickly fix it. Thank you for providing the information again

**Comment by Arthas78** [comment]
We have just updated version 1.2.9. It runs on Magento versions 2.xx
Please kindly understand!

**Comment by ssmadsen** [comment]
@Arthas78 
So the extention is finally 100% compatitble with M.2.3?

**Comment by ssmadsen** [comment]
@Arthas78 Happy days. Thanks.

**Comment by Arthas78** [comment]
Since there's no problem, I'll close the issue here

**Comment by AnthonyBonnier** [comment]
Sorry for the late reply. Indeed, we're using the version 2.1.12 of Magento. We plan to upgrade to the latest 2.3.x soon. For now, we've downgrade the extension version to make it works, as you've suggested. Thank you for your help.
