### ISSUE TITLE
Magento 2.3 Cyrillic subject problems

### ISSUE THREAD

**Issue by McAlex220** [mageplaza/magento-2-smtp#135]
My hosting antispam blocks email with cyrillic subject: "550 Subject contains invalid characters." Even from default contact form. Contact form has Cyrillic(russian) subject, from Mageplaza russian pack.

The problem was with email subject encoding. Using latin sybmols - was ok, but cyrillic - failed. I've changed mail server - and now it's ok with cyrillic. But it's really strange, because my host mail server is working fine with cyrillic email subjects at Magento 2.2 with your earlier version extension...

Technical support of my hosting mail server says:
"When a message is rejected with "550 Subject contains invalid characters" the email subject will have non-ASCII characters, which is not allowed by the RFC. To include non-ASCII characters in subjects, the subject is required to be properly encoded, for example with UTF-8. Any normal mail client will automatically handle that for you, so it's likely a bug in a custom written script that generated the invalid subject."

Does it says something to you?

**Comment by Arthas78** [comment]
You can try adding this code and test again
https://prnt.sc/m9jb0j

**Comment by Arthas78** [comment]
Since I have not received any feedback from you, I will close the ticket here

**Comment by McAlex220** [comment]
Sorry for that. It's working perfect. Thank you. Please add this to release.
