### ISSUE TITLE
Strange not working email address

### ISSUE THREAD

**Issue by chequille** [mageplaza/magento-2-smtp#136]
Hi Guys,
using Magento 2.3.0 and the latest SMTP version from here.
So far, it seems that everything is working.

But, I have an user email address, which is not getting any sales emails or password reset etc.
If I use this email address for the Test Mail function in the SMPT configuration page, I get the email.
The log says that the mail was sent.
The email is not in the spam of the mailbox.

On Magento 2.2.7 everything works with this address.

So, my question: Does somebody have an idea why this address not working anymore?
Where are the main differences maybe regarding headers, encoding etc. of the mail message?

Looking forward to hearing from you.
Best regards,
Chequille

**Comment by chequille** [comment]
Found the problem:
It is because the subject of the email containing german umlaut characters like "ä". It looks like the mailserver of the address is not accepting this and therfore not receiving the email.

As well the wrong encoding of chracters is as well discussed in Magento2. Of course it takes pretty long since the believe it and fix it.

BR
Chequille

**Comment by Arthas78** [comment]
You can add the following code to fix your charset headers error
https://prnt.sc/m9owv1
On to be most sure, you should check if the email is in the blacklist.
Also, you should try turning off our SMTP module and try it on dot-mailler. If the mail still can't be sent, you should check with the mail server and the host provider

**Comment by Arthas78** [comment]
The message header is contained in the header of the message. The use of "ă" cannot send mail because the $message charset default is ASCII it only encodes 128 characters. So you have to convert it to "utf8" encoding. Someone asked about this issue and they added the code, it succeeded. Sorry, I sent a photo to you. This is the extra code
https://prnt.sc/m9jb0j

**Comment by Arthas78** [comment]
I am very happy to hear your problem has been fixed
I'm also not sure about Gmail mail server but it may have set the default (UTF-8) encoding.
You can check that with your mail server.

**Comment by chequille** [comment]
I do really wonder about this, because when I use Outlook or any other Mail program, I do not have this problems. I always receive the mails with the German Umlaut characters as well in the subject.
Therefore, I believe it does not have to do with the mail server.

I got now emails from Mailer-Daemon from the mail server the messages are sent from. THe errors says:
    host spamschutz.xxxx.de.de [xxx.xxx.xxx.xxx]
    SMTP error from remote mail server after end of data:
    550 Subject contains invalid characters.

I am wondering, why this worked (and I amsure it did) with Magento 2.2.7 and as well with your extension?

But, as long as I have a solution with your hint, I can live with it.

Happy coding
Chequille

**Comment by Arthas78** [comment]
Because it is on magneto versions before the encoding for the headers message has been set to "base64" by default, it is set by default to ASC II on Magento 2.3. Because of this, new problems appear. We are very thankful for your error message, I will add it to complete the SMTP version
Thank you again!

**Comment by Arthas78** [comment]
Since I have not received any feedback from you, I will close the ticket here
