### ISSUE TITLE
MAGENTO 2.3

### ISSUE THREAD

**Issue by ZEFSWISS** [mageplaza/magento-2-smtp#137]
Hi,
the extension doesn't work on my side with M2 2.3. I have tested with several different SMTP accounts...nothing happens after pressing the TEST NOW button.

**Comment by Arthas78** [comment]
What version of SMTP are you using? we have released SMTP  version 1.2.9 to be compatible with Magento 2.3. Please download and install it here
https://github.com/mageplaza/magento-2-smtp
Check your core module and upgrade it if necessary

**Comment by ZEFSWISS** [comment]
Yes, I installed the last version via composer

 

Cordiales salutations / Mit freundlichen Grüßen / Best Regards

 

Alain Demouchy

 

De : Arthas78 <notifications@github.com> 
Envoyé : jeudi 24 janvier 2019 09:45
À : mageplaza/magento-2-smtp <magento-2-smtp@noreply.github.com>
Cc : ZEFSWISS <alain.demouchy@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [mageplaza/magento-2-smtp] MAGENTO 2.3 (#137)

 

What version of SMTP are you using? we have released SMTP version 1.2.9 to be compatible with Magento 2.3. Please download and install it here
https://github.com/mageplaza/magento-2-smtp
Check your core module and upgrade it if necessary

**Comment by Arthas78** [comment]
Try replacing the code here(http://prntscr.com/mbg5zl). When you send to test the email, please turn on the browser's inspect and check the error as follows http://prntscr.com/mbg5et

**Comment by ZEFSWISS** [comment]
Where ?

In app/code/mageplaza/smtp?

Because this folder doesn’t exist on my end!

 

Cordiales salutations / Mit freundlichen Grüßen / Best Regards

 

Alain Demouchy

 

De : Arthas78 <notifications@github.com> 
Envoyé : jeudi 24 janvier 2019 10:20
À : mageplaza/magento-2-smtp <magento-2-smtp@noreply.github.com>
Cc : ZEFSWISS <alain.demouchy@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [mageplaza/magento-2-smtp] MAGENTO 2.3 (#137)

 

Try replacing the code here(http://prntscr.com/mbg5zl). When you send to test the email, please turn on the browser's inspect and check the error as follows http://prntscr.com/mbg5et

**Comment by Arthas78** [comment]
If you installed your Smtp by the composer, please check your vendor/mageplaza/module_smtp

**Comment by oliverf72** [comment]
Testmail works on my side with M2.3 but my order confirmation has not been sent..
Getting this error in the log:
Notice: iconv_mime_decode(): Detected an illegal character in input string in /home/xxx/public_html/vendor/mageplaza/module-smtp/Ui/Component/Listing/Column/Actions.php on line 71

**Comment by Arthas78** [comment]
@oliverf72 You can create a ticket and we will check the problem for you on Monday because it is now our weekend break
https://www.mageplaza.com/contact.html

**Comment by Arthas78** [comment]
Since I have not received any feedback from you, I will close the ticket here
