### ISSUE TITLE
Sender email name is missing when I received mail inside my mail box!

### ISSUE THREAD

**Issue by iindranil** [mageplaza/magento-2-smtp#138]
Hi Guys,

I am using Magento 2.3.0 and the latest SMTP version 1.2.9.

SMTP email is working and receiving email inside the inbox but Sender email name is missing. This is happening for all emails. Please see the screenshot for more detail.

![image](https://user-images.githubusercontent.com/39942912/51895832-1b9e3180-23d1-11e9-8ede-d340a313b0df.png)

Thanks in advance!

**Comment by Arthas78** [comment]
Since I have not received any feedback from you, I will close the ticket here
