### ISSUE TITLE
iconv_mime_decode problem

### ISSUE THREAD

**Issue by TonySma** [mageplaza/magento-2-smtp#139]
Hello, 
We get a notice when subject string contain accent on smtp module grid
Here how to reproduce: 

`
php > echo iconv_mime_decode('Réinitialiser votre mot de passe Main Website Store', 2, 'UTF-8');
PHP Notice:  iconv_mime_decode(): Detected an illegal character in input string in php shell code on line 1
php > echo iconv_mime_decode('Reinitialiser votre mot de passe Main Website Store', 2, 'UTF-8');
Reinitialiser votre mot de passe Main Website Store
`

Notice: iconv_mime_decode(): Detected an illegal character in input string in vendor/mageplaza/module-smtp/Ui/Component/Listing/Column/Actions.php on line 71

Thank for help !
Tony

**Comment by TonySma** [comment]
https://github.com/mageplaza/magento-2-smtp/pull/140

**Comment by Arthas78** [comment]
Because the issue has been resolved, we will close this issue
