### ISSUE TITLE
Gift card email is not sent

### ISSUE THREAD

**Issue by devendrant** [mageplaza/magento-2-smtp#141]
I have configured mageplaza SMTP extension to send emails.
When someone purchases a gift card on magento2 enterprise edition, order email is delivered but gift card email is not delivered to recipient.

**Comment by Arthas78** [comment]
Please try turning off the SMTP module and using dot-mailer to check and notify us of the result.
One more thing, are you using the giftcard of which party?

**Comment by Arthas78** [comment]
Since I didn't receive a response from you, I will close the issue here

**Comment by dcwipm** [comment]
i am facing this issue any update on this?

**Comment by dcwipm** [comment]
any update on this issue?
