### ISSUE TITLE
not getting email from custom module

### ISSUE THREAD

**Issue by purvi99** [mageplaza/magento-2-smtp#142]
Hello,

i got error like 5.7.1 Client does not have permissions to send as this sender when email going from custom module.i have used outlook.

**Comment by Arthas78** [comment]
You should authenticate users and passwords. magento 2 has dot-mailler(http://prntscr.com/mjetuu)(1 tool that you can test your configuration). Please disable SMTP and test it on dot-mailler and let me know the result. If you still do not receive the email, please check your configuration

**Comment by purvi99** [comment]
can you please send link where i can test?

**Comment by purvi99** [comment]
Hello Athas,

Thanks for your reply.

But how can i use Dotmailer in magnento2?

**Comment by Arthas78** [comment]
Dot-Mailler is also a Magento tool. It has nearly the same functionality as the Smtp module. If you use the Smtp module and still send mail with normal functions like forgetting email, contact email, you should check your custom module, you can refer to the test.php file's writing method.

**Comment by purvi99** [comment]
Hello,

Thanks.but how can I configure api keys in dotmailer?

**Comment by Arthas78** [comment]
You don't need to config dot mailler. Is the SMTP module still active with basic functions?  like order email, contact email,.. Please check your custom module. You can refer to file controller/Adminhtml/test.php for more details

**Comment by purvi99** [comment]
yes,its active with basic functionalities.in smtp module,can we send two emails in same time when order palaced?

**Comment by Arthas78** [comment]
You are misunderstanding my idea. I mean, do you have a problem with smtp module? If you are using good module smtp, the problem can be in your custom module, you can refer to the test.php file for more details.

**Comment by purvi99** [comment]
okay.Got your Point.

**Comment by Arthas78** [comment]
normally you can only use 1 email order for customers, If your module wants to send 2 email order, you can refer to the bcc function in Magento 2(http://prntscr.com/mjgjwm).

**Comment by purvi99** [comment]
yes,i have used Magento2 EE.In magneto2 EE,giftcard module is avaiable.When customer placed order with giftcard product that time customer and will get email regrading orders but gift card recipient email does not get any emails regrading giftcard balance but in smtp logs,its showing success email status.

**Comment by Arthas78** [comment]
Which module are you using a gift card? Let us know, I will test it on my site

**Comment by purvi99** [comment]
hello,

i am using magento default module of gift card.its already available  in vendor folder .

**Comment by Arthas78** [comment]
Please create a new ticket at the following link.
https://www.mageplaza.com/contact.html
Please provide the information below
- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details.
Then I will check the problem for you

**Comment by purvi99** [comment]
hello,

i have send query.

**Comment by Arthas78** [comment]
Since there are no questions left, we will close this issue
