### ISSUE TITLE
Test email fails with 500 Error and PHP Notice

### ISSUE THREAD

**Issue by joshwyrick** [mageplaza/magento-2-smtp#143]
Smtp v1.2.9
Core v1.4.1
Magento 2 Open Source 2.3.0
Weltpixel Pearl theme

Host: smtp.mailgun.org
Port: 587
Protocol: TLS
Authentication: LOGIN
[Mailgun username]
[Mailgun Password]
...
Developer Mode: No

Attempting to send a test message from the configuration page fails with a 500 error, and throws the following PHP notice:

`Exception #0 (Exception): Notice: Undefined index: to in /srv/public_html/vendor/mageplaza/module-smtp/Controller/Adminhtml/Smtp/Test.php on line 108`

https://github.com/mageplaza/magento-2-smtp/blob/master/Controller/Adminhtml/Smtp/Test.php#L108

**Comment by Arthas78** [comment]
Please turn on chorme's F12, go to the network to check the ajax processing stream(http://prntscr.com/mls0hk) when you click the test now button. If the status returns 500(http://prntscr.com/mls2wl), you can replace the following code(http://prntscr.com/mls3w6), clear the cache and check again

**Comment by joshwyrick** [comment]
Thanks for the help. I have determined that the actual problem is caused by a module included with the pro version of WeltPixel's Pearl theme - **WeltPixel_EnhancedEmail** . SMTP now works after disabling the WeltPixel_EnhancedEmail module. This issue can be closed.
