### ISSUE TITLE
Send email error in magento v230

### ISSUE THREAD

**Issue by tinh-ngo-niteco** [mageplaza/magento-2-smtp#144]
# Step
- Copy folder magaplaza smtp mail to /app/code
- Run command line: php bin/magento setup:upgrade
- Config magalaza smtp mail success
- Test email

# Error
- Message error: 
Error
Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for 
- Image
![screenshot_2](https://user-images.githubusercontent.com/38058535/53630020-acbb2f00-3c41-11e9-91a8-0898cb153970.png)

Thanks!!

**Comment by Arthas78** [comment]
Please check your config information (especially the authentication field)(http://prntscr.com/mrr1va).

**Comment by tinh-ngo-niteco** [comment]
Thank you very much!! 💃

**Comment by Arthas78** [comment]
I will close this issue here
