### ISSUE TITLE
Email's subject is not showing

### ISSUE THREAD

**Issue by sadon** [mageplaza/magento-2-smtp#145]
After Upgrading Magento to 2.3.0:

1. There is no email  topics 

2. Sender ID changed to simple emails, instead of: <text> email-address@example.com

http://joxi.ru/vAWN910t1vlBv2

**Comment by Arthas78** [comment]
First, regarding the subject problem, it looks like your site is suffering from decoding the subject.
You can replace the code(http://prntscr.com/mejd5p)
`$subject = $item['subject'];
                if(stripos($subject, "=?utf-8?b?") !== false) {
                    $output = str_ireplace("=?utf-8?B?", "", $subject);
                    $output = str_replace("==?=", "", $output);
                    $output = base64_decode($output);
                }else{
                    $output = $subject;
                }
                $item['subject'] = $output;`
As for the display of sender, we feel that it is not necessary to display the name so we haven't processed it, we will note and process it in the following version of SMTP

**Comment by sadon** [comment]
I confirm 1) fix. 
Now subjects displayed correctly.
Are you planning to add this feature to new release?

**Comment by Arthas78** [comment]
We see that there are only a few sites where the email subject is affected. However, I will note this issue and inform our manager

**Comment by Arthas78** [comment]
I will close the issue here.
Thank you very much!
