### ISSUE TITLE
STARTTLS Support for Office 365

### ISSUE THREAD

**Issue by crossgate9** [mageplaza/magento-2-smtp#146]
Dear, 

I am using a Hotmail mailbox in your module. 
When enabling the permission in my mailbox, I got the following settings from Office 365 interface: 
Server name: smtp.office365.com
Port: 587
Encryption method: STARTTLS

From the backend, we can only choose SSL and TLS in the dropdown. 
And if we force to send over TLS, we got the following message: 
5.7.3 Authentication unsuccessful 
[AM6P195CA0081.EURP195.PROD.OUTLOOK.COM]

I wonder whether there is a workaround with your module? 

Thanks in advance.

**Comment by Arthas78** [comment]
As I noticed, this is a problem with your configuration information. Please check with the host provider. 
In Magento 2, you can use dot-mailler to check configuration information(http://prntscr.com/mx5jra). 
I also found some documents for your problem
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_other-mso_o365b/smtpoffice365com-535-573-authentication/2e708a73-3340-4d24-b4e5-b97ff999dbae

**Comment by Arthas78** [comment]
Because you didn't respond in 7 days, I will close the issue here
