### ISSUE TITLE
Not working with customized email templates

### ISSUE THREAD

**Issue by nguyendeicide** [mageplaza/magento-2-smtp#147]
**Magento version #: 2.3 PHP 7.2
Edition (EE, CE, OS, etc): CE
Expected behavior: Emails send out with customized email templates
Actual behavior: Right now, my email templates have been updated and selected, but emails sent out without my modification.
Steps to reproduce: Customized email order and select it in sale email - admin. Proceed an order and check your mailbox to see if it changes or not.**

**Comment by Arthas78** [comment]
First, the SMTP module has only one purpose to send an email. And template setting is the default flow of Magento, SMTP module doesn't handle that. I tried changing the order template on Magento 2.3 and found it working normally(http://prntscr.com/my2v3f)(http://prntscr.com/my2vfa)(http://prntscr.com/my2v7s). You should clear the cache and check the page again

**Comment by nguyendeicide** [comment]
Thanks @Arthas78 : i followed your instruction and it loaded the email template, but css not loading. It's template styles css: http://prntscr.com/my3fvr

**Comment by nguyendeicide** [comment]
By copy template styles css to yourtheme/web/css/email.css
I get it works, thanks for your help, (y)
