### ISSUE TITLE
Invalid header value exception when using non ASCII-characters in From name

### ISSUE THREAD

**Issue by BozzaDaniel** [mageplaza/magento-2-smtp#150]
When using a from name with accents (such as, å, ä, ö è or é), Zend-Mail will fail with an invalid header value exception. 

The stack trace points to the line: HeaderValue::assertValid($email); in AbstractAddressList.php. Remoing the accents from the From solves the issue. 

As you should be able to have a from name with accents I checked to see if zend-mail supported it, and it does. In order for it to work, you have change the encoding of the message. Setting it to utf-8 solves the issue and the mail is delivered without any exceptions.

I added:

            $message->setEncoding('utf-8');

Between the lines:

            $message = $this->resourceMail->processMessage($message, $this->_storeId);

            $transport = $this->resourceMail->getTransport($this->_storeId);

In Transport.php (should be lines 109-111).

**Comment by Arthas78** [comment]
You can add the code in Transport.php(https://prnt.sc/n43esa)
Thank you very much!

**Comment by Arthas78** [comment]
Since it was over 7 days, I will close this issue here
Thank you very much!
