### ISSUE TITLE
Integrate Mailgun SMTP cause error

### ISSUE THREAD

**Issue by malinwallenius** [mageplaza/magento-2-smtp#151]
Magento 2.3.0 , php7.2 

When using Mailgun ,  I cannot send email.   Log shows: 

![image](https://user-images.githubusercontent.com/46682097/55153938-406f1500-5186-11e9-8cb6-d815114b8bcd.png)

**Comment by Arthas78** [comment]
Please check your configuration information (especially the password field). Make sure you've entered the correct password and saved it, then flush the cache and check the site.

**Comment by Arthas78** [comment]
Since it was over 7 days, I will close this issue here
Thank you very much!

**Comment by Arthas78** [comment]
I close the issue here.
Thank you very much!
