### ISSUE TITLE
Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1

### ISSUE THREAD

**Issue by youphp** [mageplaza/magento-2-smtp#152]
# Preconditions
Magento 2.2.6
PHP 7.1.18
Amazon ses is not in sandbox mode
# Steps to reproduce
Configuring smtp with Amazon ses, Reply to customer ticket
# Expected result
Send a email to customer using customer support email address support@domain.com
# Actual result
Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: yoyo <yoyo@domain.com>, yoyo@domain.com
Note that this yoyo@domain.com is the administrator's email address, not the customer support email address support@domain.com.
When I changed the smtp configuration to google mailbox, it can send mail normally.

**Comment by Arthas78** [comment]
If you have good use with SMTP Gmail information, I believe the problem doesn't come from the SMTP module. In my opinion, you should check your configuration information with the host provider to see if it has been authenticated. Also, one way to check configuration information is to use dot-mailler available from magento. Please disable the SMTP module, then configure dot-mailler(http://prntscr.com/n5o4a8), finally go to the frontend and check with the basic functions of Magento like the subscribe, forgot email

**Comment by youphp** [comment]
I think the problem come from the SMTP module. I tested other emails and basically they can send them normally. Only the ticket reply email and email to a friend will prompt Message rejected: Email address is not verified. The following identities failed the check in region error.

**Comment by youphp** [comment]
And I tested switching from amazon ses to my personal Google mailbox, this ticket reply and email to a friend can send it normally.

**Comment by Arthas78** [comment]
Have you tried the dot-mailler with your amazon ses configuration information? SMTP module is only responsible for using the information you have configured and emailed. If the error stems from the SMTP modue, when you use configuration information from gmail, they will not be able to send mail. Please check with dot-mailler and let me know the result.

**Comment by youphp** [comment]
Sorry, I don't understand what dot-mailler is. This error may only appear in amazon ses, not the entire SMTP module.

**Comment by Arthas78** [comment]
The dot-mailler is the tool of Magento. It functions similarly to the SMTP module. Please turn off the SMTP module and try again on dot-mailler(https://prnt.sc/n5o4a8), If your problem still appears, you should check the host provider for configuration information. It seems that you still do not understand the main function of the SMTP module is to get all the information (host, user, pass, ..) to perform the mailing. So if the problem only occurs when you use the amazon ses information, you should check with your host provider

**Comment by youphp** [comment]
I have tried transactional emails, But it seems to only support basic function mail. Subscribe and forget password emails, etc. This amazon ses authentication is definitely correct.

**Comment by Arthas78** [comment]
Yes, the SMTP module has written to the dot-mailler thread so if dot-mailler can't send your email, the SMTP module can't send. Did you try with cases that can't send mail?

**Comment by youphp** [comment]
This SMTP module can send all emails using Google Mail. Why can't I send it when I use amazon ses?

**Comment by Arthas78** [comment]
The problem as you stated above(http://prntscr.com/n5qdwm). It may be because the host provider did not authenticate that email address. If you configured the dot-mailler and disabled the SMTP module, but the problem still occurs, I think the problem does not come from the SMTP module.

**Comment by youphp** [comment]
This yoyo@domain.com mailbox is the administrator personal mailbox, not the store customer support mailbox. It uses the administrator's mailbox as the sender. This issue is not related to authentication. The error is simply because the wrong mailbox is used as the sender.

**Comment by Arthas78** [comment]
I understand that you've made sure that your address name has been authenticated by the host provider(http://prntscr.com/n5qqyx). Your error is clearly displayed in your first message (http://prntscr.com/n5qrti). You can refer the link
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/ses-errors.html

**Comment by Arthas78** [comment]
As I said above, if you use a dot-mailler and the mail is still not sent, check with the provider to be sure of your configuration information.

**Comment by methodeprog** [comment]
i get the same error and it get resolve.
Why i get this error ?
1/ admin or sender address is set to AWS SES as yoyo@domain.com
2/ i set up admin address in my application as yoyo2@domain.com  and bang here is the error !!!
Setting the same address save me !

**Comment by mickhowarth** [comment]
When you're sending test emails using mageplaza's SMTP app, it asks you which contact you want to send from within the Magento Store. "General Contact" is the default.

Note that with Amazon SES you have to verify each email you want to use to send email on SES.

So you need to configure Magento to send using the email(s) you have verified with SES.

Within Magento 2, go to Stores>Config>Store Email Addresses.

Uncheck "Use system value" then enter in whichever email address (or addresses) you have verified with your Amazon SES service.

![ses2](https://user-images.githubusercontent.com/43536478/101931467-61350380-3bd1-11eb-9dfd-64d991595436.png)

I know this thread is over a year old, but I hope this helps someone... it took me a while to figure it out myself.
