### ISSUE TITLE
Email from name not proper since Magento 2.2.8 upgrade

### ISSUE THREAD

**Issue by atishgoswami** [mageplaza/magento-2-smtp#153]
Hello Team,

We recently updated our magento store to 2.2.8 EE, 
and also added the patch fixes provided by your support team 
(Issue: #149 ) to make the extension compatible 
with the recent upgrade changes that happened in the Magento core.

Since the upgrade, we have noticed the from name 
in the emails is not showing up properly as configured 
in the Magento configuration settings.

We are not sure if the issue is due to the extension upgrade 
or due to Magento upgrade. We were hoping if your team can help us with this?

Regards,
Atish

<img width="859" alt="admin_email_setting (1)" src="https://user-images.githubusercontent.com/2647377/55317611-7bc35980-548e-11e9-8b31-c69a1f689baf.PNG">

<img width="670" alt="email_Screenshot (1)" src="https://user-images.githubusercontent.com/2647377/55317469-330ba080-548e-11e9-9834-bd6a851e1392.PNG">

**Comment by Arthas78** [comment]
From Magento 2.2.8 and above, all normal email of Magento is lost "From" name. Magento has fixed this in version 2.3.1. We trying to update to fix this issue in the lower versions 2.3.1 and will release it as soon as possible

**Comment by Arthas78** [comment]
I close the issue here.
Thank you very much!

**Comment by digikeijs** [comment]
@Arthas78 do you already have a fix for this? Using magento 2.3.0

**Comment by operations1** [comment]
@Arthas7895 Hello, Is there a fix for version 2.2.8? We are experiencing this issue after upgrade and Sender name is appearing as noreply@domian.com

Thanks!
