### ISSUE TITLE
Magento 2.3.1 Compatibility

### ISSUE THREAD

**Issue by NirmalRaval** [mageplaza/magento-2-smtp#157]
Hello,

This extension is giving error while using it with Magento v2.3.1. Following is the error that we are getting:

> _Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided_

Extension was working proper till Magento v2.3.0

Let us know when it will be available soon.

**Comment by Arthas78** [comment]
I checked SMTP module on the Magento version 2.3.1 and saw it run normally. 
Please contact us so I can check your problem. This is the link
https://www.mageplaza.com/contact.html

**Comment by Arthas78** [comment]
I will close the issue here
