### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by kerlama** [mageplaza/magento-2-smtp#161]
Hi,
after upgrade to 2.2.8 and latest smtp extension, css seems broken when email is sent out.

Although the log preview is showing correct email, actual email is broken.

Any hints ?

**Comment by Arthas78** [comment]
The SMTP module is only responsible for sending mail, every configuration of mail is set up in Magento core. You can check the email template here || http://prntscr.com/nf7xn1 
Thank you very much!
