### ISSUE TITLE
Warning: fwrite(): SSL: Broken pipe when firing mails from queue with AWS SES

### ISSUE THREAD

**Issue by atishgoswami** [mageplaza/magento-2-smtp#162]
We recently implemented a queue process to fire email asynchronous during the order creation.

When firing multiple emails from a queue consumer it seems to stumble across this error a lot:

```
Warning: fwrite(): SSL: Broken pipe in /var/www/html/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php on line 260
```

Did a little digging seems that there are some issues with SMTP connections with long-running scripts:

https://docs.zendframework.com/zend-mail/transport/smtp-authentication/#smtp-transport-usage-for-servers-with-reuse-time-limit

It recommends certain options which need to be present during the SMTP connection creation.

Will it be possible to see if these setting can be added in the `Mail/Rse/Mail.php` file.

**Comment by Arthas78** [comment]
Sorry for the late reply. Our working day has started.
Thank you very much for the documentation and comments for the module, you can add the code here || http://prntscr.com/njqzum
Thank you again!

**Comment by atishgoswami** [comment]
Hey @Arthas78 raised a PR for this

**Comment by Arthas78** [comment]
Thank you for the comments contributed to this module. If there are any other ideas, please contact us so we can discuss and improve the module better. I will close this issue here. Thank you again!

**Comment by raghuiamsingh** [comment]
@atishgoswami @Arthas7895 did the change added in PR [#163](https://github.com/mageplaza/magento-2-smtp/pull/163) work?

**Comment by JamesFX2** [comment]
Confirmed @HuyPhuc98 - this is still an issue.

**Comment by atishgoswami** [comment]
@JamesFX2 @sunilit42 @raghuiamsingh 
I got it working in a hacky way, following were the patches I implemented, 
these patches are 4 years old, so might not get applied in the latest code base, might have to make some changes

```diff
diff --git a/vendor/zendframework/zend-mail/src/Transport/Smtp.php b/vendor/zendframework/zend-mail/src/Transport/Smtp.php
index 963b599..1a37465 100644
--- a/vendor/zendframework/zend-mail/src/Transport/Smtp.php
+++ b/vendor/zendframework/zend-mail/src/Transport/Smtp.php
@@ -215,6 +215,7 @@ class Smtp implements TransportInterface
             && $this->connectedTime !== null
             && ((time() - $this->connectedTime) > $timeLimit)
         ) {
+            $this->connection->disconnect();
             $this->connection = null;
         }
         return $this->connection;

```

```diff
diff --git a/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php b/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php
index eae5a77..fa81691 100644
--- a/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php
+++ b/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php
@@ -159,9 +159,11 @@ class Mail
                 $options = $this->_smtpOptions[$storeId];
                 if (isset($options['auth'])) {
                     $options['connection_class'] = $options['auth'];
+                    $options['connection_time_limit'] = 5; // recreate the connection 5 secs after connect()
                     $options['connection_config'] = [
                         'username' => $options['username'],
-                        'password' => $options['password']
+                        'password' => $options['password'],
+                        'use_complete_quit' => false, // Dont send 'QUIT' on __destruct()
                     ];
                     unset($options['auth'], $options['username'], $options['password']);
                 }

```
