### ISSUE TITLE
504 Timeout when trying to activate module. Magento 2.2.8

### ISSUE THREAD

**Issue by neddy236** [mageplaza/magento-2-smtp#166]
Module version: 1.2.10 
Magento: 2.2.8
PHP 7.1

When im trying to activate the account im getting this error.
http://prntscr.com/nnvict

Also the request returns 504 gateway time out.
http://prntscr.com/nnvii7
http://prntscr.com/nnvim4

Since we manage the server, is there something on the server that needs to be done?

I tried 2 with 2 different emails.

**Comment by Arthas78** [comment]
Sorry for the late reply. Our working day has started.
Your problem is because our company has moved the server. Please check and upgrade the latest core version here
https://github.com/mageplaza/module-core
You can refer the link attached for more detail
https://github.com/mageplaza/module-core/issues/26
Thank you very much!

**Comment by neddy236** [comment]
I see, thanks for the heads up.

**Comment by neddy236** [comment]
Hello,

I tried to activate the extension today, but I still get the same problem. Magento has been also upgraded to 2.3.1 changed php to 7.2 and mageplaza core is on latest version already. I even reinstalled the module.

**Comment by Arthas78** [comment]
Sorry for the late reply. Our working day has started.
As mentioned above, be sure to upgrade the core module to the latest version 1.4.3.
You can't use email types as alias and grouped email

**Comment by x8Haider** [comment]
Hi Arthas78,

I'm also facing the same issue. 

Magento ver. 2.3.0
 Already using the latest version of smtp & core modules:
 "mageplaza/module-core": "^1.4",
 "mageplaza/module-smtp": "^1.2",

In my case, after clicking on activate, the website is going down. hope there is no bugs in this.

**Comment by Arthas78** [comment]
@x8Haider You need to use the lastest Core version 1.4.3. If you can't still active, you can disable the active part.  You go into etc / config.xml and change <module><type> to 0 || http://prntscr.com/nr78ib
Then flush the cache and check your site again.

**Comment by Arthas78** [comment]
7 days have passed without any feedback from you, I will close the issue here.
Thank you very much!

**Comment by yogeshkhasturi** [comment]
Hello!

This issue is still there we are using 1.4.4 or Mageplaza Core module. but no luck.


Thanks,
