### ISSUE TITLE
Email topic's is not showing after upgrade to Magento 2.3.1

### ISSUE THREAD

**Issue by sadon** [mageplaza/magento-2-smtp#169]
After Upgrading Magento to 2.3.1:

There is no email topics

Sender ID changed to simple emails, instead of: email-address@example.com

http://joxi.ru/vAWN910t1vlBv2

Unfortunately fixes, noted [here](https://github.com/mageplaza/magento-2-smtp/issues/145) are not applicable.

**Comment by Arthas78** [comment]
Are you using the latest SMTP version(1.2.10)? Currently, I find that your thread is not displayed instead of decode error as the Magento version issues first.

**Comment by sadon** [comment]
Yes, I'm using 1.2.10 
Seems like the topics doesn't display because special symblos, like as "!?:" are displayed correctly.

**Comment by Arthas78** [comment]
You can add the code || (http://prntscr.com/nuq5je), reload email log page and send me the result you received.

**Comment by sadon** [comment]
After adding var-dump, there is one topic was shown
string(65) "Подтверждение Вашего заказа OWNER-NAME-IN-RUSSIAN" -absolutely correct email's subject
There is no that topics in Grid Listing.

**Comment by Arthas78** [comment]
Thank you for your information. I need your subject so I can check on my site. You can delete the add line so the email log can return to normal.

**Comment by sadon** [comment]
After proposed fix, the problem doesn't appear. All works as expected.

Can I wait for the fix in the next versions or make as a patch that?

**Comment by Arthas78** [comment]
Because this issue only appears on your site, I'm not sure if it really needs to add to the new version. However, I will also note it and add the following versions if I encounter more the sites has the same error.

**Comment by sadon** [comment]
It's a good point to check this listing on non-English alphabets, that's would be a reason of.
Thanks
