### ISSUE TITLE
Sendgrid setup issue: Error  Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for

### ISSUE THREAD

**Issue by MrCodeFreak** [mageplaza/magento-2-smtp#171]
The module is not working with sendgrid

On none authentication I get this error: 

`Error
Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for`

on all other authentication methods I get this error:

`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\xampp71\htdocs\Magento\magento22\vendor\zendframework\zend-mail\src\Protocol\Smtp.php on line 215`

**Comment by rain2o** [comment]
@MrCodeFreak I just ran into this, not with SendGrid but still received the same error when trying to use without authentication. I just found this comment and it resolved my issue - https://github.com/mageplaza/magento-2-smtp/issues/129#issuecomment-481965985. 

@Mageplaza - This seems to be a bug with the module unless I'm missing something. Is there an open ticket to have this resolved? For me changing the None authentication value from empty to "smtp" fixed the issue.

**Comment by MrCodeFreak** [comment]
@rain2o I have tried it but did not work. I have also tried this: https://github.com/mageplaza/magento-2-smtp/issues/149#issuecomment-477420789

**Comment by Arthas78** [comment]
Your problem is currently due to the ssl certificate validation, contact the server so they can check it for you.
You can refer the link for more detail
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure || http://prntscr.com/nwlbk8

**Comment by MrCodeFreak** [comment]
I do not think sendgrid will have an ssl issue... I just used it as a test on the 465 port that did not work. Tested their non ssl ports as well and still no luck.

As the module is not updated to work with sendgrid I went to magepal and theirs work : https://github.com/magepal/magento2-gmail-smtp-app

Have a look here, might give you insights on how to correct the module.

**Comment by Arthas78** [comment]
Are you using Magento version from 2.2.8 or higher? All SMTP transport settings in that version have been changed. You can refer to it here
https://framework.zend.com/manual/2.4/en/modules/zend.mail.smtp.options.html

**Comment by MrCodeFreak** [comment]
I am using 2.2.8 however your support page says that you support all 2.2.x versions: https://www.mageplaza.com/magento-2-smtp/

If you do not support all 2.2.x versions, please update the documents.

**Comment by Arthas78** [comment]
The lastest SMTP version support with current Magento versions. Please try SMTP information on dot-mailler (this is a tool of Magento used to check SMTP configuration information). If dot-mailler can work with your SMTP information, the SMTP module may also be due to our module running like the default dot-mailler thread.

**Comment by MrCodeFreak** [comment]
Even so, that does not fix your module to work with Sendgrid, Mageplaza works so in short it is definitely the module that needs an update.

At the end I think you need to review the fact that Sendgrid is supported by the module and that it is not working with the release of 2.2.8 with this module.

**Comment by Arthas78** [comment]
Thank you, I will check with SMTP account Sendgrid and upgrade module in the future if it really fails with Sendgrid accounts

**Comment by MrCodeFreak** [comment]
@Arthas78 I am awaiting your feedback on if the issue is replicated successfully your side. It's been nearly 3 weeks without confirmation of the issue recreation nor a if a fix will be provided.

Sendgrid does offer a free account of a 100 emails a day, thus it's easy enough to test and to provide feedback.

**Comment by MrCodeFreak** [comment]
Can you send me your setting you have used to connect to sendgrid (Module configuration)

**Comment by Arthas78** [comment]
This is my configuration || http://prntscr.com/o3afo8

**Comment by MrCodeFreak** [comment]
Ok your login info is incorrect. 

the username must be "apikey" and the password must be the api key. Please see below link.

https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

**Comment by Arthas78** [comment]
Oh, your mean is API key ID instead of name|| http://prntscr.com/o3akzp

**Comment by MrCodeFreak** [comment]
No, it must be "apikey" not the API ID

Steps from sendgrid:

1. Create an API Key with at least “Mail” permissions.
2. Set the server host in your email client or application to smtp.sendgrid.net.
3. This setting is sometimes referred to as the external SMTP server or the SMTP relay.
4. Set your username to 'apikey'.
5. Set your password to the API key generated in step 1.
6. Set the port to 587.

**Comment by Arthas78** [comment]
Thank you very much! I have reconfigured and now it is working || http://prntscr.com/o3b4sb
But I still haven't received an email. maybe it's delayed. I tried setting it up with the Gmail server and found it completely normal

**Comment by MrCodeFreak** [comment]
Which version of Magento are you using?

**Comment by Arthas78** [comment]
I am using Magento 2.3.0(All Magento version more than 2.2.8 use Zend 2 to be able to send email)

**Comment by MrCodeFreak** [comment]
Thanks i will test again and let you know

**Comment by VZeroCool** [comment]
@Arthas7895 Does this resolved?

**Comment by MrCodeFreak** [comment]
@Arthas7895 I tested and with the login method I was able to test non ssl however using ssl with port 465 still returned an error.

Please can you share all your settings except API key.

**Comment by VZeroCool** [comment]
@MrCodeFreak Does this will work with local server with sendgrid?

**Comment by MrCodeFreak** [comment]
@VZeroCool I am not sure what you mean by local server

**Comment by Arthas7895** [comment]
This is my configuration || http://prntscr.com/o5s27g || http://prntscr.com/o5s2fu

**Comment by VZeroCool** [comment]
@Arthas7895 Thanks for sharing configurations it helped. It was really confusing "apikey" user and "api key id" password previously its was simple username and password That's it :) 

Test mail received successfully but via programmatically it failed and gives an exception. have you faced this !? http://prntscr.com/o5udbp

**Comment by Arthas7895** [comment]
@VZeroCool  Correctly, the SMTP module has added 1 plugin to be able to retrieve From name of the message when sending mail. you can see it in the email log || http://prntscr.com/o67piy
All default Magento emails run through that plugin and process. However, it is possible that the email in your custom module runs through but it is unable to get From name from that message so they display the exception error.
If you have used SMTP on Magepal that is already running, then I recommend disabling SMTP on my side because enabling them can conflict with each other.
Thank you very much!

**Comment by MrCodeFreak** [comment]
Hi @Arthas7895,

I can not get to to work with SSL however I guess it is a Sendgrid issue.

The error I get is:

`Error

Could not open socket: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed`

**Comment by Arthas7895** [comment]
@MrCodeFreak In my opinion, your problem is that there is something on the server that has blocked the port or your server has no SSL certificate. In Magento, the client will call stream_socket_client () in order to connect to remote servers. Your connection process is corrupted here, causing them to display an error. You should check the server and firewall to see if they have blocked the port or not with an SSL certificate

**Comment by MrCodeFreak** [comment]
Ok thank you. I am going to close the issue as it seems to me a local problem.
