### ISSUE TITLE
This extension is not actived.

### ISSUE THREAD

**Issue by Gagan557** [mageplaza/magento-2-smtp#172]
I install this extension in magento 2.1.17. But show extension is not activated. I also magento core extension 
![Screenshot (216)](https://user-images.githubusercontent.com/35591297/58703411-39eb5c80-83c6-11e9-8079-4b6324bb672d.png)

Thanks

**Comment by sumeetmobiwebtech** [comment]
i am also getting this issue.
@Gagan557  are you able to solve it ?

**Comment by Gagan557** [comment]
No, this extension is not activated show in configuration

**Comment by Arthas78** [comment]
Your problem is because our company has moved the server. Please check and upgrade the latest core version here
https://github.com/mageplaza/module-core
You can refer the link attached for more detail
mageplaza/module-core#26

**Comment by Januszpl** [comment]
I have also issue with activation

Env:
Magento 2.1.11
module-core 1.4.4
smpt ver: 1.2.10

Installed via composer.

When trying to activate request is pending.... and then admin is crashed and I have time out

**Comment by gixid192** [comment]
@Januszpl Could you try adding to your host and white list our IP? 
`198.199.79.159   dashboard.mageplaza.com`
More information here: https://github.com/mageplaza/module-core/issues/26

**Comment by Arthas7895** [comment]
It has been more than 7 days and I have not received any information from you. I will close this issue here.
Thank you very much!

**Comment by Januszpl** [comment]
Thank you for the feedback but in the end I used similar extension magepal/magento2-gmail-smtp-app that worked out of the box.
