### ISSUE TITLE
How to remove **A** sign in price of australia currency in Magento 2

### ISSUE THREAD

**Issue by Gagan557** [mageplaza/magento-2-smtp#173]
I want to remove A sign before dollar sign.I setup base currency Australian Dollar. 
![Screenshot (221)](https://user-images.githubusercontent.com/35591297/58930622-cc4e8000-8779-11e9-9379-20a34d48d9c5.png)

**Comment by MpEdward** [comment]
Hi, I'm Edward.
The remove it please refer this video https://www.youtube.com/watch?v=dOTbccH69Rs.
If you can't do it, please create the ticket on the Fresdesk system.
Since this is not part of our module, this custom may charge.

**Comment by MpEdward** [comment]
It was over 7 days and I didn't receive any reply so I will close this ticket.
Thank you!
