### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by ewemartins** [mageplaza/magento-2-smtp#175]
Good afternoon, I'm trying to install the smtp module, and when I try to send email it returns the error

Error

Could not open socket: stream_socket_client (): unable to connect to ssl: //smtp.gmail.com: 465 (Permission denied)

http://prntscr.com/o63s4q

**Comment by Arthas7895** [comment]
In my opinion, when Magento calls stream_socket_client (), something has blocked and blocked your port 465 and made it impossible to open the port. It is best to contact the server and check again
You can refer the link attached for more detail
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting || http://prntscr.com/o68bts
https://stackoverflow.com/questions/28433816/how-to-fix-could-not-open-socket-in-zend-mail-zend-framework-2

**Comment by Arthas7895** [comment]
Since I have not received any of your feedback in 7 days, I will close this issue here
