### ISSUE TITLE
Magento 2.3 SMTP Port 25 Authentication NONE

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mageplaza/magento-2-smtp#176]
Port 25 Authentication NONE

When sending the test email I get this error.

```
Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for ""
```

MagePlaza Smtp 1.2.10 installed via Composer.

Related #129 

Suggested work around by linh232323 on other issue.

```
We can fix it by overwrite mageplaza/module-smtp file
File Path: vendor/mageplaza/module-smtp/Model/Config/Source/Authentication.php
change value of None from '' into 'smtp'.

The problem is from SmtpPluginManager . it only allows:

crammd5
login
plain
smtp (This is none)
```

Example:

``` php
 $options = [
            [
                'value' => 'smtp',
                'label' => __('NONE')
            ],
            [
                'value' => 'plain',
                'label' => __('PLAIN')
            ],
```

In the admin area to configure refresh your config page, select off that Authentication Type, then select None which should now have a value of 'smtp'.

Save Config
Test email again.

Works now thank you.

**Comment by Arthas7895** [comment]
Exactly, we omitted this case when omitting this case on Zend 2. It seems that on Zend 2, there are 4 methods for the connection_class field: "plain", "login", or "crammd5" (and default to smtp). We will fix it now and update it in the latest version ASAP.
Thank you very much @LiamKarlMitchell again for this contribution

**Comment by Arthas7895** [comment]
Since I have not received any of your feedback in 7 days, I will close this issue here
Thank you very much!

**Comment by hdk** [comment]
Problem still present in version 1.3.1 (Magento 2.3.3)
