### ISSUE TITLE
5.7.8 Username and Password not accept

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [mageplaza/magento-2-smtp#178]
Error

5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials m16sm14678301pfd.127 - gsmtp

when trying to send test email getting this error i am sure i am using correct password.
i checked also with manually login

**Comment by Arthas7895** [comment]
This password is not your Gmail password. It may be generated from 2-step verification here
https://support.google.com/accounts/answer/185833?hl=en
This is your configuration information problem. Please contact the hosting provider so they can check for you.

**Comment by Kenny1994** [comment]
Since there are no issues left, I'm going to close this.
