### ISSUE TITLE
None is unsupported SSL type

### ISSUE THREAD

**Issue by duythvn** [mageplaza/magento-2-smtp#18]
SMTP with SSL works just fine for me, however, if I run with port 25 None,  this exception will keep showing up when I run the test email function http://prntscr.com/h8mo74

**Comment by codedge** [comment]
Yes, same for me. If you click "Test Now" for sendind a test mail, this error shows up.

- Module 1.0.5
- Magento 2.1.9

![error](https://user-images.githubusercontent.com/4409904/32780108-6a86611a-c940-11e7-8642-dc0a41595977.png)

**Comment by evwebcoder** [comment]
This fix does not work, I also saw that SMTP added this fix to their latest release (1.1.3). 

There is another ticket open that is also running into this same issue at:
https://github.com/mageplaza/magento-2-smtp/issues/55
