### ISSUE TITLE
Authentication Credentials Invalid  on latest verion

### ISSUE THREAD

**Issue by xanka** [mageplaza/magento-2-smtp#180]
Hi Mageplaze teams,
I using Magento 2.2.5 and latest version. I config Amazoneses email but get issue "Authentication Credentials Invalid" then test send email. I checked user and password is correct.

**Comment by Arthas7895** [comment]
This is a problem that belongs to your SMTP configuration information. Please contact your host (on Amazoneses) to check. Also on Magento, you can use dot-mailler to check your configuration information
(http://prntscr.com/ocjipv)

**Comment by Kenny1994** [comment]
Since there are no issues left, I'm going to close this.
Same issue with this ticket(#178)

**Comment by technweb** [comment]
I am running into the same problem using Amazon SES. I tested the credentials via the command line - no issues. Using the extension, Authentication is failed. It looks like something is wrong in the code.

**Comment by technweb** [comment]
@Kenny1994 another piece of the info... In "developer mode" - I am getting successful message, when developer mode is off - I am getting an error. I hope this helps.
