### ISSUE TITLE
Application-specific password required

### ISSUE THREAD

**Issue by mdzahid786** [mageplaza/magento-2-smtp#181]
Error

5.7.9 Application-specific password required. Learn more at 5.7.9 https://support.google.com/mail/?p=InvalidSecondFactor h26sm30121397pfq.64 - gs

**Comment by mdzahid786** [comment]
Resolved

**Comment by Arthas7895** [comment]
Sorry for the late reply.  This is the problem information about your configuration information and it is great to hear you solved it.
Have a nice day!
