### ISSUE TITLE
Resend Email error with `recipient` is mail address only. No name

### ISSUE THREAD

**Issue by tuyennn** [mageplaza/magento-2-smtp#185]
### Preconditions (*)
1. Magento ver. 2.3.x 2.2.x 2.1.x
2. Browser: Any
3. Hosted on Apache2
### Steps to reproduce (*)
1. From Email Log Grid
2. Resend an email with `recipient` is mail only. No name
3. Error message `We can't process your request right now.`
4. The exception throw on log `No recipient forward path has been supplied`
### Expected result (*)

1. No exception and email sent successfully

### Actual result (*)
1. Error message `We can't process your request right now.`
2. The exception throw on log `No recipient forward path has been supplied`

**Comment by Arthas7895** [comment]
Thank you for your information. We are checking your PR and improve it soon.
Thank you very much!

**Comment by Desmond-Mageplaza** [comment]
Hi @tuyennn,
You pull request is going under inspection so if there is any problem, we will inform you form the pull request thread.
Thank you for your contribution.
