### ISSUE TITLE
Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/mageplaza/provider.js'

### ISSUE THREAD

**Issue by pvalium** [mageplaza/magento-2-smtp#19]
HI, when I enter in backend, i receive this error. I tried to delete all caches, static content, but no success

**Comment by magentovietnam** [comment]
I have same issue.
To resolve it do follow step:
 - Delete all folder in pub/static/ expect .htaccess.
 - Run command: php bin/magento setup:static-content:deploy
Good luck.
