### ISSUE TITLE
Test email working, real email not being sent

### ISSUE THREAD

**Issue by jpelayo** [mageplaza/magento-2-smtp#190]
IGNORE, SOLVED
(permissions misconfiguration)

Config:
Magento 2.3.2 , php 7.2
Mageplaza Core installed with Composer.
Using devel branch for SMTP module.
Using private smtp on 25 and 587 with TLS: test works. Now using 587, TLS.
Sendmail uninstalled from base OS (centos) to make sure php mail() is not used.
Magento deploy mode: default.
No var/log output related to it.

Issue:
No magento standard emails are working: invoice, account confirmation, etc. .

**Comment by jpelayo** [comment]
Solved. PErmissions misconfiguration. Never an issue. Sorry.

**Comment by Arthas7895** [comment]
Thank you, we are always available to discuss with you the issues to increase the extension quality.
