### ISSUE TITLE
modify test mail templates

### ISSUE THREAD

**Issue by Sebastian-Gottschall** [mageplaza/magento-2-smtp#194]
Can i somewhere edit the testmail templates? My Problem is that the gateway of my Server reject all of the standard Emails (Header wrong) and i cant see any log files. So i want to use the smtp test to check where the error exactly is (Try and error). for this i need to change the templates of the SMTP Testemails. 
I already tried to change it at Marketing->Email templates (import the SMTP Test template and change it) but it is always delivered with standard 2 lines text information.
What am doing wrong? 
thanks

**Comment by Arthas7895** [comment]
You can edit the email template of send test email here || http://prntscr.com/otcee2
I checked your message and found you said Header wrong. I think it has nothing to do with the template of the send test email. You can add the following code and you can check for errors in var / test.log|| http://prntscr.com/otcge1
` $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
                $logger = new \Zend\Log\Logger();
                $logger->addWriter($writer);
                $logger->info($e->getMessage());`

**Comment by Sebastian-Gottschall** [comment]
Thank you for your reply, i just was in holiday.
I will try that soon. I just want to log the mails cause it seems that the "umlauts" (äüö) in the subject makes the problem. 
Thanks,

**Comment by Arthas7895** [comment]
It seems the problem lies in the encoding. Please check and install the latest SMTP version(1.2.10) and try again

**Comment by Arthas7895** [comment]
It's been 7 days since I haven't received a response from you, I'll close it here
