### ISSUE TITLE
No sender name in all emails

### ISSUE THREAD

**Issue by ketankpborada** [mageplaza/magento-2-smtp#195]
When i send test email sender name is showing in mail,
but order,invoce,customer email has not sender name just email is showing

**Comment by Arthas7895** [comment]
The module only sets 'from' for the message. This is displayed in the email log on your admin page. Or you can use the original show function for more detail || http://prntscr.com/ov5yik || http://prntscr.com/ov5yp1

**Comment by Desmond-Mageplaza** [comment]
Hi @ketankpborada 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.

**Comment by ebofi** [comment]
Hi,

We have the same, issue the email are coming to sender like email id. There is no option to specify sender name on module.
