### ISSUE TITLE
Installation Warning: generated/code/Magento/EavGraphQl/Model/Resolver no such file or directory

### ISSUE THREAD

**Issue by hongxy** [mageplaza/magento-2-smtp#196]
My environment is Magento CE 2.3

I run command: #composer require mageplaza/module-smtp, and got a warning message: 

The directory "/path-to-magento2/generated/code/Magento/EavGraphQl/Model/Resolver" cannot be deleted Warning!rmdir(/path-to-magento2/generated/code/Magento/EavGraphQl/Model/Resolver): No such file or directory

the installation is partially failed. I have to use command line to 
enable both Mageplaza_core and Mageplaza_Smtp to get thing work.

Any idea?
Jackey

**Comment by Arthas7895** [comment]
Strangely, if you can't install it using composer, you can try manual installation in app/code/ Mageplaza. Then run the upgrade and deploy commands as usual
You can refer the link attached for more detail
https://www.mageplaza.com/install-magento-2-extension/#solution-1-ready-to-paste

**Comment by Arthas7895** [comment]
It's been 7 days and hasn't received a response from you, I'll close the issue here
