### ISSUE TITLE
 Call to undefined method ...isMultiPart()

### ISSUE THREAD

**Issue by bogus-glitch** [mageplaza/magento-2-smtp#198]
On M2 2.2.9 getting following error: 

`Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Phrase::isMultiPart() in /var/www/magento/vendor/mageplaza/module-smtp/Mail/Transport.php:123 Stack trace: #0 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\Smtp\Mail\Transport->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #1 /var/www/magento/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}() #2 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #3 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}() #4 /var/www/magento/generated/code/Magento/Email/Model/Transport/Interceptor.php(26): Magento\Email in /var/www/magento/vendor/mageplaza/module-smtp/Mail/Transport.php on line 123`

**Comment by ncrichards** [comment]
Same problem too. For me, it seems to be coming from the invoice page. 

[Sun Oct 06 14:32:03.649903 2019] [php7:error] [pid 24946] [client 101.87.100.189:17389] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Framework\\Phrase::isMultiPart() in /var/www/magento/vendor/mageplaza/module-smtp/Mail/Transport.php:123\nStack trace:\n#0 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\\Smtp\\Mail\\Transport->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Interceptor), Object(Closure))\n#1 /var/www/magento/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(75): Magento\\Email\\Model\\Transport\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#2 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Dotdigitalgroup\\Email\\Plugin\\TransportPlugin->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Interceptor), Object(Closure))\n#3 /var/www/magento/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\\Email\\Model\\Transport\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#4 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magent in /var/www/magento/vendor/mageplaza/module-smtp/Mail/Transport.php on line 123, referer: http://local.wines.com/admin/sales/order_invoice/new/order_id/134/

**Comment by Arthas7895** [comment]
You can add the following code in Mail/Transport.php file || https://prnt.sc/pfrc4a
This is the code `method_exists($body,'isMultiPart')`
One way is to remove the isMultiPart check because it is compatible with the email attachment of the Pdf Invoice module, so you can remove it without affecting your send mail process(https://prnt.sc/pfrcyv).

**Comment by bogus-glitch** [comment]
Great thanks.

Is there any chance to have a patch or workaround inside the  module?

We are pulling this module via composer during our automated deployment.

**Comment by Arthas7895** [comment]
In fact, changing the code in a module completely takes a lot of steps. You can add the code directly on your site (if you install it via the composer, change it at vendor/mageplaza/module_smtp/Mail/ Transport.php). We are currently waiting for Magento 2.3.3 to be released to check the module again and upgrade it if necessary. so I will note this problem and will add it to the upcoming update of the module

**Comment by Arthas7895** [comment]
it's been 7 days without any response from you so I'll close issue here.
Have a nice day!
