### ISSUE TITLE
adminhtml mageplaza folder not being generated.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [mageplaza/magento-2-smtp#201]
When I run a ```php bin/magento setup:static-content:deploy``` on my server that is configured as a production server it does not generate the path ```pub/static/adminhtml/Magento/backend/en_US/mageplaza``` at all. 

This in turn throws errors on my admin site. 

```
GET http://merkzoo-prod.selectedpixel.com/static/adminhtml/Magento/backend/en_US/mageplaza/testemail.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.js:1895
load @ require.js:1639
load @ require.js:820
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
(anonymous) @ require.js:1128
(anonymous) @ require.js:132
each @ require.js:57
enable @ require.js:1090
init @ require.js:774
(anonymous) @ require.js:1416
setTimeout (async)
req.nextTick @ require.js:1755
localRequire @ require.js:1405
window.require @ mixins.js:245
init @ main.js:24
(anonymous) @ main.js:96
_.each._.forEach @ underscore.js:150
(anonymous) @ main.js:79
apply @ main.js:76
bootstrap @ bootstrap.js:106
fire @ jquery.js:3232
fireWith @ jquery.js:3362
ready @ jquery.js:3582
completed @ jquery.js:3617
main.js:37 Error: Script error for: mageplaza/testemail
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
```

I'm assuming this is being auto generated when running in developer mode, but I haven't tested that yet. 

I'm running Magento 2.2.10 and version 1.2.10 of mageplaza/module-smtp

**Comment by Arthas7895** [comment]
This problem may be because the js file has not been loaded. You can replace the following code || https://prnt.sc/pqwvs2 in where to install SMTP module/view/adminhtml/templates/system/config/ button.phtml 
Then flush the cache and try again. This is the code
`Mageplaza_Smtp/js/testemail`

**Comment by Arthas7895** [comment]
It's been over 7 days and I haven't received your response, I'll close the issue here
Thank you!

**Comment by vishalthakurit** [comment]
Thanks @Arthas7895 i have also faced this issue. you solved my problem.

**Comment by joeldavuk** [comment]
This is still an issue in the latest release

**Comment by selected-pixel-jameson** [comment]
I’ve been a software developer for a long time and I’ve never run into a platform as awful as Magento. I literally dropped a good paying client because I could no longer deal with this horrible platform. Since then my quality of life has gone way up. Best decision I’ve ever made.

**Comment by matasnizamovas** [comment]
Why is this issue closed, @Arthas7895 ? The solution does not seem appropriate.
