### ISSUE TITLE
mailhog test not working

### ISSUE THREAD

**Issue by neverovsky** [mageplaza/magento-2-smtp#204]
If i enter mailhog details:
Host 127.0.0.1 
Port 1025
Protocol None
Authentication None
->Save
->Enter email and click Test email , show popup with error:

SmtpPluginManager::get was unable to fetch or create an instance for  at vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555

**Comment by neverovsky** [comment]
Forgot to say, if send email from Orders (Send email to customer) all working fine and im getting email in mailhog, so im sure what configuration is OK

**Comment by Arthas7895** [comment]
Are you using the Magento version 2.2.8 above?
If right, you can change the value to smtp || https://prnt.sc/pu5b50
This is a file path which needs to edit  
where is install Smtp module\Model\Config\Source\Authentication.php

**Comment by neverovsky** [comment]
Thank you @Arthas7895 it helped me and now it works, why it is not in master? i also fixed it just by changing to PLAIN authentication without fill any name or passwords and it is also works with MailHog fine
