### ISSUE TITLE
gigabytes of retries in mageplaza_smtp_log and system.log

### ISSUE THREAD

**Issue by marcejohnson** [mageplaza/magento-2-smtp#205]
Hi!  

We are running **magento-2-smtp v1.2.10** on **Magento 2.2.5 CE**. 

We are seeing gigabytes of retries per day getting stored in `mageplaza_smtp_log` with status of `0`. We clear these failures out daily with `DELETE FROM mageplaza_smtp_log where status=0;` to prevent our database from blowing out by gigabytes.

The curious thing is, emails **are** getting through.  It appears that `magento-2-smtp` is intermittently (once or twice per day) rapid-retrying hundreds of times per second, overwhelming the smtp provider (sendgrid).  The rest of the time sends occur with no issue.

We also see millions of these in the `system.log` when the retries intermittently occur:  

`system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []
system.log:[2019-11-07 21:56:57] main.ERROR: Could not read from smtp.sendgrid.net [] []`

Notice how happening in same second.
  
Would it be better for retries to back off (polynomially or exponentially) to prevent accidentally flooding the server/db/logs?  E.g. if failing, politely wait 1 second, then 2 seconds, then 4 seconds, etc until can get through.

Or is this some other issue -- or already known?  Apologies in advance if this is in another issue/ticket.
Thanks a lot, and please advise.

-Marc

**Comment by marcejohnson** [comment]
Thanks @Arthas7895.  I inquired with sendgrid (the email provider) and they said "you can open up to 10 connections open at one time. Each connection can send up to 100 emails so 1000 total."   Given that all providers will have constraints like this, how does magento-2-smtp handle payload segmentation?  E.g. if 200 emails are sent, how will magento-2-smtp distribute across connections?  The module originating  emails (in this case a "back in stock" module) won't know about or be able to control transport details.

**Comment by marcejohnson** [comment]
My latest on the support ticket with sendgrid

> Thanks Emily.  Can the limit be increased with a different plan?  There must be customers that send more than 100 emails at a time on a connection.   We don't have control of the vendor software which sends (so we can't divide it across multiple connections) so we need a bigger pipe.

Moving to "blocked" until we get the increase.

**Comment by Arthas7895** [comment]
Our SMTP module currently only supports 1 SMTP configuration (1 connection) per store view. So, unfortunately, it may not match your request. If you want, you can make configuration changes (user and password) for each respective store view (https://prnt.sc/qdeqle)

**Comment by imsamthomas** [comment]
Hi @marcejohnson ,
@Arthas7895  mean that: The configuration support per Magento store view.

In Magento 2 by default, every email sends to the message queue, and will process every minute.
`Each consumer processes 10000 messages and then terminates`, so you can change this number.

Edit the `/app/etc/env.php` file to configure the cron job consumers_runner.

```
...
    'cron_consumers_runner' => array(
        'cron_run' => false,
        'max_messages' => 20000,
        'consumers' => array(
            'consumer1',
            'consumer2',
        )
    ),
...
```

Hope this help.

**Comment by Kenny1994** [comment]
Hi, if there are no questions I'm going close to this issue, thank you all.
