### ISSUE TITLE
invalid mail address on activate extension 1.2.11 with magento 2.2.6

### ISSUE THREAD

**Issue by tukker01** [mageplaza/magento-2-smtp#206]
When i try to activate the extention the extention give a error invalid mail address

**Comment by Victor-Mageplaza** [comment]
Hi @tukker01 ,
I'm Victor from Mageplaza. I would like to answer your question.
Please try to update to the latest version of the Core module.
Here is the download link: https://github.com/mageplaza/module-core 
And try again and let me know about the result.

**Comment by Victor-Mageplaza** [comment]
For long time no response. I will close topic here

**Comment by tukker01** [comment]
Sorry for the late response updating module-core resolved the isseu, thanks
