### ISSUE TITLE
Failed to send mail when Authentication is set to NONE

### ISSUE THREAD

**Issue by cfman** [mageplaza/magento-2-smtp#207]
Hi, I'm using Magento 2.3.3 with module smtp version 1.2.11.

When I set Authentication to NONE, mail cannot be sent.

This is the error for sending test email:
![image](https://user-images.githubusercontent.com/10381489/69410856-d58ed180-0d46-11ea-9ca4-41d24ef9d8e5.png)

The problem should be caused by this line:
https://github.com/mageplaza/magento-2-smtp/blob/2e191864b3c6b95df866f61d65747cb73a770a9e/Mail/Rse/Mail.php#L161

**Comment by Arthas7895** [comment]
Oh! sorry, this is a module error when running Magento versions 2.2.8 or higher.
You can add the code in the file(where you install the SMTP module/Model/Config/Source/Authentication.php) || https://prnt.sc/q0h72x

**Comment by cfman** [comment]
Thanks. This works.

Will there be a new release very soon with fix? So that I don't need to apply the fix by patch.

**Comment by Arthas7895** [comment]
This is my fault, I forgot to update it in the latest SMTP module to be compatible with Magento 2.3.3. Please be assured, we will add it in a later version and release it ASAP

**Comment by Arthas7895** [comment]
Currently, if your issue has been resolved I will close this issue here. We are happy to discuss this with you to resolve the issues of this module. I will try to perfect the new version
Have a nice day!
