### ISSUE TITLE
Resend logic for Amazon SES

### ISSUE THREAD

**Issue by wuming1456** [mageplaza/magento-2-smtp#208]
![Screenshot_2019-11-25_20-40-01.png](https://i.loli.net/2019/11/25/fJzlE38N4XwU2qv.png)
According to the document of Amazon SES [https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-issues.html](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-issues.html), sending emails should use retry logic, could you please add auto retry logic when a network problem occurs.

**Comment by Arthas7895** [comment]
First, thanks for your information. Currently, we are quite busy because it is the end of the year so currently we can not test to add it to the SMTP module however I have noted it and will learn and add if it is really needed

**Comment by Arthas7895** [comment]
I noted this issue on our Trello. We will update it soon.
Thank you very much!
