### ISSUE TITLE
No sender name in all emails 

### ISSUE THREAD

**Issue by ebofi** [mageplaza/magento-2-smtp#210]
Hi,

Emails send from the module are  missing the sender name rather it shows email id to customer,we checked the orginal format of the mail too and there only the email id is present. No sender name?

Advise on this

**Comment by Arthas7895** [comment]
Can you tell me the Smtp module and the Magento version? 
This is strange because, without the From for the message, emails will not be sent. Can you take your email log for me to check?

**Comment by Rugento** [comment]
I confirm that with Cyrillic characters in from and to they are cut with the iconv_mime_decode () function since they are not encoded in mime.
Check Sender name = Тестовая запись

**Comment by Arthas7895** [comment]
You should download the replace the new version(1.2.10) here
https://github.com/mageplaza/magento-2-smtp
In this version, I changed the code to make it more suitable for the characters in Magento 2.3.3

**Comment by Arthas7895** [comment]
It's been 7 days since I haven't heard from you, so I'll close this issue here.
Thank you!

**Comment by gillouz** [comment]
HI 

we have The same issue. despite the name is filled in the email configuration it is never sent

we are using magento 2.3.0 and SMTP version 1.4.1

We tried with two different SMTP server we also try to deactivate amazon modules

Please tell how I could help you.

Gilles
