### ISSUE TITLE
AWS SES Email address is not verified error message

### ISSUE THREAD

**Issue by azmeehan** [mageplaza/magento-2-smtp#211]
Hi There,

We have the latest version of the extension and also the core module installed on Mage 2.3.2 

We have set up all Zone records and verified everything in AWS SES.

If we send a test using customer support email to itself it works but with anything else we get the following.

info@xyz.com to info@xyz.com works
info@xyz.com to test@xyz.com fails with the below error message.

Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: test@xyz.com

We have verified the email address but wondering do we need to verify the domain itself as well?

**Comment by Arthas7895** [comment]
Because you use amazon as a hosting provider, the authentication needs more configuration here(https://prnt.sc/q4y5db)
|| https://github.com/mageplaza/magento-2-smtp/issues/8#issuecomment-340701711

**Comment by Arthas7895** [comment]
Since the problem has been resolved, I will close this issue here
Thank you!

**Comment by ahmedelbougha** [comment]
For those who may ask later:
1- Please make sure that you have the correct email addresses setup under Stores > Settings > Configuration > General > Store Email Address
2- Please make sure that even your SES email you are sending (FROM) is verified in SES and out of sandbox mode
3- If the email you are sending from is still in sandbox mode, please make sure that that email you are sending (TO) is verified
