### ISSUE TITLE
Setup upgrade is now failing

### ISSUE THREAD

**Issue by dbashyal** [mageplaza/magento-2-smtp#212]
I am getting below error when trying to run setup upgrade:

```
Module 'Mageplaza_Smtp':
Installing schema... Upgrading schema... SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sender'
```

**Comment by dbashyal** [comment]
nvm I added try{}catch{} to upgradeschema.php file and it went smooth.

**Comment by Arthas7895** [comment]
Your problem is due to the sender column that was created earlier. You can fix it by adding the code 
|| https://prnt.sc/q5vkc8 in the module Smtp/Setup/UpgradeSchema.php
This is a code
`    if ($connection->tableColumnExists('mageplaza_smtp_log', 'sender') === false){...}`

**Comment by Arthas7895** [comment]
Since I haven't received your response in 7 days, I will close this issue here
Thank you very much!

**Comment by fajriarma** [comment]
Hi all, I was delete table mageplaza_smtp_log, I run bin/magento setup:upgrade, showing : SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
any solution?
