### ISSUE TITLE
DKIM fails when email is sent through M2 SMTP

### ISSUE THREAD

**Issue by ashishbutola01** [mageplaza/magento-2-smtp#214]
After installing and configuring M2 SMTP for custom SMTP server, DKIM Fails. And when sending mails through PHPMailer (for same SMTP server and config) no such issue is noticed.

**Comment by Arthas7895** [comment]
The SMTP module is only responsible for configuring, connecting to the mail server and sending messages through it. It does not affect the mail message header. 
You can try disabling the SMTP module and try reconfiguring on Magento's dot-mailler

**Comment by Arthas7895** [comment]
Since I haven't received any response from you in the past 7 days, I will close this issue here
Thank you!
