### ISSUE TITLE
multi websites fix ?

### ISSUE THREAD

**Issue by angelflo** [mageplaza/magento-2-smtp#215]
Hi,
It seems that you had developed a fix to solve pb of sending email from bakcend with bad FROM email address (who use default and not the correpsonding website) :
https://github.com/magento/magento2/pull/18472#issuecomment-501660141
Can you tell me if it's already integrated in your release or if it need a patch ?
If need a patch, please can you share it here.
Thanks a lot

**Comment by Arthas7895** [comment]
Since I haven't received any response from you in the past 7 days, I will close this issue here
Thank you!
