### ISSUE TITLE
AWS SES not working

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-smtp#217]
Magento 2.3.3

We can't send any emails anymore.

`Transaction failed: Domain contains illegal character`

Removing return-path email, new error:

`Transaction failed: Expected disposition, got =`

Solution?

**Comment by Arthas7895** [comment]
You can try the following 2 solutions
Solution 1: you can change the code(https://prnt.sc/qcuegf) in the file
Where have you installed SMTP module\Mail\Transport.php
Solution 2: you can try to the solution here https://github.com/mageplaza/magento-2-smtp/pull/203
