### ISSUE TITLE
Two new region of SES

### ISSUE THREAD

**Issue by bdjunayed** [mageplaza/magento-2-smtp#218]
Two new region of SES need to add 
1. ap-southeast-2
2. ap-south-2

**Comment by Arthas7895** [comment]
Thank you for your information. I will check it.

**Comment by Arthas7895** [comment]
I checked those 2 domain names and found the module was still running normally. Currently, you only need to use the latest version module

**Comment by Arthas7895** [comment]
It's been 7 days without a response from you so I'll close this issue here
Have a nice day!
