### ISSUE TITLE
Magento 2 SMTP - Amazon SES configuration

### ISSUE THREAD

**Issue by bdjunayed** [mageplaza/magento-2-smtp#219]
Where to put the AWS ID, Secret and the smtp key, secret. Help wanted.

**Comment by Arthas7895** [comment]
I don't understand your question. The SMTP configuration information is taken from the 'user smtp security credentials' when you took the configuration
You can refer the link attached
https://www.youtube.com/watch?v=IrSP7soIq3A&t=308s

**Comment by bdjunayed** [comment]
We only need the smtp ID, and the secret with this plugin. Sorry for this post. I am closing it.

**Comment by bdjunayed** [comment]
We only need the smtp ID, and the secret with this plugin. Sorry for this post. I am closing it.

**Comment by bdjunayed** [comment]
We only need the smtp ID, and the secret with this plugin. Sorry for this post. I am closing it.
