### ISSUE TITLE
Emails Log error

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-smtp#22]
Hi,

If i go to see email logs I get following error.

Warning: iconv_mime_decode(): Malformed string in /magento2/app/code/Mageplaza/Smtp/Ui/Component/Listing/Column/ViewAction.php on line 80

**Comment by ad1rie1** [comment]
Same problem here :)

**Comment by gixid192** [comment]
Please help us check again this config `Configuration -> Sales -> Sales Emails -> Order -> Send Order Email Copy To.`
Make sure you guys use `comma` instead of `space` to separate the emails.

We also released version 1.1.3, please get the latest version and see if you guys still have the issue.

**Comment by gixid192** [comment]
Close due to no response within 7 days.
