### ISSUE TITLE
g-suit not work

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-smtp#220]
g-suit gmail use 2-step veriflcation,app-password
on the magento2 backend,sent test email,the error like this:
5.7.8 Username and Password not accepted. Learn more at 5.7.8 support google com / mail / ? p=BadCredentials y5sm2165638ilk.83 - gsmtp

host:smtp.gmail.com
port:587
Protocol:tls
Authentication:login
Username:g-suit email
Password:app-password

**Comment by Arthas7895** [comment]
Please try to enable "Access for less secure apps" by following the link
https://myaccount.google.com/lesssecureapps

**Comment by Arthas7895** [comment]
It's been 7 days without a response from you so I'll close this issue here
Thank you very much!
