### ISSUE TITLE
Package zendframework/zend-stdlib is abandoned!

### ISSUE THREAD

**Issue by bdjunayed** [mageplaza/magento-2-smtp#221]
Happy New Year!

When I tried to install the plugin by this (composer require mageplaza/module-smtp) command it shows this following errors: 

Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.

Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.

Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

...and so on.

**Comment by Arthas7895** [comment]
You can try to install this module manually (in app/code). You can follow the link below
https://www.mageplaza.com/install-magento-2-extension/#solution-1-ready-to-paste

**Comment by jorgb90** [comment]
The packages are really abandoned.. See for example

https://packagist.org/packages/zendframework/zend-json  
https://packagist.org/packages/zendframework/zend-form
https://packagist.org/packages/zendframework/zend-filter

**Comment by Zyles** [comment]
Zend is changing name to https://getlaminas.org/

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
