### ISSUE TITLE
High CPU usage on magento 2.3.2 and php 7.2

### ISSUE THREAD

**Issue by dongshan3** [mageplaza/magento-2-smtp#222]
Sir,

My friend's server is 4 core CPU and 16GB RAM, install apache 2.4, php 7.2 on CentOS 7.

After install Mageplaza_Smtp, I saw more than 15 "load average" on top statues, for example:

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6113 apache    20   0  663360 129220  56596 R  27.5  0.8   3:06.67 httpd
 8252 apache    20   0  410408  42588  10700 R  27.2  0.3   0:04.40 php
 7380 apache    20   0  667644 131068  54164 R  26.5  0.8   3:53.21 httpd
 7837 apache    20   0  659360  96884  28424 R  25.2  0.6   1:29.86 httpd
 8224 apache    20   0  466300  98672  11192 R  25.2  0.6   0:20.08 php
 8226 apache    20   0  466300  98668  11192 R  25.2  0.6   0:20.22 php
 8242 apache    20   0  449704  82464  11180 R  25.2  0.5   0:12.02 php
 5472 apache    20   0  674368 136376  52812 R  24.8  0.8   3:38.56 httpd
 8248 apache    20   0  410408  42588  10700 R  24.8  0.3   0:04.34 php
 7851 apache    20   0  661324 105340  34856 R  24.5  0.6   2:40.42 httpd
 8135 apache    20   0  638192  81624  34284 R  24.5  0.5   0:22.58 httpd
 7849 apache    20   0  661580 106432  35712 R  23.8  0.7   2:32.91 httpd
 8222 apache    20   0  466972  99196  11192 R  23.8  0.6   0:20.88 php
 8239 apache    20   0  449704  82464  11180 R  23.8  0.5   0:11.49 php
 8250 apache    20   0  410408  42584  10700 R  23.8  0.3   0:04.36 php
 7508 apache    20   0  659672 108980  40168 R  23.2  0.7   2:35.54 httpd

If I run "bin/magento module:disable Mageplaza_Smtp", "bin/magento module:disable Mageplaza_Core" to disable smtp module, then reboot server "load average" will back to normal.

Do I need to downgrade php from 7.2 to 7.1?

Thank you.

**Comment by Arthas7895** [comment]
The installing and using modules will cost you a "load average". This is correct. 
Your mention of the downgrade of PHP version will not affect this issue

**Comment by dongshan3** [comment]
> 
> 
> The installing and using modules will cost you a "load average". This is correct.
> Your mention of the downgrade of PHP version will not affect this issue

Thanks for reply. I tried to install another smtp module, it also cost 100% CPU usage. And as you said that most like there is problem on my Magento2 installation, not smtp modules problem.
