### ISSUE TITLE
Broken on Magento 2.4-develop

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-smtp#223]
Guess this extension will not work on the new version either.

`main.CRITICAL: Unable to send mail: Unknown error {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail: Unknown error at /home/http/magento_2.4-dev/app/code/Magento/Email/Model/Transport.php:103, Zend\\Mail\\Transport\\Exception\\RuntimeException(code: 0): Unable to send mail: Unknown error at /home/http/magento_2.4-dev/vendor/zendframework/zend-mail/src/Transport/Sendmail.php:305)"} []
`

**Comment by Arthas7895** [comment]
Can you provide the link to download and install the Magento 2.4 version you are referring to? I went to Magento's homepage and didn't see it updated

**Comment by Arthas7895** [comment]
Ok, I found the link. I will check and notify you of the results

**Comment by mcirsta** [comment]
I got exactly the same error but with Magento 2.3.3 and php7.3 on Ubuntu 18.04. Might actually be a php issue ?
 Interesting that sending the test email works and I had the same configuration but just with php7.2 and that also worked.

**Comment by mcirsta** [comment]
I used this link to install php7.3 :  https://www.cloudbooklet.com/how-to-install-php-7-3-on-ubuntu-18-04/

**Comment by Zyles** [comment]
Nah it is not php. It is a module compatibility with Magento 2.3.3 problem because Magento devs made breaking changes in minor release.

**Comment by mcirsta** [comment]
In my case it was a false alarm I guess. I did something wrong or something went wrong and in Mail/Transport.php at line 111 there's a check: $this->resourceMail->isModuleEnable($this->_storeId)
 For me this one was returning false for some reason. Once that one was removed now it works.
 I suggest printing some message about the module being disabled or something. I don't really understand though as my module is enabled and also registered.

**Comment by Arthas7895** [comment]
I checked our Smtp module on Magento 2.3.4 and saw it ran normally | https://prnt.sc/r23m8l
@mcirsta I don't think the code that checks the enable module is wrong. It only checks the status of the module on each of your stores. You can check the module on each of your stores is here | https://prnt.sc/r23n18

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
