### ISSUE TITLE
the test message show success message but the email doesn't get anything

### ISSUE THREAD

**Issue by robertbaum** [mageplaza/magento-2-smtp#224]
Hello
The test message shows a success message but I didn't get anything at the email.

Magento 2.3.3
using magento-2-smtp

**Comment by Arthas7895** [comment]
Please make sure you have configured the following fields correctly || https://prnt.sc/qnu5a4 || https://prnt.sc/qnu5e8
Thank you!

**Comment by Jean-MarcS** [comment]
Same problem since upgrading from 2.2.8 to 2.2.10 : no mail, no log, nothing, except when testing the success message says all is ok (and yes, the module is configured whith dev no...)

**Comment by Arthas7895** [comment]
If you are sure all of the above settings are not being sent to your IB, contact your mail server so that they can check this problem because the mail server is a hub for your messages to your IB'receiver.
NOTE you also need to check your spam section.

**Comment by robertbaum** [comment]
The problem was from the mail server,thanks

**Comment by Jean-MarcS** [comment]
After analysing what was send, this is what might cause the problem :

Content-Disposition: =?utf-8?Q?inline?=

On earlier version of Magento I've got 

Content-Disposition: inline

This causes mail software (Thunderbird in my case) to consider there is an attachment.

And my mail provider antispam to consider there should be an attachment where there's not and direct it straight to SPAM

Any idea why those =?utf-8?Q? suddenly appeared ?
