### ISSUE TITLE
Installation fails on Magento 2.3.3

### ISSUE THREAD

**Issue by devstashuser** [mageplaza/magento-2-smtp#225]
I am trying to install the extension I get the below error. 

Magento Version: 2.3.3

Install commands in Magento root directory.

`composer require mageplaza/module-smtp`
`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`

Error:

`Using version ^1.4 for mageplaza/module-smtp`
`./composer.json has been updated`
`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Nothing to install or update`
`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`
`Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.`
`Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.`
`Package zendframework/zend-barcode is abandoned, you should avoid using it. Use laminas/laminas-barcode instead.`
`Package zendframework/zend-captcha is abandoned, you should avoid using it. Use laminas/laminas-captcha instead.`
`Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.`
`Package zendframework/zend-config is abandoned, you should avoid using it. Use laminas/laminas-config instead.`
`Package zendframework/zend-console is abandoned, you should avoid using it. Use laminas/laminas-console instead.`
`Package zendframework/zend-crypt is abandoned, you should avoid using it. Use laminas/laminas-crypt instead.`
`Package zendframework/zend-db is abandoned, you should avoid using it. Use laminas/laminas-db instead.`
`Package zendframework/zend-di is abandoned, you should avoid using it. Use laminas/laminas-di instead.`
`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.`
`Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.`
`Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.`
`Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.`
`Package zendframework/zend-filter is abandoned, you should avoid using it. Use laminas/laminas-filter instead.`
`Package zendframework/zend-form is abandoned, you should avoid using it. Use laminas/laminas-form instead.`
`Package zendframework/zend-http is abandoned, you should avoid using it. Use laminas/laminas-http instead.`
`Package zendframework/zend-hydrator is abandoned, you should avoid using it. Use laminas/laminas-hydrator instead.`
`Package zendframework/zend-i18n is abandoned, you should avoid using it. Use laminas/laminas-i18n instead.`
`Package zendframework/zend-inputfilter is abandoned, you should avoid using it. Use laminas/laminas-inputfilter instead.`
`Package zendframework/zend-json is abandoned, you should avoid using it. Use laminas/laminas-json instead.`
`Package zendframework/zend-loader is abandoned, you should avoid using it. Use laminas/laminas-loader instead.`
`Package zendframework/zend-log is abandoned, you should avoid using it. Use laminas/laminas-log instead.`
`Package zendframework/zend-mail is abandoned, you should avoid using it. Use laminas/laminas-mail instead.`
`Package zendframework/zend-math is abandoned, you should avoid using it. Use laminas/laminas-math instead.`
`Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.`
`Package zendframework/zend-modulemanager is abandoned, you should avoid using it. Use laminas/laminas-modulemanager instead.`
`Package zendframework/zend-mvc is abandoned, you should avoid using it. Use laminas/laminas-mvc instead.`
`Package zendframework/zend-psr7bridge is abandoned, you should avoid using it. Use laminas/laminas-psr7bridge instead.`
`Package zendframework/zend-serializer is abandoned, you should avoid using it. Use laminas/laminas-serializer instead.`
`Package zendframework/zend-server is abandoned, you should avoid using it. Use laminas/laminas-server instead.`
`Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.`
`Package zendframework/zend-session is abandoned, you should avoid using it. Use laminas/laminas-session instead.`
`Package zendframework/zend-soap is abandoned, you should avoid using it. Use laminas/laminas-soap instead.`
`Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.`
`Package zendframework/zend-text is abandoned, you should avoid using it. Use laminas/laminas-text instead.`
`Package zendframework/zend-uri is abandoned, you should avoid using it. Use laminas/laminas-uri instead.`
`Package zendframework/zend-validator is abandoned, you should avoid using it. Use laminas/laminas-validator instead.`
`Package zendframework/zend-view is abandoned, you should avoid using it. Use laminas/laminas-view instead.`
`Writing lock file`
`Generating autoload files`

I am fairly new to this please correct me if I am doing anything wrong. Thank you

**Comment by vincentteyssier** [comment]
Hi, there is no error here, this is how it is supposed to run. This issue should be closed

**Comment by bdtrung** [comment]
As the @vincentteyssier said, please check your vendor/mageplaza/ folder, the module package should be there @devstashuser.
