### ISSUE TITLE
tell ( silly people ) that the Enable Mageplaza SMTP is not enabled

### ISSUE THREAD

**Issue by mcirsta** [mageplaza/magento-2-smtp#226]
I forgot to enable this setting and it resulted in a very weird unknown exception. I suggest checking for this when doing the test email sending and saying that the email was successfully sent but without this setting any normal emails will not be.
 Also there could be a separate if for this setting being enabled and the logs could clearly show that this was the reason the email was not sent.
 Right now the code checks for:         if ($this->resourceMail->isModuleEnable($this->_storeId) && $message) {
after which there's no way to know the reason it failed.

**Comment by bdtrung** [comment]
Thanks for your contribution.
We will check this issue again and will update it soon.
