### ISSUE TITLE
Mail rejected as SPAM because of Content-Disposition header in 2.2.10

### ISSUE THREAD

**Issue by Jean-MarcS** [mageplaza/magento-2-smtp#227]
I have problem with my mail provider who is directly put my outgoing mail on SPAM.

After analysing the content of the message (and headers) that was send, this is I think what might cause the problem :

Content-Disposition: =?utf-8?Q?inline?=

On earlier version of Magento I've got 

Content-Disposition: inline

This causes mail software (Thunderbird in my case) to consider there is an attachment.

And my mail provider antispam to consider there should be a file attached where there's not and direct the mail straight to SPAM

Any idea why those =?utf-8?Q? suddenly appeared ? And how to make it work again ?

**Comment by Arthas7895** [comment]
Our module only works by sending mail. Your problem is probably due to the attachment issue. You need to check which module is attached and contact that party to let them check

**Comment by Arthas7895** [comment]
It's been over 7 days without a response from you so I'll close this issue here
Thank you!
