### ISSUE TITLE
Email Header

### ISSUE THREAD

**Issue by pcbuddyuk** [mageplaza/magento-2-smtp#23]
Hi,

Sends emails fine but the email sender is only the store name, no email address is there, i've checked all the astore settings in confirguration and the email address is all set.

Please help

Thanks

Simon

**Comment by gixid192** [comment]
Could you tell us what host are you using?

**Comment by pcbuddyuk** [comment]
the site is hosted on my own vps, if you mean email smtp its through dnsmadeeasy.com, i've tried 2 smtp's and they both do the same thing

Thanks

**Comment by gixid192** [comment]
Hi Simon,

We just released a new version 1.1.3, please check it and let us know if you still have the issue.
If you still has the issue, please create a ticket in our ticket system: https://mageplaza.freshdesk.com/support/home

**Comment by gixid192** [comment]
Close due to no response within 7 days.
