### ISSUE TITLE
Can't save password

### ISSUE THREAD

**Issue by lewis617** [mageplaza/magento-2-smtp#231]
When I tested email, it worked well. but, after I clicked the save config button. the password is reset.

My magento is 2.1.15

**Comment by Arthas7895** [comment]
About your question, I can confirm the following. Your passwords don't have to be reset but they will be encrypted to avoid being snooped by anyone who can access your admin page. You can send a test email and if it succeeds, the information you have entered is correct.
You can refer the code which will be encrypted here | https://prnt.sc/qwmovc

**Comment by lewis617** [comment]
> About your question, I can confirm the following. Your passwords don't have to be reset but they will be encrypted to avoid being snooped by anyone who can access your admin page. You can send a test email and if it succeeds, the information you have entered is correct.
> You can refer the code which will be encrypted here | https://prnt.sc/qwmovc

after entered the password, I can send a email and it succeeds, but after clicked the save config button, I sent a test email again and it failed.

**Comment by lewis617** [comment]
I see what you mean. password is be encrypted, so I can't test it, but I can use it in delete account, reset password and so on.
