### ISSUE TITLE
2.2.10 with SES is broken

### ISSUE THREAD

**Issue by ctadlock** [mageplaza/magento-2-smtp#235]
Emails are not sent, shows error: `Transaction failed: Expected disposition, got =`

What I think happened were changes were made to this extension for the 2.3.X but didnt also handle the 2.2.10.

**Comment by Arthas7895** [comment]
You can try to the solution attached 
https://github.com/mageplaza/magento-2-smtp/pull/203
Or you can change the code | https://prnt.sc/r3d5nr

**Comment by Arthas7895** [comment]
It's been 7 days since I received your response, so I'll close the issue here
