### ISSUE TITLE
Security vulnerability using app:config:dump

### ISSUE THREAD

**Issue by Bowens20832** [mageplaza/magento-2-smtp#236]
If you were to build a Magento 2 store using a pipeline deployment method as described in the magento docs

https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/example/shared-configuration.html

When you generate a shared configuration file, all the sensitive values are a dumped into the config.php in plain text and are able to be checked into source control. 
```
php bin/magento app:config:dump
```

If I were to continue to follow the Magento Pipeline Deployment guide, the next step would be to   check that file into source code and that could be bad for people who aren't reviewing their config files before committing.

Sensitive values should be set in env.php instead of config.php because Magento 2 is configured to ignore the env.php in .gitignore.

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.html

**Comment by Bowens20832** [comment]
I submitted a PR with a basic fix using the methods described in the Magento Dev Docs. The native Magento 2 Paypal module can be used as a reference because I can confirm that paypal credentials are being stored in env.php

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/etc/di.xml

**Comment by Arthas7895** [comment]
Thank you for this information, but due to Magento's Shared configuration, the configuration information can only be viewed and cannot be changed. This is inconvenient for other administrators who want to change configuration and testing information so we won't merge your code as it is not necessary for the functionality of the module.
But it is also a pleasure to share and hope we can discuss further in the future to improve the quality of the module.
Thank you again!

**Comment by Arthas7895** [comment]
I will close this issue here.
Have a nice day!

**Comment by barbazul** [comment]
Wow! I cannot believe by how much you missed the point made by the OP.

Shared configuration is supported by the platform and the oficially recommended way to build the Magento application, specially for Magento Cloud.

Some companies might consider this to be annoying and not use it at all. That's fine. The point of the issue raised by @Bowens20832 still stands. `bin/magento app:config:dump` **should not** dump system-specific and sensitive information, so the module should have support for that scenario.

Regarding PR #237 I would argue that, for this particular module having the `smtp/general/enabled` listed in the `environment` pool would make sense, but I may be biased by my particular use case.
