### ISSUE TITLE
order confirmation email is not sent for guest's order only Magento 2.1

### ISSUE THREAD

**Issue by aramega** [mageplaza/magento-2-smtp#24]
Hi Mageplaza Team,

In the backend shows (The order confirmation email is not sent), if i clicked on send email it sends the message.

and if the customer logged in its working fine.

Configuration

Sales -> Sales Emails -> General Settings -> Asynchronous sending is Disable

**Comment by imsamthomas** [comment]
If you do not use Mageplaza SMTP, you still get this problem :)
Check your server cronjob may help this.
