### ISSUE TITLE
Not working anymore with Magento2 2.3.5

### ISSUE THREAD

**Issue by chequille** [mageplaza/magento-2-smtp#240]
Hi,
as Zend Framework is removed from Magento2 the extension is not working anymore.

Will there be an update?
Regards,
Jürgen

**Comment by Arthas7895** [comment]
I will check this module on Magento version 2.3.5 and inform you soon.
Thanks!

**Comment by chequille** [comment]
Hi, perfect.

I just tried replacing all Zend class references to Laminas and it is working again.
Done this in Mail.php, Transport.php and InstallShema.php

Best regards,
Jürgen

**Comment by anuprasadkummali** [comment]
on 2.3.5-p1  I installed today and was able to send mails using gmail SMTP. @chequille can you please share what all features are not working. Thanks

**Comment by chequille** [comment]
Hi, of course I can tell you, because it is simple. No sending of emails worked. As well the test on the configration pages, where I can send an email as test.

Fact its, that the extension is using Zend classes, right?
THese are replaced by Laminas classes.
When I simply renamed the occurance of Zend in your code to Laminas, everything worked as before.

Maybe for some circumstances the laminas-zendframework-bridge is working differently on different servers/configurations, but this is only a guess why it may should work on your site.

As Zend Framework is gone, your code should be changed anyway sometimes in the near future.

I do not have the error message anymore, but it was some error regarding a not existing Zend\Mail\Smpt class. Something like this,

Best regards,
Jürgen

**Comment by chequille** [comment]
"Fatal Error: 'Cannot declare class Zend_Mail_Transport_Smtp, because the name is already in use' in 'D:\\Web MagentoAktuell\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Smtp.php' on line 243"

This is the error message. Happens when I want to place an order.

**Comment by chequille** [comment]
Hi again,
I found the reason :-)
In my system, there was another modul for sending SMTP emails. It was deactivated in the config but it was still enabled in the whole system.
In Version 2.3.4, this was no problem and your module worked. Now in 2.3.5-p1 the error message occurs when sending mails.
I disabled the other module and now your module is working again without my modifications.

I hate this kind of errors !!!!!!!!!

Take care.
Best regards,
Jürgen

**Comment by KarlComSe** [comment]
@chequille How did you find that the module was still in use even though it was deactivated? What steps did you take to fix the issue?

**Comment by chequille** [comment]
@KarlComSe 
Hi,
first of all to understand is, that if a module is set to "not use it" in the backend config pages, it is still not disabled and all classes are loaded from Magento, even if it will never be used.

To find easely if a module is disabled or enabled, have a look into app/etc/config.php where all modules listed in an array.
F.e. 'Mageplaza_Smtp' => 1

Hope this answers your question.
Best regards,
Chequille

**Comment by chequille** [comment]
PS:
I disabled the module by setting the value in config.php to 0, but you can also run the command bin/magento module:disable Vender_Modulname

**Comment by Arthas7895** [comment]
Ok! We have finished testing and found that the module is working properly on Magento 2.3.5. so we will close this issue here. If you have any module issues, you can contact us here so we can discuss it together.
Thank you!
