### ISSUE TITLE
Warning: Illegal offset type in isset or empty in logs

### ISSUE THREAD

**Issue by ioannisgz** [mageplaza/magento-2-smtp#243]
Hi. My logs are full of the following error. Magento 2.3.4

report.CRITICAL: Warning: Illegal offset type in isset or empty in /vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 241 {"exception":"[object] (Exception(code: 0): Warning: Illegal offset type in isset or empty in /public_html/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 241 at /public_html/vendor/magento/framework/App/ErrorHandler.php:61)"}

Any help please?

**Comment by Arthas7895** [comment]
I tried on Magento 2.3.4 and everything is normal. I checked the code and found that the error code is that the module check is on, try reinstalling the module and try again

**Comment by Arthas7895** [comment]
Since I have not received any of your feedback in 7 days, I will close this issue here
Thank you very much!

**Comment by albertwong25** [comment]
Hi, the issue found in Magento 2.3.5 as well. It happened in cron job.

The line `isset($this->_moduleEnable[$storeId])` is using 2 variables, `$this->_moduleEnable` and `$storeId`, where
`$this->_moduleEnable` is an empty array []
`$storeId` is an empty object {}
error happened as empty object is used as array index

After tracing the code, `$storeId` is set in TransportBuilder `beforeSetTemplateOptions($subject, $templateOptions)`.
`$templateOptions` is `{"area":"adminhtml","store":{}}`
seem like the store is missing with area `adminhtml` in cron job.
