### ISSUE TITLE
Magento 2.3 SMTP Port 25 Authentication NONE

### ISSUE THREAD

**Issue by hdk** [mageplaza/magento-2-smtp#244]
The problem still exists in version 1.3.1 on Magento 2.3.3

Authentication "NONE" needs value 'smtp' to work

see https://github.com/mageplaza/magento-2-smtp/issues/176

**Comment by Arthas7895** [comment]
I pushed the code to the developer branch. We will release it in the next version.
Thanks!

**Comment by KeesvanR** [comment]
I have the same experience with magento 2.3.4. I changed the code and worked fine as suggested #176

**Comment by Arthas7895** [comment]
We have updated it in the develop branch and will apply it in the next version. 
Many thanks for your kind feedback

**Comment by Arthas7895** [comment]
Because the changes have been merged into the develop branch, I will close this issue here
Thank you very much!
