### ISSUE TITLE
Skip Webhook when URL is down

### ISSUE THREAD

**Issue by diyontheweb** [mageplaza/magento-2-smtp#245]
Hi guys,

Is it possible to have webhook be skipped if the web hook URL is not accessible.

Today we had a power outage at our webhook service URL, which meant when a new customer registers on the store - the webhook fails with error 'Cannot connect to server. Please try again later.' 

This then holds blocks the customer from being created in the database for 3 minutes. Which causes nginx to time out. 

When the webhook URL is down it should not block customer creation or order creation waiting for a timeout.

Thanks

**Comment by Arthas7895** [comment]
This is a forum of SMTP module, It seems you are confused about where the module discusses. You can find our webhook forum here
https://github.com/mageplaza/magento-2-webhook/issues
Thanks!

**Comment by diyontheweb** [comment]
Sorry about that!
