### ISSUE TITLE
Mirasvit Email follow up  mst_email_queue

### ISSUE THREAD

**Issue by khalidiazza** [mageplaza/magento-2-smtp#247]
Hello ,

I accidentally deleted this table from database : **mst_email_queue**, and since i'm trying to save my website i cannot do a restore for now. 

¨Please can anyone share with me the creation script for Magento 2.1.9. ?

Thank you

**Comment by dareenzo** [comment]
Mirasvit is a different module vendor from MagePlaza. Additionally, according to the setup scripts on this module it does not do anything regarding the table you mention. So perhaps you've opened the ticket on the wrong repo @khalidiazza ???

**Comment by khalidiazza** [comment]
> 
> 
> Mirasvit is a different module vendor from MagePlaza. Additionally, according to the setup scripts on this module it does not do anything regarding the table you mention. So perhaps you've opened the ticket on the wrong repo @khalidiazza ???

hi @dareenzo Sorry, i meant table SQL creation script. and thank you for pointing that i'm on the wrong repo.
