### ISSUE TITLE
webhook problem

### ISSUE THREAD

**Issue by Gabriel-Bruno** [mageplaza/magento-2-smtp#248]
Hello @haitv282 
hope you are doing well
while trying to checkout i got error:
https://www.awesomescreenshot.com/video/178360?key=d6fc5c97c65ccc44ee650e6fd066c7b3

after the checking the reason, i got this -> https://meetanshi.d.pr/fFD28a

would you assist

Best Regards,
Gabriel

**Comment by bdtrung** [comment]
Regarding your problem, it seems it's an issue from the Webhook module, not related to the Smtp module so please create a ticket for us at this [link](https://mageplaza.freshdesk.com/support/home).

Thanks!
