### ISSUE TITLE
Laminas\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for

### ISSUE THREAD

**Issue by agusfernandez** [mageplaza/magento-2-smtp#249]
Hi, iam having this issue for the smtp.gmail ( i already gave permissions on the account for testing) but it keeps appearing this problem "Laminas\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for". Can you guide me on what i should do to make it work?

thanks

**Comment by PascalBrouwers** [comment]
having the same issue @agusfernandez how did you fix it?

**Comment by agusfernandez** [comment]
hi @PascalBrouwers  to tel you the truth i dont remember but this can help you https://github.com/mageplaza/module-core/issues/3
