### ISSUE TITLE
Support for X-SMTPAPI header

### ISSUE THREAD

**Issue by marcejohnson** [mageplaza/magento-2-smtp#251]
Does `magento-2-smtp` module support populating the `X-SMTPAPI` header, directly or indirectly?

Sendgrid throttles at 100 per connection [documented here](https://sendgrid.com/wp-content/uploads/2016/09/SendGrid-Implementation-Review.pdf).

**However** extending SMTP with the `X-SMTPAPI` header increases the throttle limit by several orders of magnitude... which is significant.  See [details here](https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html#:~:text=You%20may%20send%20up%20to,connections%20from%20a%20single%20server)

Or if there is another workaround, or is this on the roadmap would also appreciate knowing.  Thanks!

-Marc

**Comment by HuyPhuc98** [comment]
The Smtp module does not support filling X-SMTPAPI headers.
Please contact the Mail server for assistance with your issue.
Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days. 
Have a nice day.
