### ISSUE TITLE
Email Log Preview is empty

### ISSUE THREAD

**Issue by vbidou** [mageplaza/magento-2-smtp#252]
Hello, 

I just installed the extension on a version of 2.3.2 of Magento
I tested few time the form Contact us of my website, and all is doing fine (the email is received by the visitor). Very good extension. Mine runs with Office 365.

But in the Email log tracker of the site, the preview remains empty.
Should I pay attention to something particular into the configuration ?
If this is abnormal, do you need any inputs to investigate the potential root cause?
I already purged the cache. No effect.

Also, by the way, the Email Logs does not show the email of the customer on the table, I think this should be added in order to enhance visibility (suggestion).

Thanks in advance,
Best regards,

**Comment by HuyPhuc98** [comment]
Can you tell me which version of the Smtp module you are using?

Your problem may be because your Smtp module is out of date.
Please update the module to the latest version.
You can download it here: https://github.com/mageplaza/magento-2-smtp

Thank you!

**Comment by vbidou** [comment]
Hello,
Thanks for your fast reply.
I installed yesterday the version 1.3.1 of the Extension.
Should I perform an update anyway?

**Comment by HuyPhuc98** [comment]
You do not need to perform the update because it is the latest version already.
Can you give a screenshot of mageplaza_smtp_log table information in your database?
Thank you!

**Comment by vbidou** [comment]
![mageplaza-smtp-log](https://user-images.githubusercontent.com/44623543/84801418-70127300-afff-11ea-9008-14e10942a45f.jpg)
Hope this is what you need.
Else let me know.

**Comment by HuyPhuc98** [comment]
Can you copy the "email_content" column information of an email to Notepad and take a screenshot to send me? https://prnt.sc/t1bltd
I want to see the full data of email_content.
Please also let me know which version of Magento you currently use.

Thank you!

**Comment by vbidou** [comment]
Hello, 

Here is the email content of the 1st id.
[email_content.txt](https://github.com/mageplaza/magento-2-smtp/files/4794733/email_content.txt)

I am using Magento 2.3.2 
Let me know if you need any other information. Thank you.
Best regards,

**Comment by HuyPhuc98** [comment]
Hi,

I have checked and found that email content is fine.
It's hard for me to check your issue here.
For the best support on your issue, please create a ticket at the following link: https://mageplaza.freshdesk.com/support/tickets/new

Thank you!

**Comment by vbidou** [comment]
Thank you.

I just noticed that Email preview is not only affecting the Magento_SMTP extension, but also the generic Magento one. I have the preview not responive as well and the issue is described in this ticket: https://github.com/magento/magento2/issues/23754
Therefore, I will first attempt to upgrade the magento version to the latest and will see if it resolves the problem. I will feedback the results.

Best regards,

**Comment by vbidou** [comment]
Hello,
I successfully migrated to Magento 2.3.5
My problem on standard email preview was resolved.
But the preview on the Magento_SMTP extension is still bugging (Blank page).
I just opened a service ticket on Mageplaza, in order to report the bug.
Thanks for your support.

**Comment by HuyPhuc98** [comment]
Since you created the ticket, I will close this issue here and solve your problem on our ticket system.

**Comment by soumyabratam6** [comment]
mageplaza_smtp_log table showing blank after send the mail even email log also blank
