### ISSUE TITLE
EMail Blank Body

### ISSUE THREAD

**Issue by grazianodimaio** [mageplaza/magento-2-smtp#253]
Hello!

I use this module on a Magento 2.3.1 install.

Suddenly, without touching anything the email are sent with a blank body.
i do not receive any error log in system log or others magento logs.

What it can be?

Thanks!

**Comment by HuyPhuc98** [comment]
Hi!

For your problem, you need to contact the Mail server so they can check this problem.
Smtp module only works to send requests to send mail to the Mail server.
You can check by turning off the Smtp module, and sending emails via default Magento || https://prnt.sc/t6o6un

Thank you!

**Comment by grazianodimaio** [comment]
Hi,

i'm not saying the extension is not working.
It worked very well until last week, then all the email started to send without body.

I activated the log of the email and all i see is a NULL write in the body.

I was wondering if you ever had this issue and how you fixed it.
It's driving me crazy

**Comment by HuyPhuc98** [comment]
Hi,

It's hard for me to check your issue here.
For the best support on your issue, please create a ticket at the following link: https://mageplaza.freshdesk.com/support/tickets/new

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days. If your problem persists, please let us know further detailed reports.
