### ISSUE TITLE
testemail.js is required from a different location to where it's generated by static content deploy

### ISSUE THREAD

**Issue by thisisandrew** [mageplaza/magento-2-smtp#254]
Magento 2.3.5-p1

Running php bin/magento setup:static-content:deploy --area=adminhtml will generate the testemail.js to `pub/static/adminhtml/Magento/backend/{locale}/Mageplaza_Smtp/js/testemail.js`

the admin view for system config requests the file from `static/version{deployed_version}/adminhtml/Magento/backend/{locale}/mageplaza/testemail.js` which 404s.

The apparent fix is to get the requirejs config right in the template.
```
<script type="text/x-magento-init">
    {
        "#smtp_configuration_option_test_email_to": {
            "mageplaza/testemail": {
                "ajaxUrl": "<?= $block->getButtonUrl() ?>"
            }
        }
    }
</script>
``` 

should be fixed to reference the file properly by the Vendor_Module convention

**Comment by HuyPhuc98** [comment]
Hi,

The testemail.js file has been defined in the requirejs-config.js file (Smtp/view/adminhtml/requirejs-config.js) and is called back in the button.phtml file (Smtp/view/adminhtml/templates/system/config/button.phtml)

When running the command deploy file testemail.js will be deployed.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days. If your problem persists, please let us know further detailed reports.
