### ISSUE TITLE
Error while sending test email

### ISSUE THREAD

**Issue by hernumber9** [mageplaza/magento-2-smtp#255]
Running 2.3.5-p1, just installed the extension via composer, and using gmail settings.  Clicked on the "Test Now" button and received the following:

![Screen Shot 2020-06-29 at 1 51 40 PM](https://user-images.githubusercontent.com/63079218/86039148-02f3da00-ba10-11ea-9726-201adfda6f96.png)

**Comment by HuyPhuc98** [comment]
Hi,

For your problem, you should set the value for the 'Authentication' field in the Smtp configuration to 'Login' https://prnt.sc/t8vrl0
We have fixed this bug on the latest version and will be released in the near future.

Thank you!

**Comment by hernumber9** [comment]
Ah, I missed that field. Thanks!

**Comment by wstnbrg** [comment]
@HuyPhuc98 is there an estimated date of delivery for the next version?
