### ISSUE TITLE
Smtp test email not working

### ISSUE THREAD

**Issue by suthar05october** [mageplaza/magento-2-smtp#256]
hi 

 try all the methods but test email showing technical error. Please try to help me

**Comment by HuyPhuc98** [comment]
Hi,

Can you describe more clearly the problem you are having?
A screenshot in this case helps me a lot.

Thank you!

**Comment by lecampos** [comment]
same error:

![image](https://user-images.githubusercontent.com/20343734/88129415-aebac080-cb9d-11ea-861a-9728e2d8c00c.png)

**Comment by HuyPhuc98** [comment]
Hi,

Could you please provide me some screenshots of Smtp configuration.
Thank you!

**Comment by moazzama** [comment]
hi,
can anyone help me to solve my "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." when we test email[
![error_in_smtp](https://user-images.githubusercontent.com/68050583/88644203-2166f700-d0dc-11ea-88c8-fecb4177c81f.png)
](url)

**Comment by HuyPhuc98** [comment]
Hi,

Firstly, make sure you have installed the latest version of Mageplaza Core module.
https://github.com/mageplaza/module-core/

Then from your Magento root directory, check your /var/log/exception.log or /var/log/system.log if there are any new error log. Also check /var/report if there are new record (file).

**Comment by moazzama** [comment]
error in exception.log file
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code:
0): Authentication failed
 at
/var/www/html/eshoppy_porto/app/code/Mageplaza/Smtp/Mail/Transport.php:141,
Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 0):
Authentication failed
 at
/var/www/html/eshoppy_porto/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:349)"}
[

**Comment by HuyPhuc98** [comment]
Hi.

Regarding your problem, you need to check the Smtp configuration (Username and Password), the configuration is currently incorrect, resulting in Authentication failed || https://prnt.sc/tq98e0

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed reports.

**Comment by rycogroup** [comment]
vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:349
hello, I have same issue
Can you help me to fix it?

Thank a lot

**Comment by moazzama** [comment]
i think First of fall update the module then that you enter the user name
and password that you are entering wrong that will be error show You Try a
Correct Credentials

**Comment by rycogroup** [comment]
Hi @moazzama 
I have update lastest module and enter Correct Credentials, but still not working
