### ISSUE TITLE
Cannot declare class Zend_Mail_Transport_Sendmail

### ISSUE THREAD

**Issue by m9iqbal** [mageplaza/magento-2-smtp#257]
I have an error while testing SMTP in backend.

```PHP Fatal error:  Cannot declare class Zend_Mail_Transport_Sendmail, because the name is already in use in vendor/magento/zendframework1/library/Zend/Mail/Transport/Sendmail.php on line 0" while reading response header from upstream```

Magento : 2.3.5-p1 version.
PHP : 7.3.x

**Comment by HuyPhuc98** [comment]
Hi,

It's hard for me to check your issue here.
For the best support on your issue, please create a ticket at the following link: https://mageplaza.freshdesk.com/support/tickets/new

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
