### ISSUE TITLE
smtp.office365.com cannot send mail

### ISSUE THREAD

**Issue by amuropao08** [mageplaza/magento-2-smtp#258]
We have use your extension for a long time and it's working good until last week. Every email show error status in email log. I'm not sure is Microsoft have change something or our client do something. How can I see the detail of the error. Below is current config (I also try to reload settings from the button again).

Host : smtp.office365.com
Port : 587
Protocal : TLS
Authentication : LOGIN

When I try to send test mail it show this error

5.7.3 Authentication unsuccessful [SG2PR06CA0186.apcprd06.prod.outlook.com]

**Comment by HuyPhuc98** [comment]
Hi,

As I noticed, this is a problem with your configuration information. Please check with the host provider.
In Magento 2, you can use dot-mailler to check configuration information(http://prntscr.com/mx5jra).

Also, you may refer to this guide:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_other-mso_o365b/smtpoffice365com-535-573-authentication/2e708a73-3340-4d24-b4e5-b97ff999dbae

Thank you!

**Comment by amuropao08** [comment]
Thank you for your reply. Our client has change config about SMTP right now all email already send out. Thanks
