### ISSUE TITLE
Send Test email button is not working

### ISSUE THREAD

**Issue by blob84** [mageplaza/magento-2-smtp#261]
### Preconditions (*)

1. magento 2.3.3
2. php 7.2.32

### Steps to reproduce (*)

1. Click on Test Now

### Expected result (*)

1. Email sent

### Actual result (*)

1. Nothing

**Comment by HuyPhuc98** [comment]
Hi,

Your problem is that there has been a successful email notification, but the email has not been sent?
Would you please provide me some screenshots of the Smtp configuration page.

Thank you!

**Comment by blob84** [comment]
The button did not worked. The email was not sent.
Now it works, I thing was a cache problem even if I've cleaned after the installation.
