### ISSUE TITLE
How to programmatically send mail via smtp?

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-smtp#262]
### Summary (*)
I have installed the module in 2.3.5-p1 and it works fine using the shop. 
I would like to send mails programmatically (customer import) but the SMTP in charge is rejecting me.

### Examples (*)

`/** @var $this->_transportBuilder \Magento\Framework\Mail\Template\TransportBuilder */
$transport = $this->_transportBuilder
->setTemplateIdentifier('my_custom_template_identifier')
->setTemplateOptions(
	['area' => \Magento\Framework\App\Area::AREA_FRONTEND, 'store' => $storeId]
)->setTemplateVars([]
)->setFrom(
	'from@example.com'
)->addTo(
	'to@example.com',
	'My example company'
)->getTransport()->sendMessage();`

I get the feeling the plugin does not automatically inject itself into the process. What am I missing here?

Thank you.

**Comment by HuyPhuc98** [comment]
Hi,

In this regard, you need to check whether the template "my_custom_template_identifier" has been declared or not.
If the template is already declared, you need to check the error in var/log and give me the screenshot of the error.

Thank you!

**Comment by OvalMedia** [comment]
Thank you and sorry. I messed up something else unrelated to your module.
