### ISSUE TITLE
Warning: Illegal offset type in isset or empty in logs

### ISSUE THREAD

**Issue by albertwong25** [mageplaza/magento-2-smtp#264]
Reopen for #243 Warning: Illegal offset type in isset or empty in logs

> I tried on Magento 2.3.4 and everything is normal. I checked the code and found that the error code is that the module check is on, try reinstalling the module and try again

Hi, the issue found in Magento 2.3.5 as well. It happened in cron job.

The line `isset($this->_moduleEnable[$storeId])` is using 2 variables, `$this->_moduleEnable` and `$storeId`, where
`$this->_moduleEnable` is an empty array []
`$storeId` is an empty object {}
error happened as empty object is used as array index

After tracing the code, `$storeId` is set in TransportBuilder `beforeSetTemplateOptions($subject, $templateOptions)`.
`$templateOptions` is `{"area":"adminhtml","store":{}}`
seem like the store is missing with area `adminhtml` in cron job.

_Originally posted by @albertwong25 in https://github.com/mageplaza/magento-2-smtp/issues/243#issuecomment-678104715_

**Comment by HuyPhuc98** [comment]
Hi,

I have checked and found that the Smtp module is working properly on Magento 2.3.5.
Would you please tell me which Smtp module version you are using and give me some screenshots of the error you are having.

Thank you!

**Comment by insiteful** [comment]
First: Thanks for the excellent module!

I'm not sure if I should start a new issue, but I'm also having this issue on Magento 2.3.4. Mageplaza 1.4.1.

Emails are being sent, but this is in our log:

`[2020-08-28 15:35:02] main.CRITICAL: Warning: Illegal offset type in isset or empty in /opt/bitnami/apache2/htdocs/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 240 {"exception":"[object] (Exception(code: 0): Warning: Illegal offset type in isset or empty in /opt/bitnami/apache2/htdocs/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 240 at /opt/bitnami/apache2/htdocs/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

Incidentally, we also can't access the Mageplaza configuration page (it's blank).

**Comment by albertwong25** [comment]
> Hi,
> 
> I have checked and found that the Smtp module is working properly on Magento 2.3.5.
> Would you please tell me which Smtp module version you are using and give me some screenshots of the error you are having.
> 
> Thank you!

Our module version is 1.4, which I think it is already up-to-date.
As I mentioned, the error happened when `$storeId` is an object, instead of a valid index of array. It is cause by another module which try to set templateOptions with `store = {}`.
Since Smtp is adding a plugin into Magento\Framework\Mail\Template\TransportBuilder in order to set `mp_smtp_store_id = templateOptions`, it causes the problem if the giving variable templateOptions is not a valid type for Smtp.
Apart from setting store to integer in the other module, Smtp can make a datatype checking before using the variable. If the datatype of the variable, say `store` in this case, is invalid, set it to default store id would be one of the solutions to solve the problem.

**Comment by HuyPhuc98** [comment]
Hi,

Thank you very much for your comments on the problem.
We will take note of this issue and examine it.

**Comment by hewgim** [comment]
We have exactly the same error message occuring when some cron process tries to send emails (other emails seem to get sent okay). I agree with @albertwong25. 

Mail/Template/TransportBuilder.php 


```
    public function beforeSetTemplateOptions(
        \Magento\Framework\Mail\Template\TransportBuilder $subject,
        $templateOptions
    ) {
        $this->registry->unregister('mp_smtp_store_id');
        if (array_key_exists('store', $templateOptions)) {
            $this->registry->register('mp_smtp_store_id', $templateOptions['store']);
        }

        return [$templateOptions];
    }
```

mp_smtp_store_id does not get set because the store array key does not exist in $templateOptions.

In Mail/Transport.php

```
     public function aroundSendMessage(
        TransportInterface $subject,
        Closure $proceed
    ) {
        $this->_storeId = $this->registry->registry('mp_smtp_store_id');
        $message        = $this->getMessage($subject);

        if ($this->resourceMail->isModuleEnable($this->_storeId) && $message) {
```

$this->_storeId is therefore never set and a null value is passed to $this->resourceMail->isModuleEnable()

**Comment by HuyPhuc98** [comment]
Hi,

Since your problem is related to the third module I cannot reproduce the problem on the local page.
You can refer to @albertwong25 way to solve the problem.

I will note this issue and check.
Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.

**Comment by tuyennn** [comment]
@albertwong25 same problem
