### ISSUE TITLE
facing issue on smtp request 

### ISSUE THREAD

**Issue by NTK-2016** [mageplaza/magento-2-smtp#271]
here is the error received in log   and backend we got the technical problem with server issue
[2020-10-01 14:31:30] main.CRITICAL: 5.7.0 (#AUTH005) Too many bad auth attempts.
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): 5.7.0 (#AUTH005) Too many bad auth attempts.
 at /var/www/vhosts/m4.eyedev.net/httpdocs/app/code/Mageplaza/Smtp/Mail/Transport.php:142, Zend\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): 5.7.0 (#AUTH005) Too many bad auth attempts.
 at /var/www/vhosts/m4.eyedev.net/httpdocs/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348)"}
![image](https://user-images.githubusercontent.com/24722367/94824604-d5f5ff80-0422-11eb-9a53-299ecc4d0d96.png)
![image](https://user-images.githubusercontent.com/24722367/94824817-09388e80-0423-11eb-98be-98e9daef27f2.png)

**Comment by HuyPhuc98** [comment]
Hi,

Your problem may be due to the incorrect configuration.
Would you please check your Smtp configuration and try again for me.

Thank you!

**Comment by NTK-2016** [comment]
Hi,

I have you got mail in Inbox because It is an issue occurred when we configure with gmail ,mail sent successfully sent but not received can you please check

**Comment by HuyPhuc98** [comment]
Hi,

Please double check you have disabled the fields in the configuration according to the following screenshot
https://prnt.sc/uvapkf || https://prnt.sc/uvarbd
If not then please disable it and try again for me.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days. If your problem persists, please let us know further detailed reports.

**Comment by NTK-2016** [comment]
hi @HuyPhuc98 ,
sorry for delay reply , it is a server issue which is resolved 
thnks
