### ISSUE TITLE
avada.io and other potentially illegal third-party providers should be removed or disabled

### ISSUE THREAD

**Issue by tehXor** [mageplaza/magento-2-smtp#272]
The extension adds third party scripts and stores third party information in the `localStorage` from at least `app.avada.io`. We noticed it during a compliance check from the legal department in a test environment. 

Obviously every third party addition should be configurable via the backend and an extended information about data privacy of all third party providers should be stated somewhere so that we who use this extension can add these information in our data privacy statements in case we do not disable them.

However with the recent annulment of Privacy Shield our legal department sees absolutely no way to include avada.io as EU based shop. So including it for us would be illegal regardless of our privacy statement, which makes the need to disable it even bigger.

Therefore it would be nice, if you could modify the extension in this direction. Otherwise I think the only way would be forking and modifying `view/frontend/templates/script.phtml` and possibly other code. Would you see any potential issues with that? And what purpose has avada in the first place in this extension?

**Comment by msyhr** [comment]
Super disappointing to see something like this, combined with the fact that the script is still injected if the marketing stuff is disabled in the back-end causing a bunch of script errors in the console. That could have been at least solved with a simple ifconfig="" on the block https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_block

 No accusations of nefarious intentions from me, but this will definitely steer me away from mp in the future.

**Comment by msyhr** [comment]
> Therefore it would be nice, if you could modify the extension in this direction. Otherwise I think the only way would be forking and modifying `view/frontend/templates/script.phtml` and possibly other code. Would you see any potential issues with that? And what purpose has avada in the first place in this extension?

Feel free to use this https://github.com/msyhr/mageplaza-smtp-remove-avada to get the block removed.

**Comment by tehXor** [comment]
> No accusations of nefarious intentions from me, but this will definitely steer me away from mp in the future.

I think we are all struggling with good privacy and being able to monetize our services and products. And nobody is happy about the annulment of Privacy Shield. Still some (more) consideration and sensitivity about this topic from all involved parties would be nice. And in this case it was/is a) hard to detect that you could run in a serious compliance issue but using this extension beforehand and b) you should think that by providing a good extension as open source you monetize by drawing customers to your paid extensions and not by collecting data (if this it what avada.io does - I actually don't know it). And we are actually currently considering some more mageplaza extensions in case we stick with Magento 2 for the project. However, if they all come with stuff like this I'm not so sure anymore 😏

In any case, that was kinda off topic but thanks for your great contribution @msyhr !

**Comment by imsamthomas** [comment]
Hi,

Thanks for your report.
The hotfix will be released officially soon. 
If you do not enable it, it will not be load in frontend.

It does not send any data to any services until you understand and enable, and set it up.

Regards,
Sam

**Comment by imsamthomas** [comment]
Hi @tehXor , @msyhr , @aeno 

We has released the hotfix:

- For Magento 2.3.x https://github.com/mageplaza/magento-2-smtp/releases/tag/v1.5.1
- For Magneto 2.4.x https://github.com/mageplaza/magento-2-smtp/releases/tag/v4.1.1

Have a great day!

Sam
