### ISSUE TITLE
Magento2 Smtp 4.1.1   minimum-stability dev

### ISSUE THREAD

**Issue by stkrelax** [mageplaza/magento-2-smtp#274]
### Preconditions (*)
1. Magento 2.3.5-p2
2. Project composer json minimum-stability of course stable with no intention to change that

### Steps to reproduce (*)
1. I want to install mageplaza/magento-2-social-login 
2. but here in magento-2-smtp the miminum stability is defined as dev

### Expected result (*)
1. make the module stable so i can install mageplaza/magento-2-social-login

### Actual result (*)
1. composer states that minimum stability requirements do not match
https://github.com/mageplaza/magento-2-smtp/blob/2b265972c20eba3dc3c63c192c4c0e4492ba2513/composer.json#L18

**Comment by HuyPhuc98** [comment]
Hi,

I tried to reproduce your problem, as a result, the module was installed successfully.
Would you please try reinstalling for me.

Thank you!

**Comment by stkrelax** [comment]
when magento project composer.json has "minimum-stability" set to "stable", than it is not possible to install

mageplaza/magento-2-social-login 4.0.0 via composer 

because smtp module has minimum-stability set to dev
