### ISSUE TITLE
Error Could not read from smtp-relay.gmail.com

### ISSUE THREAD

**Issue by danielpavey** [mageplaza/magento-2-smtp#275]
Keep getting this error when trying to send test email:

Error Could not read from smtp-relay.gmail.com

### Preconditions (*)

1. Magento ver. 2.3.5-p2
2. Magento 2 SMTP mail version 4.1.1

### Steps to reproduce (*)

1. Have configured admin as per instruction. Have tried switching ports and protocol but still receive same error message.

### Expected result (*)

1. Expect test email to send

### Actual result (*)

1. Test Email fails

![Screenshot 2020-10-16 at 09 17 32](https://user-images.githubusercontent.com/18568935/96233780-722a1580-0f90-11eb-9842-20f275097fa0.png)

**Comment by HuyPhuc98** [comment]
Hi,

Would you please provide me screenshots of your entire Smtp configuration.
Thank you!

**Comment by danielpavey** [comment]
Hi

Sure:

![Screenshot 2020-10-16 at 09 32 14](https://user-images.githubusercontent.com/18568935/96235296-853de500-0f92-11eb-8e47-0587d282d99b.png)

**Comment by HuyPhuc98** [comment]
Hi,

Are you using Gmail as a hosting provider?
If this is the case, then your configuration is incorrect.
Please configure the following screen shot || https://prnt.sc/v0fsej
"Useraname" is your Gmail account load.
"Password" is the password generated when you create two-step verification for your Gmail account through the following link:
https://support.google.com/accounts/answer/185833?hl=en

Thank you!

**Comment by danielpavey** [comment]
Hi

Thanks for your help.

Our company is a G-Suite / Google Apps customer.

We use smtp-relay.gmail.com in other places to to send email via our Google account.

Will smtp-relay.gmail.com not work with your module?

**Comment by HuyPhuc98** [comment]
Hi,

Our Smtp module does not support smtp-relay.gmail.com.
Hope sympathy.
Please use the configuration in the previous message to configure SMTP for your Gmail SMTP service provider, GSuite.

Thank you!

**Comment by danielpavey** [comment]
Ok

Thanks for your help 😄
