### ISSUE TITLE
admin user Retrieve Password can't send email ,but customer forgot password and place order it's ok

### ISSUE THREAD

**Issue by mattqiu** [mageplaza/magento-2-smtp#277]
admin user Retrieve Password can't send email ,but customer forgot password and place order it's ok,and test email in backend also ok,why?

**Comment by HuyPhuc98** [comment]
Hi,

I tested Retrieve Password admin user on the local site and found no problem.
Your problem is that the email was sent successfully but not received the email?

Please tell me.
Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> I tested Retrieve Password admin user on the local site and found no problem.
> Your problem is that the email was sent successfully but not received the email?
> 
> Please tell me.
> Thank you!

yes,it shows successed,but I didn't received any email

**Comment by HuyPhuc98** [comment]
Hi,

Please check if the email is in the spam box or not?
Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> Please check if the email is in the spam box or not?
> Thank you!

I already checked,nothing in it,and I try different email also can't receive

**Comment by HuyPhuc98** [comment]
Hi,

Would you please tell me how much module version Smtp and Magento you are using.
Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> Would you please tell me how much module version Smtp and Magento you are using.
> Thank you!

magento ver:2.3.4
smtp ver: 1.4.1

**Comment by HuyPhuc98** [comment]
Hi,

I tried the test on the local page, resulting in the email still being sent when I retrieve Password.
Would you please try another email address for me.

If the problem persists, you can refer to the following article to be able to change the Password by using the SQL command in database:https://www.mageplaza.com/kb/how-reset-admin-password-magento-2.html

Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> I tried the test on the local page, resulting in the email still being sent when I retrieve Password.
> Would you please try another email address for me.
> 
> If the problem persists, you can refer to the following article to be able to change the Password by using the SQL command in database:https://www.mageplaza.com/kb/how-reset-admin-password-magento-2.html
> 
> Thank you!

Thank you,I  want change the password by email.I tried qq email,hotmail,I can't received any email.

**Comment by mattqiu** [comment]
no solutions?

**Comment by HuyPhuc98** [comment]
Hi,

Please check your email log to see what status email forgot password is.
Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> Please check your email log to see what status email forgot password is.
> Thank you!

Already checked,just one success email

**Comment by HuyPhuc98** [comment]
Hi,

If the email status stating that the password is forgotten is successful, it is not our Smtp module.
You need to contact your Mail server so they can check it out for you.

Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> If the email status stating that the password is forgotten is successful, it is not our Smtp module.
> You need to contact your Mail server so they can check it out for you.
> 
> Thank you!

email log didn't have a subject about  password forgotten

**Comment by HuyPhuc98** [comment]
Hi,

Except the email notifying to change password is not sent, all the remaining emails have been sent successfully?
Please tell me.

Thank you!

**Comment by mattqiu** [comment]
> Hi,
> 
> Except the email notifying to change password is not sent, all the remaining emails have been sent successfully?
> Please tell me.
> 
> Thank you!

yes.I already tested

**Comment by HuyPhuc98** [comment]
Hi,

Please try to disable our module and try configuring with Dotmailer to be able to use Magento's default emailing function || https://prnt.sc/va0y54
Then try again and let me know the results.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
