### ISSUE TITLE
You know tell me if it works with sns from aws?

### ISSUE THREAD

**Issue by lucenarenato** [mageplaza/magento-2-smtp#278]

**Comment by HuyPhuc98** [comment]
Hi,

Our Smtp module provides complete support for Amazon SES service providers.
So you can configure Amazon SES to notify an Amazon SNS topic when you receive bounces or complaints, or when emails are delivered.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
