### ISSUE TITLE
Specified invalid parent id (Mageplaza_Core::menu) {"exception":"[object] (OutOfRangeException(code: 0):

### ISSUE THREAD

**Issue by sbwcws** [mageplaza/magento-2-smtp#28]
Here's the error I am getting when accessing Magento ADMIN

`[2017-11-26 13:18:27] main.CRITICAL: Specified invalid parent id (Mageplaza_Core::menu) {"exception":"[object] (OutOfRangeException(code: 0): Specified invalid parent id (Mageplaza_Core::menu) at /home/public_html/vendor/magento/module-backend/Model/Menu/Builder.php:83)"} []`

**I am using Magento 2.2.1 
Ubuntu 17.04 x64**

**Comment by sbwcws** [comment]
Your Line 83

`throw new \OutOfRangeException(sprintf('Specified invalid parent id (%s)', $parentId));`

Causing this issue.

**Comment by imsamthomas** [comment]
Hi,

You should install Mageplaza Core https://github.com/mageplaza/module-core

All Mageplaza modules require the Core module.

**Comment by sbwcws** [comment]
Working. Thanks
