### ISSUE TITLE
When we run setup:upgrade this issues arises

### ISSUE THREAD

**Issue by kshitipatel** [mageplaza/magento-2-smtp#280]
Stack trace:
#0 D:\Projects\wamp64\www\magento2\vendor\composer\ClassLoader.php(444): include()
#1 D:\Projects\wamp64\www\magento2\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\Projects\\wam...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Mageplaza\\Smtp\\...')
#3 D:\Projects\wamp64\www\magento2\app\code\Mageplaza\Smtp\Helper\EmailMarketing.php(55): spl_autoload_call('Mageplaza\\Smtp\\...')
#4 D:\Projects\wamp64\www\magento2\vendor\composer\ClassLoader.php(444): include('D:\\Projects\\wam...')
#5 D:\Projects\wamp64\www\magento2\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\Projects\\wam...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Mageplaza\\Smtp\\...')
#7 [internal function]: spl_autoload_call('Mageplaza\\Smtp\\...')
#8 D:\Projects\wamp64\www\magento2\vendor\mage in D:\Projects\wamp64\www\magento2\app\code\Mageplaza\Smtp\Helper\Data.php on line 33

**Comment by HuyPhuc98** [comment]
Hi,

The error you are experiencing is because you have not installed the Core module.
Please download it here and help me re-install: https://github.com/mageplaza/module-core

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
