### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by stevenlavine** [mageplaza/magento-2-smtp#281]
I have setup the extension using the following settings

![image](https://user-images.githubusercontent.com/910649/98096489-b881de80-1e83-11eb-8f8e-59ea55a503c1.png)

![image](https://user-images.githubusercontent.com/910649/98096583-d8190700-1e83-11eb-90a7-3d0ff8e1a550.png)

However whenever I send a test email, I get the email was successfully sent message, however no email is received and there is no entry in the Email Logs database table. If I use telnet the email sends correctly.

**Comment by HuyPhuc98** [comment]
Hi,

Please check for me if the Developer Mode field configuration and Magento's default emailing functionality is disabled.
https://prnt.sc/vd6ui6 || https://prnt.sc/vd6uzq || https://prnt.sc/vd6vdr
If not, please disable it and try again for me.

Thank you!

**Comment by stevenlavine** [comment]
> Hi,
> 
> Please check for me if the Developer Mode field configuration and Magento's default emailing functionality is disabled.
> https://prnt.sc/vd6ui6 || https://prnt.sc/vd6uzq || https://prnt.sc/vd6vdr
> If not, please disable it and try again for me.
> 
> Thank you!

Thank you! someone had set the disable email communications to "yes" set that to no and it all started working. Many thanks for your suggestions

**Comment by refueledinc** [comment]
@stevenlavine I see are using SendGrid, like we are. Just an FYI, SendGrid is not going to be supporting login authentication method soon and require everyone to use API authentication only. 

I believe MagePlaza needs to make changes to the module to support this new requirement.

**Comment by HuyPhuc98** [comment]
Hi,

I have checked and found that Sendgrid's upcoming v3 API upgrade will not affect the Smtp module, as the Smtp module uses Smtp credentials (username and password) to connect to the SendGrid.
You just need to switch authentication to the API is okay, do not use credentials with username and password anymore.

You can set up API information at this link:

https://sendgrid.com/docs/for-developers/sending-email/authentication/?fbclid=IwAR2fj_XA46NUF0nAhcBjlv-vHWI2eMtgiBBEkKR-WmW1np3M2T31LAo51fo#basic-authentication 

and can refer to the following video for more details:
https://www.youtube.com/watch?v=PEetQ55B9U4&t=212s&fbclid=IwAR3kQEJpJG2IpAQVZWjaWWfvn0WpBBw-M2hDdu0mJHrmeoMegWoSCB0u-KQ 

Thank you!

**Comment by Hadzim170398** [comment]
Can someone help me? I just install Magento 2.3.3 at localhost and I just install an extension SMTP from Mageplaza. I already configure the SMTP and google settings. I just enable a less secure app. When I try to test send an email it popup this error.


![image](https://user-images.githubusercontent.com/56250766/103327145-611c7b00-4a8e-11eb-90d8-52bee52a5910.png)

**Comment by HuyPhuc98** [comment]
Hi,

Please try to switch to Port 587 and Protocol TLS and try again.
Thank you!

**Comment by Hadzim170398** [comment]
I got this error when a change to TSL and port 587. 

![image](https://user-images.githubusercontent.com/56250766/103330830-30dcd880-4a9e-11eb-9961-47e80607228a.png)

**Comment by HuyPhuc98** [comment]
Hi,

Your problem is with your SSL certificate (your Port 465 may have been blocked).
You need to contact the Web server so they can check this out for you.

Thank you!

**Comment by Hadzim170398** [comment]
@HuyPhuc98 Thank you for helping. Thanks for the info.

**Comment by devrajram** [comment]
I am having issue sending any email out to customer and see the failed entry in Email log. When I click resend, it works fine. 
Test Email button works fine. I tried both SSL and TSL using LOGIN but same issue.

In the Magento (version: 2.3.7) log exception file i get below error:

[2021-08-13 03:41:54] main.CRITICAL: Incorrect authentication data
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Incorrect authentication data
 at /home/kapadala/r.kapadalay.com/vendor/mageplaza/module-smtp/Mail/Transport.php:141, Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): Incorrect authentication data
 at /home/kapadala/r.kapadalay.com/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:351)"} []

Any suggestion/help would be highly appreciated.


Thanks,
Dervaj

**Comment by atty31** [comment]
In my case I got the success message, but the email is not received in my inbox. Also in the grid it shows the success message. Any clue about this one ? 
Thanks
