### ISSUE TITLE
Mail not send - Failure "Unrecognized command"

### ISSUE THREAD

**Issue by anethum** [mageplaza/magento-2-smtp#282]
Magento Version 2.3.6
Mageplaza SMTP Version 1.5.2

After Upgrade of Magento to Version 2.3.6 and SMTP Version 1.5.2 
E-Mails doesn't send and collected in the Mail log with the status "Error".

If I try to use the Button "Test now" I get only the message "Unrecognized command"

in the expection.log if found following entry:

`[2020-11-04 15:23:01] main.CRITICAL: Unrecognized command
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unrecognized command
 at /var/www/html/vendor/mageplaza/module-smtp/Mail/Transport.php:142, Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): Unrecognized command
 at /var/www/html/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:358)"} []
`

If I use the "resend" button in the Email Log, I get following error "We can't process your request right now."

system.log
'[2020-11-04 15:25:21] main.CRITICAL: Unrecognized command
 [] []'

**Comment by HuyPhuc98** [comment]
Hi,

Would you please provide me a screenshot of your entire Smtp configuration.
Thank you!

**Comment by anethum** [comment]
![2020-11-04 18_41_45-Konfiguration _ Settings _ Stores _ Magento Admin - Seal Technology](https://user-images.githubusercontent.com/1729737/98151907-33251b00-1ed1-11eb-8781-6c66ba9baa9f.png)

![2020-11-04 19_07_55-Konfiguration _ Settings _ Stores _ Magento Admin - Seal Technology](https://user-images.githubusercontent.com/1729737/98151869-20aae180-1ed1-11eb-88a7-7a526d81dbf0.png)

![2020-11-04 19_12_03-Email Log _ SMTP _ Stores _ Magento Admin - Seal Technology](https://user-images.githubusercontent.com/1729737/98152381-eee64a80-1ed1-11eb-802d-f729f91ef3d5.png)

**Comment by HuyPhuc98** [comment]
Hi,

Could you please tell me which host provider you are using?
Thank you!

**Comment by anethum** [comment]
the host provider is normaly not the issue. The Mailserver is hosted by own.

with Magento 2.3.4 and SMTP Version 1.3.1 it works fine.

After Upgrade I get this error.

**Comment by HuyPhuc98** [comment]
Hi,

Would you please provide me Smtp configuration information so I can reproduce the problem and test it on the local page.
Thank you!

**Comment by anethum** [comment]
![2020-11-09 15_40_45-Window](https://user-images.githubusercontent.com/1729737/98555236-fb87eb80-22a1-11eb-9bc0-592ecdbef394.png)

Please find the attached smtp configuration

**Comment by HuyPhuc98** [comment]
Hi,

Can you provide me a configuration password?
So I can reproduce your problem.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
