### ISSUE TITLE
main.js:37 Error: Script error for: mageplaza/testemail

### ISSUE THREAD

**Issue by dearste** [mageplaza/magento-2-smtp#284]
Get this error: main.js:37 Error: Script error for: mageplaza/testemail

All command done before.

**Comment by HuyPhuc98** [comment]
Hi,

Would you please describe more clearly the problem you are having for me.
What version of Magento and Smtp module are you using?
How to reproduce your problem like?

Please tell me.
Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
