### ISSUE TITLE
 main.CRITICAL: Authentication Failed

### ISSUE THREAD

**Issue by syberbg** [mageplaza/magento-2-smtp#289]
magento 2.4
mageplaza smtp  Version | 4.1.2

Authentication Failed 
I double check login details.But result is Authentication Failed  on send test mail
![image](https://user-images.githubusercontent.com/71674132/99661925-3db4e800-2a6d-11eb-8846-b49acf5dd16b.png)
 
{"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Authentication Failed
 at /var/www/html/venige/vendor/mageplaza/module-smtp/Mail/Transport.php:142, Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): Authentication Failed  at /var/www/html/venige/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:351)"} []

**Comment by HuyPhuc98** [comment]
Hi,

The error you get is because your configuration account is not authenticated.
Please verify the configuration account at your hosting provider (Zoho) and try again for me.

Thank you!

**Comment by syberbg** [comment]
I forget to say, that everifing work whith magento 2.3.p1. I do not change zoho configuration.
![image](https://user-images.githubusercontent.com/71674132/99772182-f97c2300-2b12-11eb-9f0a-0959a02bf004.png)

zoho options
![image](https://user-images.githubusercontent.com/71674132/99772293-2a5c5800-2b13-11eb-9177-a045e63c4a89.png)

**Comment by HuyPhuc98** [comment]
Hi,

I tried configuring the Smtp module with host provide Zoho on the local site and I also got an "Authentication Failed" error || https://prnt.sc/vmngj4
The reason is that the account is configured incorrectly or it is not authenticated.

Would you please check your configuration account and try again for me.
Thank you!

**Comment by syberbg** [comment]
everything is fine with another email client with the same passwords running OK.But from market don`t work.
I think problem is in magento module

**Comment by HuyPhuc98** [comment]
Hi,

In order to correctly configure the Smtp module with your Zoho hosting provider, you need to create a Zoho account and authenticate it.
Then use that account to configure the Username and Password fields.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.

**Comment by mohitthakur02** [comment]
I'm not use zoho. I'm use gmail smtp to solve this issue but is still here so what can i do have an idea please suggest.This error is coming on after placeorder in magento 2.


2 exception(s):
Exception #0 (Magento\Framework\Exception\MailException): Authentication Failed

Exception #1 (Laminas\Mail\Protocol\Exception\RuntimeException): Authentication Failed


Exception #0 (Magento\Framework\Exception\MailException): Authentication Failed
