### ISSUE TITLE
BCC of order mail not sent when customers mail address is incorrect

### ISSUE THREAD

**Issue by wyrix** [mageplaza/magento-2-smtp#29]
If the customer adds a non existing mail address in the order, the mail could not be sent to the customer (ofcourse). But if you enabled the option to send a BCC of the order mail to yourself (I don't have the english version of Magento, but it should be called something like 'Send a copy to'), this mail is not sent too. In these cases, we're not notified there's a new order.

**Comment by gixid192** [comment]
Hi Wyrix,

Could you take a picture of that setting in Magento? (in your language).
We also need the Magento version that you are using.

Thank you.

**Comment by wyrix** [comment]
Hi gixid192,

See the red bordered option in the file attached;
![send-copy-to](https://user-images.githubusercontent.com/34075598/33394455-b097d144-d542-11e7-8717-fadd25aa28a3.png)

We are using version 2.2.1 of Magento.

**Comment by imsamthomas** [comment]
Duplicated #32

**Comment by gixid192** [comment]
Please remove the trailing space after the comma, as suggested in the comment, it is comma-separated so the input should be `email1@host.com,email2@host.com` NOT `email1@host.com, email2@host.com`

**Comment by rikwijnen** [comment]
It is not a duplicate of #32. #32 is about having multiple mail addresses in the field. This issue is about the mail is not send when the customers mail address is invalid or does not exist. It should however send the mail to the CC address, no matter if the customers mail address exists/is valid or not.
