### ISSUE TITLE
Hi. Test Now Button is not working. i'm in magento 2.4 smtp 4.1.3.

### ISSUE THREAD

**Issue by NguyenvanLuc06081994** [mageplaza/magento-2-smtp#291]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by HuyPhuc98** [comment]
Hi,

I reproduced your problem on the local page, as a result the Smtp module still works fine.
Would you please check back for me.
If the error persists, please provide a screenshot of the error for me.

Thank you!

**Comment by NguyenvanLuc06081994** [comment]
thank you for your support. it's working. thank you very much.

**Comment by HuyPhuc98** [comment]
Hi,

Since there are no more problems I will close the issue for now.
Thank you!
