### ISSUE TITLE
SMTP configuration settings are not displayed in Admin

### ISSUE THREAD

**Issue by bhatti-dhara** [mageplaza/magento-2-smtp#292]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. After installing Mageplaza_Smtp extension, go to Admin > Stores > Settings > Configuration

### Expected result (*)

1. As per [documentation](https://docs.mageplaza.com/smtp-m2/?_ga=2.86642968.1017490211.1609333491-37334544.1609136198), it should display **Smtp** configuration settings in admin. 

### Actual result (*)

1. Currently, **Social Login** configuration tab is displaying instead of **Smtp**, as shown in following screenshot.

![Screenshot-from-2020-12-31-11-26-43-png-1920×1080-](https://user-images.githubusercontent.com/17154042/103397031-66e09200-4b5c-11eb-91a6-35326c345656.png)

There is etc/adminhtml/system.xml file is for **Social Login extension**. It should be for **Smtp extension**. Please let me know once it done.

**Comment by HuyPhuc98** [comment]
Hi,

There is a bit of confusion about the system.xml file of the Smtp module on Github.
Would you please download the Smtp module here and install it again for me.
https://drive.google.com/file/d/1jIaM17w5mNcYL-0GGyGAxHEe0Lv32YRO/view?usp=sharing

Thank you!

**Comment by bhatti-dhara** [comment]
Thanks for the updates.

I have replaced module with new one. Now I'm facing some error like "This extension is not actived." as shown in following screenshot:

![Screenshot from 2020-12-31 13-08-17](https://user-images.githubusercontent.com/17154042/103400065-bed1c580-4b69-11eb-90cf-9786c057e01e.png)

Please let me know information should I require to activate the extension.

**Comment by HuyPhuc98** [comment]
Hi,

Please check if the Core module version is the latest version 1.4.9.
If not, please update it to the latest version for me.
You can download it here: https://github.com/mageplaza/module-core/tree/v1.4.9

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
