### ISSUE TITLE
Emails not sent - SSL operation failed

### ISSUE THREAD

**Issue by MajorKuprich** [mageplaza/magento-2-smtp#293]
Hello,

Magento version 2.3.6
Mageplaza Smtp version 4.1.3

No email are sent.
I've try to send test emails via admin but still no success.

Authentication failed error, despite of correct credentials (tested with diffrent mail accounts, providers).

Full error stacktrace:
```
{"status":false,"content":"5.7.1 Authentication failed\r\n"}<br />
<b>Fatal error</b>: Uncaught Exception: Warning: fwrite(): SSL operation failed with code 1.
OpenSSL Error messages:
error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown in
/home/virtual/app/www/vendor/laminas/laminas-mail/src/
Protocol/AbstractProtocol.php on line 263 in
/home/virtual/app/www/vendor/magento/framework/App/
ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler-&gt;handler(2, 'fwrite(): SSL o...',
'/home/virtual/s...', 263, Array)
#1 /home/virtual/app/www/vendor/laminas/laminas-mail/src/
Protocol/AbstractProtocol.php(263): fwrite(Resource id #1685, 'QUIT\r\n')
#2 /home/virtual/app/www/vendor/laminas/laminas-mail/src/
Protocol/Smtp.php(399): Laminas\Mail\Protocol\AbstractProtocol-&gt;_send('QUIT')
#3 /home/virtual/app/www/vendor/laminas/laminas-mail/src/
Protocol/Smtp.php(439): Laminas\Mail\Protocol\Smtp-&gt;quit() in
<b>/home/virtual/app/www/vendor/magento/framework/App/
ErrorHandler.php</b> on line <b>61</b><br />
```

**Comment by HuyPhuc98** [comment]
Hi,

Would you please provide me the screenshot of the Smtp module configuration.
Thank you!

**Comment by MajorKuprich** [comment]
Hello,

I've also tried with TLS protocol but no difference.

![smtp config](https://i.imgur.com/vuCvuFs.png)

**Comment by HuyPhuc98** [comment]
Hi,

Would you please check to help me configure Dotmailer to send email by default Magento is disabled? || https://prnt.sc/wkmp51
If not please disable it for me.

Thank you!

**Comment by MajorKuprich** [comment]
Hello,

It is disabled by default.

![](https://i.imgur.com/TTuf96W.png)

**Comment by HuyPhuc98** [comment]
Hi,

Please try to change Post to 587 and Protocol to TLS then try again for me.
If the error still persists, please send me the screenshot of the error.

Thank you!

**Comment by MajorKuprich** [comment]
Sorry for late reply,

Error popup:

![](https://i.imgur.com/Vz4XYeJ.png)

TLS config:

![](https://i.imgur.com/oyNzhT7.png)

**Comment by HuyPhuc98** [comment]
Hi,

In this regard, you need to allow less secure apps.
If still not works try changing the password for Gmail

You can refer to the following article: 
https://stackoverflow.com/questions/34433459/gmail-returns-534-5-7-14-please-log-in-via-your-web-browser/34433953

Thank you!

**Comment by MajorKuprich** [comment]
Less secure apps enabled https://www.google.com/settings/security/lesssecureapps

![](https://i.imgur.com/ruQEj5C.png)

Captcha unlocked https://accounts.google.com/DisplayUnlockCaptcha

![](https://i.imgur.com/XdMrr3V.png)

**But only after password changes mail send working fine.**
Thank You for help, I think We can close this topic.

**Comment by HuyPhuc98** [comment]
Hi,
Since the problem has been resolved, I will close this for now.
