### ISSUE TITLE
Avada syntax error

### ISSUE THREAD

**Issue by atty31** [mageplaza/magento-2-smtp#295]
Hi,
I am running version 4.2.1 of the mageplaza/module-smtp module on Magento 2.4.1. I don't have any customization of the theme or such and on every page I receive in the console this JS error:
`Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    onreadystatechange https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    s https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    s https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    e https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    l https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    _invoke https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    h https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    p https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    e https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    l https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    _invoke https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    h https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    p https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    e https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    l https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    _invoke https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    h https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    p https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    e https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    l https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    _invoke https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    h https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    p https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    e https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    l https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    _invoke https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    h https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    p https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    exports https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    <anonymous> https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    <anonymous> https://app.avada.io/scripttag/popup/avada-popup.min.js:6
    a https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    <anonymous> https://app.avada.io/scripttag/popup/avada-popup.min.js:1
    <anonymous> https://app.avada.io/scripttag/popup/avada-popup.min.js:1`

from line `avada-popup.min.js:6:191825` . The js library is loaded from `vendor/mageplaza/module-smtp/view/frontend/templates/script.phtml`. Any idea how to fix this ? Thank you

**Comment by HuyPhuc98** [comment]
Hi,

Has your problem been resolved?
If not, you can fix the problem by disabling the Email Marketing function in the SMTP module configuration if you do not use that function || https://prnt.sc/10nv5lk

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
