### ISSUE TITLE
Composer 2 problem

### ISSUE THREAD

**Issue by sugosol** [mageplaza/magento-2-smtp#298]
### Preconditions (*)

1. Magento 2.4.2
2. Mageplaza/module-smtp 4.3.2
3. Composer 2.0.11

### Steps to reproduce (*)
"composer update"

### Expected result (*)

"Nothing to install or update"

### Actual result (*)

Problem 1
    - Root composer.json requires mageplaza/module-smtp ^4.1, it is satisfiable by mageplaza/module-smtp[4.1.0, ..., 4.3.2] from composer repo (https://repo.packagist.org) but mageplaza/module-smtp[1.0.6, ..., 1.5.2] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by HuyPhuc98** [comment]
Hi,

Are you trying to update the SMTP module via composer?
Please tell me your current SMTP module version?

Thank you!

**Comment by sugosol** [comment]
Hi, smtp is latest version. I'm trying to update composer from 1 to 2.
I noted that with composer 1 installed, if I call "composer update" -> "Nothing to install or update"
with composer 2 installed I get the error above

**Comment by HuyPhuc98** [comment]
Your Composer version is currently 2.0.11 and the Smtp module version is also the most recent.
Can you tell me what you're trying to do with the composer?

Thank you!

**Comment by sugosol** [comment]
My composer version is 1.10, If I update to 2, I get the error above.

**Comment by HuyPhuc98** [comment]
The command you ran to upgrade the composer was incorrect.
Please refer to the following article to be able to update the composer:
https://getcomposer.org/doc/03-cli.md#:~:text=To%20update%20Composer%20itself%20to,phar%20with%20the%20latest%20version.&text=If%20Composer%20was%20not%20installed,this%20command%20is%20not%20available.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.

**Comment by magemaclean** [comment]
I am also getting this same error. New installation on Magento 2.4.2 with composer 2.

Using version ^4.1 for mageplaza/magento-2-social-login
./composer.json has been updated
Running composer update mageplaza/magento-2-social-login --with-all-dependencies
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
```
  Problem 1
    - mageplaza/magento-2-social-login[4.1.0, ..., 4.1.2] require mageplaza/module-smtp ^4.0.0 -> satisfiable by mageplaza/module-smtp[4.0.0, ..., 4.3.2] from composer repo (https://repo.packagist.org) but mageplaza/module-smtp[1.0.6, ..., 1.7.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
    - Root composer.json requires mageplaza/magento-2-social-login ^4.1 -> satisfiable by mageplaza/magento-2-social-login[4.1.0, 4.1.2].
```

**Comment by borde91** [comment]
confirmed issue, got exact same issues when trying to run composer update with composer 2.x it only works witrh complser 1.x
Please fix the issue

Here is the error:

Your requirements could not be resolved to an installable set of packages.

  ```
Problem 1
    - Root composer.json requires mageplaza/module-delete-orders ^1.2, it is satisfiable by mageplaza/module-delete-orders[1.2.0, 1.2.1] from composer repo (https://repo.packagist.org) but mageplaza/module-delete-orders[1.1.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - Root composer.json requires mageplaza/module-smtp ^4.3, it is satisfiable by mageplaza/module-smtp[4.3.0, 4.3.1, 4.3.2, 4.4.0] from composer repo (https://repo.packagist.org) but mageplaza/module-smtp[1.0.6, 1.1.3, 1.2.0, 1.2.9, 1.4.0, 1.4.1, 1.4.3, 1.5.2, 1.7.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
```

**Comment by kxip-wb** [comment]
Current version of module (4.5.2) is support to composer version 2.1.5 ?

**Comment by asannikov** [comment]
since composer2 has canonical flag as true by default, now repo.magento.com has more priority than packagist. Composer 1 had false by default. Find more info here: https://getcomposer.org/doc/articles/repository-priorities.md

Just set canonical to false:
```
 "0": {
            "type": "composer",
            "url": "https://repo.magento.com/",
            "canonical": false
        },
```

it's not recommended by composer to use non-caconical repos, as it goes slower and more insecure. But you are doing that only for repo.magento.com, which looks pretty secure so far:)

**Comment by savan13** [comment]
# @

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
