### ISSUE TITLE
Email link not correct for reset password, The link is working in the email logs 

### ISSUE THREAD

**Issue by TechMartLLC** [mageplaza/magento-2-smtp#299]
I have configured mageplaza SMTP extension. The emails are working but the links within them is not working. I have checked the links in Email logs and they are working when I view them but once they delivered they don't work. Is there anything that I need to update or configure properly. Any help would be greatly appreciated.

**Comment by HuyPhuc98** [comment]
Hi,

Can you provide me a screenshot showing the problem and some screenshots of your problem?
Thank you!

**Comment by TechMartLLC** [comment]
What I have found is the link in emails logs is pointing to https://stage.companyname.com (which is a the valid address and link). When they system sends the email to the customer he/she received a different link that is pointing to http://email.companyname.com (Which doesn't exit and gives 404 error). I think this is a configuration issue and I am having trouble on figuring out where to fix this address.

**Comment by HuyPhuc98** [comment]
For this, please check the "Password Options" configuration in Stores-> Customers-> Customer Configuration || https://prnt.sc/11735bq
Thank you!

**Comment by TechMartLLC** [comment]
I have checked the "Password Options" configuration in Stores-> Customers-> Customer Configuration as you suggested and previewed the default template. It is working within the Magento System but when the email goes to the user email, the link changed. Something is happening during the sending of email from Magneto System. Is there any where I need to check the some domain specific settings or mail server settings. Any help would be appreciated. 
![Default Template for Reset Password](https://user-images.githubusercontent.com/73844338/114058893-7822f400-9859-11eb-96e8-033362400ea8.PNG)

**Comment by HuyPhuc98** [comment]
There is no way to configure a specific domain for forgot Password emails.
It is identified in the Forgot Password template.

You can change the mail server in the Smtp module configuration || https://prnt.sc/117yq2x
Try another mail server and try again for me.

**Comment by TechMartLLC** [comment]
I have changed the mail server in the SMTP module as you had advised but same error. I do not think this is an SMTP issue but at least we have tried it. This link is being updated somehow in the email as the value of some variables changes. Any other ideas that I can try.
![SMTP Setting after](https://user-images.githubusercontent.com/73844338/114184206-2d14e980-990a-11eb-98f9-7b0710bd4587.PNG)

**Comment by HuyPhuc98** [comment]
Hi,

That Right, this problem is not caused by the Smtp module.
You should check the email related modules you are using, most likely it affected the Forgot Password email template.
Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
