### ISSUE TITLE
acl error

### ISSUE THREAD

**Issue by woakley** [mageplaza/magento-2-smtp#30]
On setup:upgrade

Invalid Document
Element 'resource': The attribute 'title' is required but missing.
Line: 34

I believe this is referring to the acl.xml

**Comment by haitv282** [comment]
Hi,

I am so sorry for late response.
Regarding your problem, please install our Core module first by `composer require mageplaza/module-core`.
Or simply clone it [here](https://github.com/mageplaza/module-core)
Thank you very much.
