### ISSUE TITLE
Mensagem de email enviado com sucesso, porém o email não é enviado.

### ISSUE THREAD

**Issue by daniloaldm** [mageplaza/magento-2-smtp#301]
### Preconditions (*)
Magento version 2.4.1 (Community)

### Steps to reproduce (*)
1. Configure SMTP outgoing emails
2. Try to send the test email

### Expected outcome (*)
1. E-mail reaches the sender

### Current results (*)
1. A message appears that the email was sent successfully, however, the email was not sent. (checked for spam, among other things)

Configs:
![image](https://user-images.githubusercontent.com/38409136/115297823-08ebb080-a133-11eb-8ca2-2f01ea6ff332.png) 
![image](https://user-images.githubusercontent.com/38409136/115297783-fc675800-a132-11eb-8df6-3797f9e3eccf.png)

**Comment by HuyPhuc98** [comment]
Hi,

In this regard, please check the configuration 'Mail Sending Settings' (Stores-> Configuration-> Advanced-> System) and 'DDG Transactional' (Stores-> Configuration-> Engagement Cloud-> Transactional-> Emails ) has been turned off yet || https://prnt.sc/11q5ei8 || https://prnt.sc/11q5fca
If not, please turn them off for me.
At the same time, you need to check that the Smtp module configuration is correct.

Hope this can be of help to you.
Thank you!

**Comment by daniloaldm** [comment]
Hi, this worked for me, thanks!
