### ISSUE TITLE
Sales email not showing total block 

### ISSUE THREAD

**Issue by liquidia** [mageplaza/magento-2-smtp#302]
### Preconditions (*)

1.Magento version 2.3.3
2. Module version 1.5.2
### Steps to reproduce (*)

1. Install module via composer and use google smtp 
2. Email sent by extensions does not show total block (subtotal, shipping, tax and grand total)

### Expected result (*)

Expected result
https://ibb.co/RyY2DVT

### Actual result (*)
Actual result 

https://ibb.co/GQbTwjZ

**Comment by HuyPhuc98** [comment]
Hi,

I have seen you create a ticket for this issue at our customer support system.
Please follow ticket #112231.
Thank you!
