### ISSUE TITLE
Installation dependencies not met using Composer 2 and Magento 2.4.2

### ISSUE THREAD

**Issue by magemaclean** [mageplaza/magento-2-smtp#303]
### Preconditions (*)

1. Magento 2.4.2
2. Composer 2

### Steps to reproduce (*)

Installed via composer method: 
1. Install mageplaza/module-core
2. Install mageplaza/module-smtp 
3. Install mageplaza/magento-2-social-login

### Expected result (*)

1. Installation success

### Actual result (*)

Using version ^4.1 for mageplaza/magento-2-social-login
./composer.json has been updated
Running composer update mageplaza/magento-2-social-login --with-all-dependencies
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
```
  Problem 1
    - mageplaza/magento-2-social-login[4.1.0, ..., 4.1.2] require mageplaza/module-smtp ^4.0.0 -> satisfiable by mageplaza/module-smtp[4.0.0, ..., 4.3.2] from composer repo (https://repo.packagist.org) but mageplaza/module-smtp[1.0.6, ..., 1.7.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
    - Root composer.json requires mageplaza/magento-2-social-login ^4.1 -> satisfiable by mageplaza/magento-2-social-login[4.1.0, 4.1.2].
```

**Comment by HuyPhuc98** [comment]
Hi,

Your problem may be because the required module version is not satisfied.
To solve this problem you should install the modules manually by installing the modules in the directory 'app/code/Mageplaza', then running the command setup and deploy.

Before that, you need to delete all the modules in the 'vendor/mageplaza' directory and run the command 'composer dump-autoload'.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days.
