### ISSUE TITLE
Test email not working due to 404 on js file

### ISSUE THREAD

**Issue by svlauer** [mageplaza/magento-2-smtp#304]
### Preconditions (*)

1. Magento version: 2.2.9 in production mode.
2. Module version: 4.3.2

### Steps to reproduce (*)

1. Install as normal, run compile- and deploy steps, refresh cache.
2. Fill in server details, click test-email-button.

### Expected result (*)

1. A test email is sent, the UI gives feedback.

### Actual result (*)

1. Nothing happens.
2. In the console, I see that there is a 404 response for `pub/static/adminhtml/Magento/backend/de_DE/mageplaza/testemail.js`
  (de_DE is the correct language code)
3. In `pub/static/adminhtml/Magento/backend/de_DE`, there only is a `Magento_Smtp` folder, no `magento` folder.

Otherwise, the module works fine, settings are saved and emails are being sent via SMTP.

On Magento 2.3.6 in developer mode, test email sending works.

**Comment by HuyPhuc98** [comment]
Hi,

This problem may be because the js file has not been loaded. You can replace the following code || https://prnt.sc/pqwvs2 in where to install SMTP module/view/adminhtml/templates/system/config/ button.phtml
Then flush the cache and try again. 
This is the code 'Mageplaza_Smtp/js/testemail'.

Thank you!

**Comment by svlauer** [comment]
Ah, I had found that file (by grepping for the missing file name), but did not want to play around without knowing what I am doing (esp. since the module is working as intended).

After replacing that code, test email sending works as intended.

**Comment by HuyPhuc98** [comment]
Hi,

Since the issue has been resolved I will close this issue for now.
Thank you!
