### ISSUE TITLE
Content Security Policy Issue

### ISSUE THREAD

**Issue by alexsmith2709** [mageplaza/magento-2-smtp#305]
### Preconditions (*)
1. Magento 2.4.2
2. Mageplaza SMTP Version 4.3.2

### Steps to reproduce (*)
1. Click on "Marketing" > "Newsletter" or any option under "Email Marketing"

### Expected result (*)
1. Corect admin pages to load

### Actual result (*)
1. Error on page due to Content Secuirty Policy blocking avada.io
![newsletter1](https://user-images.githubusercontent.com/10212208/120209105-304f9600-c226-11eb-931f-f0c7cfdc1380.JPG)
![newsletter2](https://user-images.githubusercontent.com/10212208/120209121-334a8680-c226-11eb-889e-4febf5d5cde9.JPG)

I dont want avada.io to load, i dont need it. Marketing Automation module is disabled yet this still tries to load. *.avada.io is only in the csp whitelist for script-src, not frame-src but i dont see why i should have to add it when it is disabled and i dont want anything to do with avada.

**Comment by HuyPhuc98** [comment]
Hi,

To fix your problem, please download the file 'csp_whitelist.xml' at the following link:
https://drive.google.com/file/d/1OiLz8P1A77GUJAcRzHFTFRjBeXSGO4XT/view?usp=sharing
Then replace that file in 'Mageplaza/Smtp/etc/csp_whitelist.xml' folder and try again for me.

You can refer to the following article for more details: 
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html

Thank you!

**Comment by alexsmith2709** [comment]
I am aware how to fix it, but why is avada.io trying to load scripts when marketing automation is turned off?
