### ISSUE TITLE
Mailgun not working

### ISSUE THREAD

**Issue by asrenzo** [mageplaza/magento-2-smtp#31]
Hi,
Installed your extension on Magento 2.1.10 this morning and I'm unable to send a test email from backoffice. I always get "5.7.0 Mailgun is not loving your login or password"
I know my credentials to be the right ones cause I'm able to send emails from the same machine using swaks.

Moreover some stange infos in logs :

#0 vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp/Auth/Login.php(95): Zend_Mail_Protocol_Abstract->_expect(Array)
#1 vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php(217): Zend_Mail_Protocol_Smtp_Auth_Login->auth()
#2 vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php(200): Zend_Mail_Protocol_Smtp->helo('localhost')
#3 vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#4 vendor/magento/zendframework1/library/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
vendor/mageplaza/module-smtp/Controller/Adminhtml/Index/Index.php(125): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))

Why do I have helo('localhost') ???

Mageplaza smtp is enabled and configured as required in documentation.

Any idea ?

Regards

**Comment by haitv282** [comment]
Hi there,

Regarding your problem, it seems that the problem caused by the Mailgun configuration. Please read how to configure it [here](https://www.mageplaza.com/blog/how-to-configure-mailgun-smtp-in-magento-2.html).
Please check again and let us know the result.
Thank you very much.

Regards,
Mageplaza Team
