### ISSUE TITLE
Custom Module email sending fails (standard Magento emails send fine)

### ISSUE THREAD

**Issue by MisterH001** [mageplaza/magento-2-smtp#310]
### Summary (*)

I have created a custom module that sends an email in an observer (customer_register_success). It fails to send if SMTP module is enabled (using Magento TransportBuilder)

### Examples (*)

Observer:
          try
          {
             $error = false;

             $sender = [
                'name' => $this->_escaper->escapeHtml($customer->getFirstName()),
                'email' => $this->_escaper->escapeHtml($customer->getEmail()),
             ];
             $templateVars = [
                'firstname' => $customer->getFirstName(),
                'lastname' => $customer->getLastName(),
                'email' => $customer->getEmail()];
             $postObject = new \Magento\Framework\DataObject();
             $postObject->setData($sender);
             $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
             $transport =
             $this->_transportBuilder
             ->setTemplateIdentifier('new_registration_email_template') // Send the ID of Email template which is created in Admin panel
             ->setTemplateOptions(
                ['area' => \Magento\Framework\App\Area::AREA_FRONTEND, // using frontend area to get the template file
                'store' => \Magento\Store\Model\Store::DEFAULT_STORE_ID,]
             )
             ->setTemplateVars($templateVars)
             ->setFrom($sender)
             ->addTo('me@myemail.com')
             ->getTransport();
             $transport->sendMessage(); ;
             $this->inlineTranslation->resume();

          }
          catch (\Exception $e)
          {
          \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug($e->getMessage());
          }

**Comment by HuyPhuc98** [comment]
Hi,

Your problem may be that the custom module and the Smtp module are not compatible with each other.
You should only use a single module to send emails.
Thank you!

**Comment by HuyPhuc98** [comment]
To send email via the SMTP module, you just need to configure the SMTP module to connect to your hosting provider || https://prnt.sc/166xel2
Thank you!

**Comment by MisterH001** [comment]
Thank you.
It is configured correctly within Magento. But when myself (or 3rd party module devs) use the code detailed above to send emails, (core magento code) no emails are sent. (core transactional emails are sent correctly though).
Thanks
Mark

**Comment by HuyPhuc98** [comment]
For the Smtp module to work at its best, you should disable other modules related to emailing (except the core module).
Because if there is the impact of the third module, it will lead to the processing of sending email errors.
Thank you!

**Comment by MisterH001** [comment]
Thank you but I don't think you quite understand me though.
The module I've created isn't related to emailing. It does lots of things and at the end needs to send a notification email to the store admin but when your module is enabled it fails to send (doesn't even show in the Mageplaza SMTP logs.
The code I am using to send the email is listed above. It looks like your module overrides the default Magento way of sending an email.

**Comment by MisterH001** [comment]
Hi. Just to update.
I have resolved this. Nothing wrong with your module (it's great!)
There was a 3rd party conflict on the event I was using.
thanks for your time.
