### ISSUE TITLE
problems when using composer 2 

### ISSUE THREAD

**Issue by borde91** [mageplaza/magento-2-smtp#313]
### Preconditions (*)

1. Magento 2.4.2
2. Mageplaza/module-smtp 4.4.0
3. Composer 2

### Steps to reproduce (*)

1. execute the command: composer update
### Expected result (*)

1.Command executes without issues

### Actual result (*)
1. This error appears:
Your requirements could not be resolved to an installable set of packages.

Problem 1
  - Root composer.json requires mageplaza/module-delete-orders ^1.2, it is satisfiable by mageplaza/module-delete-orders[1.2.0, 1.2.1] from composer repo (https://repo.packagist.org) but mageplaza/module-delete-orders[1.1.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
Problem 2
  - Root composer.json requires mageplaza/module-smtp ^4.3, it is satisfiable by mageplaza/module-smtp[4.3.0, 4.3.1, 4.3.2, 4.4.0] from composer repo (https://repo.packagist.org) but mageplaza/module-smtp[1.0.6, 1.1.3, 1.2.0, 1.2.9, 1.4.0, 1.4.1, 1.4.3, 1.5.2, 1.7.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

The error does not occur when using composer 1. Many other modules from other vendors are installed but only the one from mageplaza is giving the error.

**Comment by HuyPhuc98** [comment]
Hi,

If you get an error while installing the module with composer 2, you can install the SMTP module manually.
First, you need to install the SMTP module in the app/code/Mageplaza directory, then run the setup and deploy commands to activate the module.

Thank you!

**Comment by davidwindell** [comment]
@borde91 you can work around this by forcing composer to use the version from Packagist using exclude like so:

```
"magento": {
            "type": "composer",
            "url": "https://repo.magento.com/",
            "exclude": ["mageplaza/module-smtp"]
        },
```

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
