### ISSUE TITLE
BCC of order mail not sent when customers mail address is incorrect

### ISSUE THREAD

**Issue by sreichel** [mageplaza/magento-2-smtp#317]
### Preconditions (*)

1. Magento 2.3.5-p1
2. SMTP 4.2.1

### Steps to reproduce (*)

Same as #29

1. > If the customer adds a non existing mail address in the order, the mail could not be sent to the customer (ofcourse). But if you enabled the option to send a BCC of the order mail to yourself (I don't have the english version of Magento, but it should be called something like 'Send a copy to'), this mail is not sent too. In these cases, we're not notified there's a new order.

### Expected result (*)

1. bcc/copy is sent
2.

### Actual result (*)

1. bcc/copy is not sent

**Comment by HuyPhuc98** [comment]
Hi,

I will test this on my local site and let you know when the testing is over.
Thank you!

**Comment by HuyPhuc98** [comment]
I have reproduced the problem on the local site and the result is that the email is still successfully sent to the email address that does not exist in the email log, and the copy email is still sent to the BCC address || https://i.imgur.com/VH7dICk.png || https://prnt.sc/180biq8

With the email address existing, does your problem appear?
Thank you!

**Comment by sreichel** [comment]
![ksnip_20210702-121225](https://user-images.githubusercontent.com/5022236/124259476-d6950100-db2e-11eb-8bbb-16ca789f5e25.png)

1) valid customer email ... copy is sent to info@xyz (same for bcc)
2) invalid email ... there is no copy/bcc. The copy does not appear in logs and is not sent.
