### ISSUE TITLE
Adding multiple emails, comma seperated to send as BCC breaks sending

### ISSUE THREAD

**Issue by squishz** [mageplaza/magento-2-smtp#32]
As title states, when adding multiple emails to any of the order emails it will break the email being send. I have attached a screenshot example bellow:

![screen shot 2017-12-13 at 16 59 15](https://user-images.githubusercontent.com/17438260/33951517-16ad74a4-e027-11e7-897e-443aa64b85df.png)

**Comment by imsamthomas** [comment]
Same with #29

**Comment by gixid192** [comment]
Please remove the trailing space after the comma, as suggested in the comment, it is comma-separated so the input should be `email1@host.com,email2@host.com` NOT `email1@host.com, email2@host.com`

**Comment by gixid192** [comment]
Close due to no response within 7 days.
