### ISSUE TITLE
Guest Checkout Issue

### ISSUE THREAD

**Issue by magecaptain** [mageplaza/magento-2-smtp#326]
### Preconditions (*)

1. Magento Version: 2.3.2
2. SMTP Extension version 1.9.1

### Steps to reproduce (*)

When I try to place an order through Guest it shows an error, but the order was placed successfully and and also get email to that email which I have used at checkout time. 

1. Guest Checkout
2. Placed Order

### Expected result (*)

1. After Order Placed Email Send to User
2. Order Created Successfully
3. And Success page open

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/83595985/127736265-6c60ade2-49ee-40eb-93c9-8c5e5174f737.png)
checkout process stops at this point and shows an error in the console for this API

2. at checkout step 2(payment page) it shows the following error message:
Something went wrong with your request. Please try again later.

3) when trying to reload the page, it redirects to the empty cart page.

**Comment by HuyPhuc98** [comment]
Hi,

Please check the SMTP module configuration and send a test email to see if it works.
If there is an error, please provide me with a screenshot.

Thank you!

**Comment by magecaptain** [comment]
Hi,Thanks for your response, That test email is success and not any issue. Also email also sending correct but when doing order with guest checkout and with limepay creditcard method we are getting error but actually order is placed and email sent to customer. At frontend page it show error that try again and customer trying again and actually order are capturing as duplicate when trying again. In inspect we have checked and we getting error in payment information call and error is like as below"749"<br /><b>Fatal error</b>:  Uncaught Zend\Mail\Protocol\Exception\RuntimeException: Could not read from email-smtp.ap-southeast-2.amazonaws.com in /srv/www/current/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:306Stack trace:#0 /srv/www/current/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php(335): Zend\Mail\Protocol\AbstractProtocol-&gt;_receive(300)#1 /srv/www/current/vendor/zendframework/zend-mail/src/Protocol/Smtp.php(390): Zend\Mail\Protocol\AbstractProtocol-&gt;_expect(Array, 300)#2 /srv/www/current/vendor/zendframework/zend-mail/src/Protocol/Smtp.php(429): Zend\Mail\Protocol\Smtp-&gt;quit()#3 /srv/www/current/vendor/zendframework/zend-mail/src/Protocol/Smtp.php(417): Zend\Mail\Protocol\Smtp-&gt;_disconnect()#4 /srv/www/current/vendor/zendframework/zend-mail/src/Transport/Smtp.php(187): Zend\Mail\Protocol\Smtp-&gt;disconnect()#5 [internal function]: Zend\Mail\Transport\Smtp-&gt;__destruct()#6 {main}  thrown in <b>/srv/www/current/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php</b> on line <b>306</b><br />Looking for solutions of this issue.Thanks,Alpesh---- On Sat, 31 Jul 2021 22:31:59 +0530  ***@***.******@***.***> wrote ---- 
Hi, 
Please check the SMTP module configuration and send a test email to see if it works. 
If there is an error, please provide me with a screenshot. 
Thank you!

**Comment by HuyPhuc98** [comment]
Hi,

You only get an error with the limepay credit card payment method.
Have you tried other payment methods?
Please tell me,
Thank you!

**Comment by magecaptain** [comment]
Hello,

We have also tried other payment gateway like Braintree
but still, it shows the same error for guest checkout.

when we disable the SMTP extension and then tried to checkout as a guest, the order was placed successfully.

looking for quick response as this is breaking site and many customer doing duplicate order.

Thanks

**Comment by HuyPhuc98** [comment]
Please try with default Magento payment methods.
Because as you said, the order is still placed successfully and the email is still sent to the customer.
I am concerned that the problem is due to the compatibility between the SMTP module and the payment methods is faulty.

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days
