### ISSUE TITLE
Not receiving transaction emails

### ISSUE THREAD

**Issue by Rockfordgun** [mageplaza/magento-2-smtp#33]
Hi there 

I installed the mageplaza smtp plugin cause i cant get mails through cron jobs.
I installed your plugin and setup was done fairly quick.
I ran a test via your test button and i receive those mails with no issues.
But when i try and buy a new product the client and myself are not receiving any of the emails can you maybe help me out.

**Comment by gixid192** [comment]
I received your ticket and also replied to you. Since github is open source, I will paste my response here

Our extensions built on top of Magent's Core.
So if your magento cannot send/receive emails, it cannot work with our extensions.

Please resolve the issues with your Core magento first.

**Comment by Rockfordgun** [comment]
Yeah i got your response thx i got my issue narrowed down. I went into the magento cron logs. Looks like i have some errors on the crontab.php file. How do i recreate this file r where can i download it again?

**Comment by gixid192** [comment]
This is github and we only serve the problems related to the current topic.
Please reply in your ticket in our ticket system.
