### ISSUE TITLE
Sendgrid : Authentication failed: Bad username / password 

### ISSUE THREAD

**Issue by benchew1234** [mageplaza/magento-2-smtp#334]
![smtp](https://user-images.githubusercontent.com/68327682/132152823-657378d0-d773-4064-a9f0-a8a535d554f4.png)

Hi , I tried put sendgrid API key ID as username & API key as password . But I received this authentication error in my magento exception.log.  Any solution that I can refer to fix? Thanks

**Comment by HuyPhuc98** [comment]
Hi,

To configure the SMTP module with Sendgrid, you need to generate an API key for your SendGrid account.
Then configure the 'Username' field to be 'apikey', and the 'Password' field to be the API key you just created || https://prnt.sc/1rd1424

Thank you!

**Comment by benchew1234** [comment]
Thanks! Its working.
