### ISSUE TITLE
aws ses api implementation

### ISSUE THREAD

**Issue by onlinebizsoft** [mageplaza/magento-2-smtp#338]
Since SMTP interface is not stable, the API interface would be much better for AWS ses

**Comment by HuyPhuc98** [comment]
Hi,

Can you describe your feature request more clearly?
A few screenshots describing the problem would help me a lot.
Thank you!

**Comment by onlinebizsoft** [comment]
@HuyPhuc98 please see here https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-api.html

**Comment by onlinebizsoft** [comment]
As you can see the SMTP interface get many issues (timeout, connection,.....), it is not stable as API interface
