### ISSUE TITLE
MAGEPLAZA - Magento 2 SMTP - AWS Ses configuration

### ISSUE THREAD

**Issue by sergiobelli** [mageplaza/magento-2-smtp#34]
Hi all, 
we are trying to configure this plugin to send email by AWS SES service.

We are find some issues when we try to send a test email.

Is the plugin current working for AWS SES?

How can I configure it?

thanks
Sergio

**Comment by gixid192** [comment]
You just need to input the pair of keys as user and password.
You also need to verify your email before you can work with SMTP (in general not just our extension).
![img](https://user-images.githubusercontent.com/8438046/32215548-d6d897bc-be54-11e7-82dd-5cf3a3f84a77.png)

You can replace your email with your current Sales Emails to test the extension.

**Comment by sergiobelli** [comment]
Thank you, we found solution...
There are to set protocol to TLS in order to make configuration working

**Comment by miro91** [comment]
@sergiobelli can you give me more details where to set the protocol to TLS

**Comment by gixid192** [comment]
Hi @miro91 
It is in our extension setting ![img](https://content.screencast.com/users/Lovemagic/folders/Jing/media/8f18112e-4e3a-4cab-b959-4402fc2a35ec/2018-02-28_0830.png)
