### ISSUE TITLE
Using same preference causes error

### ISSUE THREAD

**Issue by chequille** [mageplaza/magento-2-smtp#37]
Hi,
as I am using in my module as well the following preference

<preference for="\Magento\Framework\Mail\Template\TransportBuilder"
                type="JscDesign\Attachment\Model\Email\TransportBuilder"/>

of course this causing problems, because your TransportBuilder Class does not have my function to attach pdf files to an email.

I added my function to your TransportBuilder.php and it works again as it should, but this is just a workaround.

Do you have any idea how this can be handled when two extensions using the same preference in di.xml?

Please let me know.

BR Jürgen

**Comment by gixid192** [comment]
We just released the new version v1.1.3. This version removed the "same preference" issue.

**Comment by gixid192** [comment]
Close due to no response within 7 days.
