### ISSUE TITLE
PHP 8.1 - Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by chriswatt** [mageplaza/magento-2-smtp#377]
![image](https://user-images.githubusercontent.com/488912/172139580-7b744fe2-2a84-4521-8d71-345fd763bd3d.png)

https://github.com/mageplaza/magento-2-smtp/blob/e7e0d63649b05b0a4335108472b7a8a16e544094/Helper/EmailMarketing.php#L541

SMTP: 1.4.12 / Magento 2.4.4 / PHP 8.1

As a temporary solution, I modified the line 541~ to read

```php
$customerName = $quote->getCustomerEmail() ? explode('@', $quote->getCustomerEmail())[0] : '';
```

**Comment by KhietNguyen83** [comment]
Thank you for your interest in our SMTP extension.
We will review and update the bug according to your suggestion in the next version.
Thank you very much!
Thank you!

**Comment by MTheProgrammer** [comment]
This is still reproducible on add to cart, before customer begins the checkout process
