### ISSUE TITLE
Mailgun - From address issue

### ISSUE THREAD

**Issue by configzone** [mageplaza/magento-2-smtp#38]
Hi there, 

Seems after configuring with mailgun it's using default login id as sender email in mailgun, that suppose to be store email address. Mailgun recon to use subdomain during domain setup in the account in order to send from root email address. 

Right now all emails sending from subdomain email address. Also if you send email from the admin then its use sender name from main store if you are using multistore. that lead wrong sender name.

Does anyone have an idea how to resolve it?

Thanks

**Comment by gixid192** [comment]
We don't have any issues with Mailgun.

I supposed you are using the latest code? Could you provide your Magento version and the steps to reproduce the issue?

**Comment by gixid192** [comment]
Close due to no response in a week.
