### ISSUE TITLE
Test email sent but not the transactional emails

### ISSUE THREAD

**Issue by wirepaq** [mageplaza/magento-2-smtp#39]
I think I am doing something wrong since I tried another smtp plugin and it had same issue. Test emails are sent fine but the transactional emails are not. I have the cron set up. Executed the cron manually from cli as well but no success.

**Comment by gixid192** [comment]
If so then there is something with your store, it's not about the email but about the transaction flow.
Since it is not about our extension, I'm going to close this from here.

Hope you will find solutions for your store soon.
