### ISSUE TITLE
Magento 2.4.5 p1 Enterprise edition compatible check

### ISSUE THREAD

**Issue by antony-eglobeits** [mageplaza/magento-2-smtp#392]
### Description (*)

Hi,
  One of our clients is using the SMTP Magento module ( version 
  1.2.0 ) and looking to upgrade the  "Magento 2.3.1
   Enterprise Edition  " to " 2.4.5-p1 Enterprise Edition  ".  so, kindly 
  let us know the compatibility of the above module with "Magento 2.4.5-p1
   Enterprise Edition ".

### Additional information

If not compatible, Do you Guys have any plan to 
release/develop a new version of the above module.
Please let us know.

**Comment by KhietNguyen83** [comment]
Hi @antony-eglobeits ,
Thank you for your interest in Mageplaza extensions.
We are in the process of testing the compa with magento 2.4.5p1.
You can still install it on your magento, if there is any problem, contact us, we will solve it for you.
Thank you very much!
