### ISSUE TITLE
Magento version upgrade form V2.3.5 version to V2.4.5-p1 and email not triggering

### ISSUE THREAD

**Issue by diamondzacx** [mageplaza/magento-2-smtp#393]
### Preconditions (*)

Magento version upgrade form V2.3.5 version to V2.4.5-p1 on our environment with nginx and php-fpm (php ver 8.1) and Mageplaza extension version 1.2.5

### Steps to reproduce (*)

Facing an issue while connecting SMTP (https://github.com/mageplaza/magento-2-smtp) over the TLS/ SSL with "smtp.office365.com" and getting below error while throwing test email.  The feature is provided by Mageplaza extension.

### Expected result (*)

Should get success message, while sending a test email

### Actual result (*)

1. [Screenshots]
![image](https://user-images.githubusercontent.com/16942728/205610022-f6af4be6-fd28-4665-a817-87606304a964.png)

**Comment by KhietNguyen83** [comment]
Thank you for your interest in the Mageplaza SMTP extension.
Please try using port 587, TLS protocol.
If the problem persists, it may be due to the SSL certificate, Please contact your Web server to check.
Thank you very much!

**Comment by diamondzacx** [comment]
Thanks for your response, it worked, hence closing the issue.
