### ISSUE TITLE
issue when load log email in magento version 2.2

### ISSUE THREAD

**Issue by tomnyson** [mageplaza/magento-2-smtp#40]
http://prntscr.com/hyei7q

**Comment by gixid192** [comment]
Please help us try again with Incognito/Private mode in your browsers to avoid conflicts in browsers' addon/extensions.
Thank you.

**Comment by tomnyson** [comment]
what do you mean?

**Comment by gixid192** [comment]
I mean you can try again with Anonymous mode (Ctrl+Shift+N) to try again.
Thank you.

**Comment by gixid192** [comment]
Close due to no reply in 7 days.
