### ISSUE TITLE
can't active module with email correct on magento 2.1.9

### ISSUE THREAD

**Issue by tomnyson** [mageplaza/magento-2-smtp#41]
http://prntscr.com/hyek3u

**Comment by gixid192** [comment]
Could you try again with different email and name please?
Thank you.

**Comment by tomnyson** [comment]
I already reregister new user.but it still how empty message.

**Comment by gixid192** [comment]
Please send us your store address, name and email that you used.
Thank you.

**Comment by tomnyson** [comment]
https://ww.vmax.vn
user: tomnyson
tabletkindfire@gmail.com

**Comment by tomnyson** [comment]
let check please 👍

**Comment by gixid192** [comment]
Could you try again please?
Thank you.

**Comment by gixid192** [comment]
Close due to no reply in 7 days.
