### ISSUE TITLE
test email sent ok, 5.7.8 Error: authentication failed: UGFzc3dvcmQ6 after saving configurations

### ISSUE THREAD

**Issue by stone-ly** [mageplaza/magento-2-smtp#42]
Hello team,

Thanks for the extension - I installed it via composer very smoothly. However each time after testing and saving configurations I will get this error:
5.7.8 Error: authentication failed: UGFzc3dvcmQ6

Testing emails sent fine. Saving configurations and get error. Re-type password and testing fine. Saving configuration and get error... Seemed the password changes after saving configuration? (the *** gets one or two digits longer after saving)

I am on Magento 2.2.2. Appreciate your time and reply.

Thanks
Stone

**Comment by gixid192** [comment]
Close due to created tickets in our system.
