### ISSUE TITLE
Invalid from email when testing email on settings page 

### ISSUE THREAD

**Issue by crtl** [mageplaza/magento-2-smtp#44]
Hello,
ive tried to enter my credentials for the SMTP settings in the admin panel.
Because I use an Amazon AWS SMTP Relay I do not have any email address to log in with, instead I just have a username.
I can save the Username and all my credentials but I dont have any opportunity to test my email because it says the sender email is invalid.

**Comment by gixid192** [comment]
Hi,

Amazon requires whitelist the sender email. Could you check it once again?
![image](https://user-images.githubusercontent.com/8438046/35544427-d77dcda6-059c-11e8-82d5-3e618fa6d1da.png)

**Comment by gixid192** [comment]
Close due to 7 days without responding.
