### ISSUE TITLE
Get error when install the extension

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-smtp#45]
When I run the command  setup:di:compile I got this error

Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/html/magento2/app/code/Mageplaza/Smtp/Helper/Data.php on line 30

Help Please.

**Comment by gixid192** [comment]
You can follow our user guide here to install Core module https://www.mageplaza.com/install-magento-2-extension/

It starts from `Step 4: Run command line`

**Comment by msliman** [comment]
Thank you for your reply. I need to download the extension folder and install it, not via composer.
How do it ?

**Comment by gixid192** [comment]
You can get the Core module from here: https://github.com/mageplaza/module-core

**Comment by msliman** [comment]
Thank you, it is working fine.

**Comment by gixid192** [comment]
Great I could help. I will close the issue from here.

**Comment by gixid192** [comment]
@manojramtarento This is the repo for Smtp issue, you are asking about Layered Navigation extension.
You can post your question in our ticket system here: https://www.mageplaza.com/contact.html
