### ISSUE TITLE
Email sent header problem

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-smtp#46]
When an email sent, the header is username which I set in the extension configuration. how can I make headers be the real email which I set in Owner, Sales, Customer support ?

**Comment by gixid192** [comment]
It depends on your smtp service, we tested with Google and some others, they always take login information as Sender Email.
For the record, I can remember Mailgun and Mandrill always follow Magento's settings.

**Comment by msliman** [comment]
That is right, I tried MailGun and it is working fine .
