### ISSUE TITLE
how can i activate

### ISSUE THREAD

**Issue by taiprasert1** [mageplaza/magento-2-smtp#47]
![capture](https://user-images.githubusercontent.com/35983947/35604274-17a80068-0674-11e8-82b6-94ccaee5f13c.JPG)

**Comment by datvm1** [comment]
Hi,

You can enter your name and your commonly used email there. It will register your email on our system and activate all free extensions from Mageplaza for your email. Also you will be subcribed to receive updates and news about our extensions.
After registering, you can change the email anytime. Just hit the Update this license button, and this form will re-appear.

**Comment by taiprasert1** [comment]
it a Mageplaza Account right? 

i enter  Mageplaza Account it say " empty response"

**Comment by gixid192** [comment]
Close due to created a ticket in ticket system.
