### ISSUE TITLE
最新的版本有bug

### ISSUE THREAD

**Issue by huichen2017** [mageplaza/magento-2-smtp#48]
最新的版本有bug
选择none后（将none改为空了），但是验证会失败，报5.7.8 Error: authentication failed: authentication failure错误！！

**Comment by gixid192** [comment]
Hi,
At the moment, the extension doesn't support "None" as protocol yet. We will update this feature in next release.

请您用英语写字。

**Comment by huichen2017** [comment]
ok, thank you

**Comment by gixid192** [comment]
Since there is no issue left, I will close this issue from here.

**Comment by huichen2017** [comment]
I mean version 1.1.2 does not support ssl is empty, but version 1.0.2 is supported

**Comment by gixid192** [comment]
Thanks for your information.
We are checking the extension with all Protocol, we will release new version as soon as we finish the check.

**Comment by huichen2017** [comment]
OK, I'm looking forward to it
