### ISSUE TITLE
Install without composer on magento 2

### ISSUE THREAD

**Issue by NoSGR** [mageplaza/magento-2-smtp#49]
Hello,

is there any guide to install the module without composer in magento 2?

Everytime i try to install it through composer, i get this error: 

composer require mageplaza/module-smtp the command stopped at: Using version ^1.1 for mageplaza/module-smtp ./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev) Nothing to install or update Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead. Generating autoload files

and then composer & website become broken untill i restore a backup.

**Comment by datvm1** [comment]
Hello,

I'm not sure if you have composer setup wrong somehow. You can download our SMTP extension and install it directly, by visiting the link below.
https://github.com/mageplaza/magento-2-smtp/archive/master.zip
Also, it requires our Core module. You can download it here:
https://github.com/mageplaza/module-core/archive/master.zip

**Comment by NoSGR** [comment]
Hello,

do you have any instructions about installation without composer? I have just to upload the files?

Thanks in advance

**Comment by datvm1** [comment]
Hello,

You can paste the content of those .zip files from links above into app/code/Mageplaza.
https://prnt.sc/ia9ywj
Rename the folders to Core and Smtp.
Then run upgrade and deploy commands like installing usual modules.

**Comment by gixid192** [comment]
Close due to no responses within 7 days.
