### ISSUE TITLE
Authentication method CRAM-MD5 throws include error

### ISSUE THREAD

**Issue by C4rter** [mageplaza/magento-2-smtp#54]
When you choose CRAM-MD5 the following error is thrown when testing the mail send:

Warning: include_once(Zend/Mail/Protocol/Smtp/Auth/Cram-md5.php): failed to open stream: No such file or directory.

I think the reason is the naming of the value. The value is "cram-md5" but when looking at the Zend File it has to be "crammd5". When I change it, the error is not thrown anymore.

I changed it in the source model:
app\code\Mageplaza\Smtp\Model\Config\Source\Authentication.php

**Comment by gixid192** [comment]
Thanks for your report, we will fix it soon.

**Comment by gixid192** [comment]
Hi @C4rter, I updated this in the dev branch, if you have any comment in the code, please let me know here, otherwise, kindly help us close the issue.
Thank you.

**Comment by C4rter** [comment]
@gixid192 Looking good. Thanks.
