### ISSUE TITLE
When selecting no "Protocol" the error "is unsupported SSL type" in thrown.

### ISSUE THREAD

**Issue by C4rter** [mageplaza/magento-2-smtp#55]
When you select "None" in the protocol config, an error is thrown when sending store emails. The test email is working. But store emails such as the email that's being sent when adding a new order comment throws the error "is unsupported SSL type".

The issue happens because the SMTP Procol Class from Zend needs an SSL type when the SSL config element is set. But the SMTP Extension sets an empty string when choosing "none".

See "__construct" here: vendor\magento\zendframework1\library\Zend\Mail\Protocol\Smtp.php
And "getTransport" here: app\code\Mageplaza\Smtp\Mail\Rse\Mail.php

The "ssl" element shouldn't be set empty, it has to be omitted entirely when set to "none".

**Comment by gixid192** [comment]
Hi @C4rter, I updated this in the dev branch, if you have any comment in the code, please let me know here, otherwise, kindly help us close the issue.
Thank you.

**Comment by C4rter** [comment]
@gixid192 Looking good. Thanks.

**Comment by neerajgupta98** [comment]
Hello @C4rter 
I also face same this error can you please help how can you solve this error
