### ISSUE TITLE
Email logs SMTP - Base table or view not found

### ISSUE THREAD

**Issue by foxmasters** [mageplaza/magento-2-smtp#57]
Ehe email logs panel displays error:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ecommerce.mageplaza_smtp_log' doesn't exist, query was: SELECT COUNT(*) FROM `mageplaza_smtp_log` AS `main_table`

**My System**

1. Magento 2.2.2
2. PHP 7.0
3. Mysql 5.7.21

**Modulo**

1.Mageplaza_smtp v.1.1.3

**DataBase Table setup_module**

2. Mageplaza_Smtp  schema_version  1.1.0          
3. Mageplaza_smtp data_version 1.1.0

Probably the next function was not installed, but I do not know how to run that part of the code

> public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
>     {
>         $installer = $setup;
>         $installer->startSetup();
> 
>         if (!$installer->tableExists('mageplaza_smtp_log')) {
>             $table = $installer->getConnection()
>                 ->newTable($installer->getTable('mageplaza_smtp_log'))
>                 ->addColumn('id', Table::TYPE_INTEGER, null, [
>                     'identity' => true,
>                     'nullable' => false,
>                     'primary' => true,
>                     'unsigned' => true,
>                 ], 'Log ID')
>                 ->addColumn('subject', Table::TYPE_TEXT, 255, ['nullable => false'], 'Email Subject')
>                 ->addColumn('email_content', Table::TYPE_TEXT, '64k', [], 'Email Content')
>                 ->addColumn('status', Table::TYPE_SMALLINT, 1, ['nullable' => false], 'Status')
>                 ->addColumn('created_at', Table::TYPE_TIMESTAMP, null, [], 'Created At')
>                 ->addIndex($installer->getIdxName('mageplaza_smtp_log', ['status']), ['status']);
> 
>             $installer->getConnection()->createTable($table);
>         }
> 
>         $installer->endSetup();
>     }
> }
>

**Comment by datvm1** [comment]
Hi,

For some reasons, part for creating table 'mageplaza_smtp_log' didn't run. Could you try upgrading again?
By updating the version to 1.1.1 in these 2 files:
Mageplaza/Smtp/Setup/UpgradeSchema.php
https://prnt.sc/irvgy0
Mageplaza/Smtp/etc/module.xml
https://prnt.sc/irvh01

You can get them in the link attached.
https://www.dropbox.com/s/iu1vhjwjfqdaggk/upgrade-smtp.zip?dl=0

After making these changes, please run upgrade command then deploy if needed.
php bin/magento setup:upgrade

**Comment by foxmasters** [comment]
thanks, but I had to delete the extension and reinstall it. and it works

**Comment by gixid192** [comment]
Great! We will close this issue from here.
