### ISSUE TITLE
Testmail not working with just website/store config

### ISSUE THREAD

**Issue by mvenghaus** [mageplaza/magento-2-smtp#58]
Hello,

Steps to reproduce:
- goto Under System > Conf > ..
- go to website edit and leave admin values blank
- enter valid smtp data
-> click send test mail without saving -> works
-> save data -> click send test mail -> wrong credentials

Thx in advance for fixing this :)

**Comment by gixid192** [comment]
Thanks for your report, we will check and let you know the result soon.

**Comment by mvenghaus** [comment]
#64

**Comment by gixid192** [comment]
Thanks for your PR, right now we uploaded a temporary fix in the master code. We need to verify your PR and check this issue further, we will let you know when new version released.

**Comment by gixid192** [comment]
@mvenghaus this issue has been fixed in the new version of the extension: 1.2.1
