### ISSUE TITLE
After installing Not sending confirmations mail to  new subscribers 

### ISSUE THREAD

**Issue by tousif12** [mageplaza/magento-2-smtp#60]
After installing SMTP with mail chimp , I am not getting confirmation emails to new subscribers.

**Comment by gixid192** [comment]
Did you mean only the newsletter emails or it's all other emails have the same problems?

**Comment by gixid192** [comment]
It looks like the issue comes from Magento itself, https://github.com/magento/magento2/issues/9010
Were you able to send newsletter before installing our extensions?

**Comment by tousif12** [comment]
@gixid192 
 yes It was sending but using mailchimp.

**Comment by gixid192** [comment]
I'm sorry that I'm not sure what you mean. My question is did it work with your default/native Magento without any third-party extension?

**Comment by gixid192** [comment]
Close due to no response within 7 days.
