### ISSUE TITLE
Invalid command or cannot parse to address

### ISSUE THREAD

**Issue by czettnersandor** [mageplaza/magento-2-smtp#61]
I have a strange error which I'm not sure where coming from.

The test emails are going out ok, I can also use the Magento contact form and the emails are going out ok through Mailgun. When it's coming to Order emails, the mail log is showing an "ERROR" label and no email is going out.

In the system.log, this message appears:

[2018-03-21 11:03:48] main.ERROR: Invalid command or cannot parse to address

I noticed the email address in case of order emails is in a format of `Firstname Lastname <user@domain.tld>` while the contact form emails "From:" part is just the email address.

I'm using Magento 2.2.3 and Mageplaza Smtp 1.1.3

**Comment by gixid192** [comment]
The order email form should be `email address` only. Are you using any third-party extensions to customize that part?
At the moment, our smtp extension only works with `email only`.

**Comment by czettnersandor** [comment]
I just checked an other store where the same extension is installed (v 1.1.2) and it looks like the Emails Log grid is the same, order emails are in a format of `Firstname Lastname <user@domain.tld>`, others are just emails. I have no clue what might be different that's causing this, both standard Magento 2.2.3. The one with the issue is running on Azure, the other one is on Digitalocean. No 3rd party extensions that are doing anything with emails. Although the one that's working has also Mailchimp installed, but emails are going through SMTP. The one not working has no extensions yet at all, just a fresh install of Magento 2.2.3.

Could you point out where this error message might come from? It's not found anywhere in the project folder, so might be the OS sendmail command?

**Comment by gixid192** [comment]
Did you mean you check the Log grid and see that `Firstname Lastname <user@domain.tld>`? It is not how it send, it just how it displayed. And if you noticed, we already remove that column in our latest version.
So if you have other places to look at, please let me know, that Log grid is not a correct place to assure that it is the email format.

**Comment by czettnersandor** [comment]
Apparently, this error message is sent back from Mailgun. It's because the address had trailing space.

Maybe trim the address before sending it?

**Comment by gixid192** [comment]
Please give me a picture of it (the whole picture of where you found it too please), I'm not sure if this issue comes from our extensions.

**Comment by czettnersandor** [comment]
To reproduce:

Go to Stores > Configuration > Sales > Sales Emails. Change "Send Order Email Copy To", add a space to the end of the field, then save config. Now try to send an order email with Mailgun.

Here is a screenshot of the configuration:
![Space after email](http://www.cohesiondigital.co.uk/ss/sandor/img-2018-03-27-170648.png)

Unfortunately Magento is not trimming the email on save, so it gets saved to the database like that.

**Comment by gixid192** [comment]
Thanks for your suggestion, we will put it in our next releases.
For now, please clear by hand. If you don't have any further problems, kindly help us close this issue from here.

**Comment by czettnersandor** [comment]
Initially I wanted to fix it myself, but this extension is only sending it to the Zend library, so it would take me a little more time. If you send me pointers where to trim the address, I can send a pull request. Maybe it's easier if you do it.

Anyway, closing ticket. Thank you for this great extension, it was really helpful.
