### ISSUE TITLE
Doesn't work in Magento 2.1.9

### ISSUE THREAD

**Issue by nelero** [mageplaza/magento-2-smtp#7]
When i activate module and put my authentication keys (Mailjet) nothing works.
if i send it with same credentials in a php page on my Magento installation => OK.

why the function is aroundSendMessage ? see https://www.ashsmith.io/magento2/transactional-emails-in-magento-2/

**Comment by tsauerwein** [comment]
The extension works for me with version 2.1.9. Are you able to send a test mail in the configuration?
