### ISSUE TITLE
Getting Error for undefined function

### ISSUE THREAD

**Issue by vinayaWD** [mageplaza/magento-2-smtp#70]
Hello,

When I'm trying to send email to customer for new account create, the mails are not sending and in log file I'm getting error "PHP Fatal error:  Call to undefined method Mageplaza\Smtp\Helper\Data::versionCompare() in /app/code/Mageplaza/Smtp/Mail/Transport.php on line 120"

Please check and update "Helper/Data.php" file.

Thanks

**Comment by datvm1** [comment]
Hi,

That method is declared in our Mageplaza Core module. Could you please check and see if you are using the latest version, 1.3.11?
You can download it here:
https://github.com/mageplaza/module-core/

**Comment by vinayaWD** [comment]
Hi,

Mageplaza Core and LayeredNavigation module was with theme (Porto theme), If I update Core then this may not be compatible the theme functionality.

Please suggest what should I do to resolve this?

Thanks

**Comment by datvm1** [comment]
Hi,

The latest version of Core module should be compatible. Please back up the old version and try updating it.
If it doesn't work well with LayeredNavigation module, although I'm fairly certain that it will, could you update LayeredNavigation too?

**Comment by vinayaWD** [comment]
Hi,

I tried but getting error "One or more Mageplaza extensions are not validated." in admin panel.

**Comment by datvm1** [comment]
Hi,

It is more likely a warning. You can follow that link to Smtp admin config and add an email to registration section.

**Comment by vinayaWD** [comment]
Which registration email?

**Comment by datvm1** [comment]
Hi,

You could use any email for it. Besides, this validation step is just a warning, it shouldn't interfere with functionality of Smtp module.

**Comment by gixid192** [comment]
Close due to no response within 7 days.

**Comment by manezaf8** [comment]
php doesn't have **mbstring** installed.

Go through this guide, it will give you more information on how to install it: http://php.net/manual/en/mbstring.installation.php

Ubuntu/Debian

`sudo apt-get install php-mbstring`

In case you are using PHP 7.x.

`sudo apt-get install php7.0-mbstring`

For Centos

`sudo yum install php-mbstring`

**Comment by leonmex** [comment]
please just change  from snake coding to camelcase PHPUnit\Framework\TestCase; that fix the problem:

use PHPUnit\Framework\TestCase;
