### ISSUE TITLE
magento-2-smtp installation issue

### ISSUE THREAD

**Issue by banyakart** [mageplaza/magento-2-smtp#72]
Hi 
can you guide me how to installation smtp. we trying 3 time, but getting error.

**Comment by gixid192** [comment]
May we know what error you are getting?

**Comment by banyakart** [comment]
done by self try.

thank you...

**Comment by gixid192** [comment]
@banyakart could you share with us what was the problem?

**Comment by banyakart** [comment]
Dear,

Actually that time was using free server of 1mb memory and. so getting
error in terminal. after upgrade done successfully. if got any other isuue
i will again contact you...

thank you

**Comment by gixid192** [comment]
Thank for your information.
