### ISSUE TITLE
Little issue with Port 25 and No secure protocol.

### ISSUE THREAD

**Issue by jordisalord** [mageplaza/magento-2-smtp#73]
Hi there,
First of all, thanks for that module.
It seems there's a little error when using port 25 and no security protocol.

It is at: /Mail/Rse/Mail.php, line 89.

I changed the code to:
```
...
            $this->_smtpOptions[$storeId] = [
                'type' => 'smtp',
                'host' => isset($configData['host']) ? $configData['host'] : '',
                'port' => isset($configData['port']) ? $configData['port'] : '',
                'auth' => isset($configData['authentication']) ? $configData['authentication'] : '',
                'username' => isset($configData['username']) ? $configData['username'] : '',
                'password' => isset($configData['password']) ? $this->encryptor->decrypt($configData['password']) : '',
            ];
	    
	    if (isset($configData['protocol'])) {
		$this->_smtpOptions[$storeId]['ssl']=$configData['protocol'];
	    }
...

```
Because if 'ssl' parameter is empty it gives some Zend errors, like:
`main.CRITICAL:  is unsupported SSL type`

I wish i'm not wrong, it solved my problem.

Jordi

**Comment by gixid192** [comment]
Thank so much for your contribution @jordisalord 
I updated this code in the dev version https://github.com/mageplaza/magento-2-smtp/commit/d5ebe1605878b827558eb83ddb9b69360bd42a49

I'm happy that you can use our extensions within your store, really appreciate your effort!
If you believe there is no issue left, kindly help us close this issue.

Thank you.

**Comment by gixid192** [comment]
Close due to now response in 7 days.
