### ISSUE TITLE
Oder email is not sent using Amazon SES

### ISSUE THREAD

**Issue by Alex1844** [mageplaza/magento-2-smtp#76]
I have configured everything correctly for Amazon SES (preconfigured Amazon SES does not exist) and tried the test email.
The test email works just fine.
Password reset email works just fine

I have placed the order and nothing was sent.
Then I enabled Email logging and went to Sales->Order, opened the existing order and clicked on Send Email.
Nothing was sent. The MagePlaza -> Email log shows the status for the email as ERROR. (The second email SUCCESS status is when I enabled Developer Mode, which of course did not send the email)

It is run on Magento 2.2.4. Asynchronous sending is disabled

I have poked around and apparently the Message From field of the message is empty for some reason if I leave Return-Path Email empty, even though the Order -> Sender is correctly configured in Sales Emails. The From field in Email Log still shows empty even if return Return-Path Email is configured and email sent.

![mageplazasmtp](https://user-images.githubusercontent.com/39203655/39974500-4e6e952a-56f7-11e8-8333-e75b5acdefcf.JPG)

**Comment by gixid192** [comment]
I'm not sure why this error happens. Kindly try an alternative approach:
Magento 2.2.4 shipped with Dotmailer Transaction Emails https://www.screencast.com/t/wSLA3bZsAZkZ
You can use it right away without registering an account.
Please check if it works for you.

**Comment by Alex1844** [comment]
What do I need to configure to get it going? I have tried just configuring DDG Transactional.

Nothing gets sent and this error gets logged
[2018-05-14 04:33:39] main.ERROR: Invalid MAIL FROM address provided
 [] []

**Comment by gixid192** [comment]
Kindly check if you changed your transactional emails to the registered email https://github.com/mageplaza/magento-2-smtp/issues/34#issuecomment-353074275
Transactional emails settings: https://www.screencast.com/t/XjoXzV0G

**Comment by Alex1844** [comment]
They are all configured correctly except the Custom Email 1 is empty

**Comment by Alex1844** [comment]
This should help you:

If I configure 'Send Order Email Copy To' in 'Sales Emails - > Order' then I get 'main.ERROR: From Header set twice' in system.log  
If i leave it empty, then I get 'main.ERROR: Invalid MAIL FROM address provided'

Apparently, your module uses Amazon SES username to fill "From" field, which is not an email address, thus the invalid mail error.
If I configure 'Send Order Email Copy To', then it tries to add it to From field, which already has the Amazon SES username configure, thus 'From Header set twice' error

What do we do from here?

**Comment by Alex1844** [comment]
No, it does not send anything and it logs 'main.ERROR: Invalid MAIL FROM address provided' in system log

**Comment by gixid192** [comment]
So it is not about that setting then, I suppose.
Actually, it is not about our extension, when you try with Dotmailer, which is another Smtp `tool` and it doesn't work, then it highly not from the `tools` but the server itself.
Are you able to share the SES credentials? Not here, but if you can, I will try with PHPmailer, which you can find here: https://github.com/PHPMailer/PHPMailer If you can't share, you can use that tool to test.

**Comment by Kroellie** [comment]
Same issue here, since update to 1.1.3 AWS SES not working anymore. Same symptoms + error logs. Please fix.

**Comment by Usman1493** [comment]
Was facing the same issue in Magento 2.2.5. 
Solved it using this [](https://github.com/sashas777/bug-from-email)
This is the only solution that worked for me
