### ISSUE TITLE
Amazon SES is missing

### ISSUE THREAD

**Issue by premgurung** [mageplaza/magento-2-smtp#77]
Hi 

installed MagePlaza latest version using composer but we are unable to see the amazon ses in smtp provider.

Below are steps followed to install MagePlaza.

1. Install via composer (recommend)
It’s easy to install, update and maintenance.

Run the following command in Magento 2 root folder:

composer require mageplaza/module-smtp
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

can someone please help us out in the above issues .

Regards
Prem

**Comment by gixid192** [comment]
Duplicated https://github.com/mageplaza/magento-2-smtp/issues/34

**Comment by premgurung** [comment]
@gixid192 

we have used keys are username and password and verified the email address but still getting the error message "Authentication Credentials Invalid"

**Comment by gixid192** [comment]
It is not about our extensions, kindly help us check again your credentials.
