### ISSUE TITLE
Amazon SES is missing

### ISSUE THREAD

**Issue by MunirajM** [mageplaza/magento-2-smtp#8]
This extension looks promising for Magento 2. I am not able to find Amazon SES provider which is actually required for me but its listed on available services on extension page. Is it possible to get any updated version which includes Amazon SES provider. 

Thanks for your awesome extension!

**Comment by tsauerwein** [comment]
Isn't it possible to use Amazon SES by directly providing the SMTP credentials? See http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html

**Comment by MunirajM** [comment]
Hi,

Thanks for your swift response!

Yes its possible however I usually used to do the SES integration by providing Access key and secret key for M1(https://drive.google.com/file/d/0ByrHa6EGF-jXLWN1emZxT0pkX0E/view) and I was looking for the same with this extension. 

Will there be any plan for integrating this in the near future?

Thanks

**Comment by gixid192** [comment]
Hi guys,

Amazon SES required more information, a pair of keys and then the email you want to use.
So technically, our SMTP doesn't support Amazon SES at the moment.

If you want to use it, you need to edit 2 files (Thanks to **Russel** with great help)
- app/code/Mageplaza/Smtp/Controller/Adminhtml/Index/Index.php on Line 114 (for email testing)
```
112                         $mail      = new \Zend_Mail();
113                         if ($params['username']) {
114                                 #$mail->setFrom($config['username']);
115                                 $mail->setFrom("support@domain.com");
```
- app/code/Mageplaza/Smtp/Application/Resource/Mail.php on Line 112. (transactional emails)
```
#$userName   = $this->smtpHelper->getConfig(self::CONFIGURATION_GROUP_SMTP, 'username');
$userName = "support@domain.com";
if ($userName && $senderName) {
      $message->clearFrom();
       $message->setFrom($userName, $senderName);
}
```

Where `support@domain.com` is used as your sender email.
![image](https://user-images.githubusercontent.com/8438046/32215548-d6d897bc-be54-11e7-82dd-5cf3a3f84a77.png)

You also need to verify the email before using it.

As @MunirajM stated, Access and Secret keys will be used as user and password correspondingly.

We are considering to add this in our code. Will available in next release.

**Comment by jspizziri** [comment]
@gixid192 ,

The issue you're referencing is the same as https://github.com/mageplaza/magento-2-smtp/issues/4.

@gwharton issued a pull request (https://github.com/mageplaza/magento-2-smtp/pull/14) which implements the fix that you're referencing however it was closed referencing a commit that doesn't actually resolve the issue by @imsamthomas .

It'd be nice to get this resolved.

**Comment by imsamthomas** [comment]
We fixed this already, please pull latest version
