### ISSUE TITLE
sender address on magento 2.2.4

### ISSUE THREAD

**Issue by polo2ro** [mageplaza/magento-2-smtp#80]
Hi,
The module does not work well with magento 2.2.4, in test mode the sender is correctly set in email but not for new orders.

**Comment by KlausGw** [comment]
Hi,
There is the same problem here.
But the emails to the customer go out.

**Comment by gixid192** [comment]
Hi guys,
This is a known bug from Magento https://github.com/magento/magento2/issues/14952
Here is the unofficial fix for this issue: https://github.com/sashas777/bug-from-email

**Comment by polo2ro** [comment]
Thanks!

**Comment by msawyers** [comment]
A simple fix instead of installing a module is to do like below until fixed in next release:

1. Goto >. ..../vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php
2. Edit function configureEmailTemplate() and add this line $this->transportBuilder->setFrom($this->identityContainer->getEmailIdentity());
to show like below:

protected function configureEmailTemplate()
    {
        $this->transportBuilder->setTemplateIdentifier($this->templateContainer->getTemplateId());
        $this->transportBuilder->setTemplateOptions($this->templateContainer->getTemplateOptions());
        $this->transportBuilder->setTemplateVars($this->templateContainer->getTemplateVars());
        $this->transportBuilder->setFrom($this->identityContainer->getEmailIdentity());

        //the below are commented
        //$this->transportBuilderByStore->setFromByStore(  
        //    $this->identityContainer->getEmailIdentity(), 
        //    $this->identityContainer->getStore()->getId() 
       // ); 
    }

Please note you are editing core file.

**Comment by ymarc77** [comment]
> Here is the unofficial fix for this issue: https://github.com/sashas777/bug-from-email

This solution doesn't work for me

**Comment by JoshuaFlood** [comment]
@ymarc77 did you ever work out the problem? I can't get it to work either, but it doesn't seem that there is any better SMTP solution and a hand-written one would, no doubt, look identical to this.

**Comment by ymarc77** [comment]
Yes, it works properly when this  script is enabled: https://github.com/sashas777/bug-from-email

**Comment by ci2014** [comment]
Do all the people, having that problem, have the amazon payments module installed? I think the error is to be found there.

This solved it:
https://github.com/amzn/amazon-payments-magento-2-plugin/pull/288/files

Thanks to:
https://github.com/magento/magento2/issues/14952#issuecomment-418943695

**Comment by Usman1493** [comment]
(https://github.com/sashas777/bug-from-email)
This is the only solution that worked for me... 
Thanks.

**Comment by ymarc77** [comment]
@Usman1493  Magento 2.2.6?

**Comment by Usman1493** [comment]
@ymarc77 Magento 2.2.5

**Comment by robertkent** [comment]
https://github.com/magento/magento2/issues/14952#issuecomment-425135300 might help?

**Comment by manojind** [comment]
Just install a small module on your magneto 2.2.5 that will work 


https://github.com/manojind/magento2.2.5-email-sender

**Comment by TechnoBuddhist** [comment]
> Do all the people, having that problem, have the amazon payments module installed? I think the error is to be found there.
> 
> This solved it:
> https://github.com/amzn/amazon-payments-magento-2-plugin/pull/288/files
> 
> Thanks to:
> [magento/magento2#14952 (comment)](https://github.com/magento/magento2/issues/14952#issuecomment-418943695)
> 
> ## Note
> This issue to to **Amazon Payment method**.

Thanks!! This resolved my issue on 2.2.5. I removed all Amazon_xxxx modules and all started working as expected!!

**Comment by iget-master** [comment]
Do anyone found how to fix it on 2.2.6? :-1:

**Comment by phpWebStudio** [comment]
> (https://github.com/sashas777/bug-from-email)
> This is the only solution that worked for me...
> Thanks.

I know I did it wrong, but I changed only: 
1) vendor/magento/framework/Mail/Template/TransportBuilder.php (add new method **setFromByStore**(), same as in module above)
2) vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php (fixed transportBuilderByStore to transportBuilder in the method **configureEmailTemplate**(), same as in module above )

Solved for me.
