### ISSUE TITLE
4.7.8 Error

### ISSUE THREAD

**Issue by nexxtcommerce** [mageplaza/magento-2-smtp#84]
By sending of test Email I bocome error 4.7.8 Error
How can I fix it.
I use Mandrill http://prntscr.com/jro84k

**Comment by zebeel** [comment]
Hi there,
Please go to https://mageplaza.freshdesk.com/helpdesk and open a new ticket. Our support team will help you check this issue. The support is free and to speed up the support process, please provide us the following information:

- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details. (should be able to read/write pub/ var/ folders)

**Comment by gixid192** [comment]
Close due to no response within 7 days.
