### ISSUE TITLE
'From' header is missing?

### ISSUE THREAD

**Issue by ymarc77** [mageplaza/magento-2-smtp#87]
Magento 2.2.4. Gmail blocks our emails sent via magento2smtp v 1.2.1. There is empty FROM header: <>

 Our system has detected that this message is
    550-5.7.1 not RFC 5322 compliant:
    550-5.7.1 'From' header is missing.
    550-5.7.1 To reduce the amount of spam sent to Gmail, this message has been
    550-5.7.1 blocked. Please visit

**Comment by ymarc77** [comment]
![voila_capture 2018-06-15_07-47-18_pm](https://user-images.githubusercontent.com/24270238/41482225-375c9736-70d5-11e8-954b-1f3ba656d98d.png)

**Comment by Bmacuser1** [comment]
Hi Marc. Did you find a solution for this? for us its not working with another fix of the magento 2.2.4 core bug.

**Comment by ymarc77** [comment]
I installed this fix: https://github.com/sashas777/bug-from-email
Now it works.

**Comment by LiamKarlMitchell** [comment]
Still a problem in 2.2.5
