### ISSUE TITLE
No Order Confirmation Emails sending when place order in frontend

### ISSUE THREAD

**Issue by minhducnho** [mageplaza/magento-2-smtp#88]
hi there,
When i configure it with mandrill and test mail is sent, it is successful. But when order placed or anything, it is not sending any email. No errors also. If i disabled your module or comment function aroundSendMessage in app/code/Mageplaza/Smtp/Mail/Transport.php, when place order, it send email successful.

I am using magento-2-smtp version 1.1.0 , Mageplaza Core version 1.0.0, Developer Mode is No 
Magento ver. 2.2.4, Developer Mode

**Comment by zebeel** [comment]
Hi,
Please check the Sending Domains and make sure your domain is verified.
http://prntscr.com/jzd50i

**Comment by nexxtcommerce** [comment]
I experience exactly the same error. My sending emailaddress is verified at mandrill (it is the domain marked later with myverifieddomain.com).

When i send a test-email (on the settings page of your module) it works. This one isn't stored at the Email Logs page of your module. I can find it in the Mandrill API Log, it goes through without problems.

When i send an order email (using the resend function in an order) i get a success message immediately in magento. The email is also stored in the Email Logs page of your module (and marked with Status Success). But it isn't delivered to my inbox. In the mandrill API logs, it gets rejected: "reject_reason": "invalid-sender"

The difference i see in the API logs: The successfull message adds "From: Owner <hello@myverifieddomain.com>" in the raw_message. The one not sent lacks this (so, it totally makes sense that Mandrill isn't sending it)

This is the successfull message:
{
    "raw_message": "Received: from localhost (unknown [104.xxx.xxx.xx])\n\t(Authenticated sender: rRVxxxxxxx@xxx.com)\n\tby relay-3.eu-west-1.relay-prod (Postfix) with ESMTPSA id E6A1826BFA\n\tfor <xxx@yyyy.com>; Fri, 29 Jun 2018 08:10:09 +0000 (UTC)\nFrom: Owner <hello@myverifieddomain.com>\nTo: xxx@yyy.com\nSubject: TEST EMAIL from Custom SMTP\nX-MC-Subaccount: nextesting\nContent-Type: text/html; charset=utf-8\nContent-Transfer-Encoding: quoted-printable\nContent-Disposition: inline\nMIME-Version: 1.0\n\n<p>Your store has been connected with a custom SMTP successfully. Now yo=\nu can Save Config and use this connection.</p>=0A<p>Sent via SMTP by htt=\nps://www.mageplaza.com</p>",
    "ip_pool": null,
    "from_email": null,
    "to": [
        "xxx@yyy.com"
    ],
    "return_path_domain": null,
    "send_at": null,
    "key": "rRVGxxxxxxx",
    "from_name": null,
    "async": false
}

Whereas the one blocked in the API:

{
    "raw_message": "Received: from localhost (unknown [104.xxx.xxx.xx])\n\t(Authenticated sender: rRVxxx@xxx.com)\n\tby relay-6.eu-west-1.relay-prod (Postfix) with ESMTPSA id 9950B26DF9\n\tfor <zzz@yyy.com>; Fri, 29 Jun 2018 08:23:27 +0000 (UTC)\nTo: XXX YYY <zzz@yyy.com>\nSubject: =?utf-8?B?SWhyZSBNYWluIFdlYnNpdGUgU3RvcmUgQmVzdGVsbGJlc3TDpHRpZ3VuZw==?=\nX-MC-Subaccount: nextesting\nContent-Type: text/html; charset=utf-8\nContent-Transfer-Encoding: quoted-printable\nContent-Disposition: inline\nMIME-Version: 1.0

... some email payload ...

</body>=0A</html>=\n=0A",
    "ip_pool": null,
    "async": false,
    "from_email": null,
    "key": "rRVGxxxx",
    "from_name": null,
    "send_at": null,
    "return_path_domain": null,
    "to": [
        "zzz@yyy.com"
    ]
}

I use Magento 2.2.4 and Mageplaza SMTP 1.2.1 

Do you have any ideas what causes this misbehaviour?

**Comment by zebeel** [comment]
Hi there,
Please follow this issue to know how to fix this: https://github.com/mageplaza/magento-2-smtp/issues/80#issuecomment-391565229

**Comment by nexxtcommerce** [comment]
great, thanks. Worked for me, problem solved
