### ISSUE TITLE
Magento 2 getting an issue while install

### ISSUE THREAD

**Issue by KnagarajuK** [mageplaza/magento-2-smtp#90]
Hi Team, 

While installing mageplaza smtp extension using composer getting an error as shown below in magento 2
```
                                                                                                                                        
  [Composer\Downloader\TransportException]                                                                                              
  The "https://repo.kensium.com/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                  
  Failed to enable crypto                                                                                                               
  failed to open stream: operation failed  
```
![index](https://user-images.githubusercontent.com/39402605/42455988-5309a322-83b1-11e8-94ea-5d4011d1447a.png)

Kindly advise me how to fix this issue?

**Comment by KnagarajuK** [comment]
As well trying to install module via download

getting like:-

1/7 [====>-----------------------]  14% 2 secs 58.0 MiBPHP Fatal error:  Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/html/realstreet/app/code/Mageplaza/Smtp/Helper/Data.php on line 31

Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/html/realstreet/app/code/Mageplaza/Smtp/Helper/Data.php on line 31

**Comment by Tuvpt** [comment]
if you install module via download, please install core module at this link: https://github.com/mageplaza/module-core

**Comment by SnowCommerceBrand** [comment]
@KnagarajuK This looks like more or less a problem with your composer Repo for SSL. 

https://github.com/composer/composer/issues/6529https://github.com/composer/composer/issues/6529

**not found in /var/www/html/realstreet/app/code/Mageplaza/Smtp/Helper/Data.php**
Also I think your missing the required mageplaza/module-core that is why

**Comment by Tuvpt** [comment]
We will close this ticket after 7 days without feedback
