### ISSUE TITLE
Wrong Sender used in store view

### ISSUE THREAD

**Issue by dennisderoo** [mageplaza/magento-2-smtp#94]
When I send a test mail from the configuration at a multi-store environment, then always the sender is used that is set under the default store view, not from the specific storeview.

![image](https://user-images.githubusercontent.com/1586567/43189538-14f22e04-8ff7-11e8-9823-72ba0786db2b.png)

For example; 
As General Contact under default config I have filled in "a@email.com".
As General Contact under a specific storeview config I have filled in "b@email.com".

When testing with the specific store view, it's always using "a@email.com" as sender instead of "b@email.com"

**Comment by datvm231** [comment]
Hi,

Thank you for reaching out to us.
This problem should be fixed with the latest commit in develop branch.
https://github.com/mageplaza/magento-2-smtp/commit/07d8ec041e5bf654a51f3dd2c78012c45430fbad

Kindly check it again and feel free to report if you find further problem.

**Comment by datvm231** [comment]
Close due to no response within 7 days.
