### ISSUE TITLE
Error : No body specified [ when clicked on Test Email ]

### ISSUE THREAD

**Issue by karthick-spartan** [mageplaza/magento-2-smtp#96]
Installed the plugin via composer and when testing the Email. I am getting this issue. Please find the below log information. 

main.CRITICAL: No body specified {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): No body specified at /var/www/html/vendor/mageplaza/module-smtp/Mail/Transport.php:116, Zend_Mail_Transport_Exception(code: 0): No body specified at /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php:284)"} []

I am using Gmail config. And currently using Magento ver. 2.2.5

Can someone help me on this. Stuck with this for a day.

**Comment by datvm1** [comment]
Hi,

Please make sure you are using the latest version of Mageplaza Core and SMPT modules.
In case you already are, do you have any other sending mail module installed?

**Comment by karthick-spartan** [comment]
Hi, Thank you for the reply, You are right there was some other plugin installed and after disabling that I was able to check the test mail. 

Thanks for your comment.
