### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by abdelkebir** [mageplaza/magento-2-smtp#97]
I have installed this extension into my client Magento 2.2.4 based website, when I try to test email sending I get a popup with the following message: 

> Error
> Network is unreachable

**Comment by datvm1** [comment]
Hi,

Firstly, you should check if your hosting/server is blocking port 25, 465, or 587.
Then check with your host provider about your mail server functionality. You can follow this instruction:
https://technet.microsoft.com/en-us/library/aa995718%28v=exchg.65%29.aspx

**Comment by deepak206** [comment]
I am also facing the same issue with 2.2.2 version, @datvm231 is there any solution for this problem?
