### ISSUE TITLE
Error accessing google smtp 

### ISSUE THREAD

**Issue by JoshuaFlood** [mageplaza/magento-2-smtp#99]
Upon sending a test e-mail I recieve the following error:

5.7.14 Please log in via 5.7.14 your web browser and then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 b124-v6sm7102305wmg.47 - gsmtp 

I have attempted to 'allow less secure apps' as recommended by google, enabled IMAP on my mail account and attempted the https://accounts.google.com/DisplayUnlockCaptcha method.

None of this works.

Thanks.

**Comment by datvm231** [comment]
Hi,

Make sure you allow access for the correct google account in these links:
https://accounts.google.com/DisplayUnlockCaptcha
https://myaccount.google.com/lesssecureapps
These are already all the neccessary steps for using Gmail SMTP.

Also try giving these access in private/incognito mode of your browser, then try sending test email in the same browser session.

**Comment by JoshuaFlood** [comment]
Not sure what was up with it but I never managed to solve this. Ended up using another account with Zoho, which still doesn't work but at least connects to the smtp server. I've read that Google has recently been causing lots of problems with SMTP. Might be worth comparing with the magepal module specifically for gmail smtp (though I haven't tested it myself).

**Comment by sumeet-synergytop** [comment]
@datvm231 
https://accounts.google.com/DisplayUnlockCaptcha
again and again i need to click on continue from that link

**Comment by andreabuffa001** [comment]
For those looking for an answer to the problem. I have magento 2.3.3 I loaded the default settings in "Load Settings" using Gmail. I set "Login" as authentication and entered the google email and instead of my gmail password a password created via google "App password". So it should work smoothly.
